### ISSUE TITLE
saving opening duplicated supersimplers loads wrong samples

### ISSUE THREAD

**Issue by jeremywen** [nysthi/nysthi#1]
## Steps

1. start with a new patch
2. add supersimpler
3. duplicate that module
4. load a different sample into the first slot of both.
5. close Rack (saved to autosave.vcv)
6. open Rack

## actual result

the samples in the first slot will now be the same sample

## expected result

they should load the correct samples that they were saved with

**Comment by nysthi** [comment]
Great catch!
I'll check! Thank you
probably the problem is for the simpler too...

**Comment by nysthi** [comment]
probably I forgot about duplication: they share the same ID... :)

**Comment by nysthi** [comment]
can't be solved, we need a new event from VCV Rack (at least 2 onVoluntaryDelete (when the user is deleting from menu) and  onClone)

**Comment by nysthi** [comment]
https://github.com/VCVRack/Rack/issues/425

**Comment by nysthi** [comment]
we need to wait for the rack 0.6.0
I need a "Clone" message to differentiate (Andrew knows about it)

**Comment by jeremywen** [comment]
👍

**Comment by nysthi** [comment]
still waiting for the API change

**Comment by VSpellbound** [comment]
Hi!

Can this be fixed in v 0.6 ?

**Comment by nysthi** [comment]
@VSpellbound @jeremywen  should be solved in
https://github.com/nysthi/nysthi/releases/tag/v0.6.2

**Comment by VSpellbound** [comment]
thanks!
