### ISSUE TITLE
CV input to Mouth in S.A.M.

### ISSUE THREAD

**Issue by midiguru23** [nysthi/nysthi#106]
Attaching a cable to the CV input of the Mouth parameter in S.A.M. causes the audio output to break up in a weird way. This is true even when the input value is zero and the trimpot for the CV input is also centered.

**Comment by midiguru23** [comment]
Following up on this, none of the CV inputs seems to work at all. The others just do nothing. The knobs work fine, but the CV inputs don't "turn the knobs." (This is in the Windows build.)

**Comment by nysthi** [comment]
good catch !
I mismatched the names of some variables 

repaired in version 0 6 33
