### ISSUE TITLE
Fresh repo ?

### ISSUE THREAD

**Issue by silvyn** [nysthi/nysthi#11]
Hi, I wanted to download nysthi plugin VCV, but can't find usefull stuff in release. The wiki is empty, etc..

Is it temporary or I miss somomething ?

Thinks

**Comment by nysthi** [comment]
in release there is the binary and the changelog.

**Comment by silvyn** [comment]
There was empty lasts days o_0. That's OK now and I run it on my Fedora 27.

**Comment by antoniotuzzi** [comment]
GREAT!
