### ISSUE TITLE
clock mult - how to stop?

### ISSUE THREAD

**Issue by rbreckenridge** [nysthi/nysthi#111]
I'm feeding an external clock (clocked) into ClockMult for the purpose of multiplying it 24x and sending it out to other things.

However, when I stop the main clock, ClockMult keeps outputting the 24x clock and there doesn't seem to be a way to stop it --- is there? I'd like for the multiplied clock to stop when the main one does...

**Comment by nysthi** [comment]
the clock is just a time computer, computes time using the input, but after, there is no relation between
clock and clockMULT
you want to use nysthi::bridge on the output to stop it (cutting it)
