### ISSUE TITLE
rxg 100 chan B silent

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#114]
I cannot get any sound out of rxg100 chanB
chan A is working perfectly
what am I missing?

**Comment by joopvdl** [comment]
hm. after restarting the patch, there's sound. but still much softer than chan A

**Comment by nysthi** [comment]
there is something strange happening, seems more memory related

I've got the same problem but is very random
I can't reproduce in a systematic way

**Comment by nysthi** [comment]
(it's happening in other effect of the same serie too)

**Comment by joopvdl** [comment]
Can I help in testing?

Op ma 10 dec. 2018 om 11:21 schreef nysthi <notifications@github.com>:

**Comment by nysthi** [comment]
the only is to describe a procedure that recreates systematically the bug!  
GOOD LUCK ! :D

**Comment by nysthi** [comment]
probably catched ! (I hope... )

is happening on WIN under stress

**Comment by nysthi** [comment]
in vers 0 6 37

**Comment by nysthi** [comment]
please recheck it... vers 0 6 37
