### ISSUE TITLE
request 2 sends to your new mixers.. No Returns

### ISSUE THREAD

**Issue by BoscoRemus** [nysthi/nysthi#115]
2 sends to your new mixers.. No Returns 
we can return on the inputs..
is it possible to do a new overlay page like the COMMANDS and the output jacks..

**Comment by nysthi** [comment]
I checked and it's too difficult to add a SEND (or 2 SENDs)  without destroying current coherence in the UI
I guess, you can easily simulate with second mixer, using all the POST OUTs
