### ISSUE TITLE
janneker pulse length

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#116]
Hey Antonio,

I was discussing the use of Janneker with Marc Boulé, because it's also a great tool to control his sequencers. He added a trig-to-next-sequence feature to the sequencers, on my request. But it turns out the sequencers do not respond properly to the pulse of Janneker.
According to Marc it has to do with pulse length, or something, not really my expertise. But you can ask him, if you need, he's certainly ok with that.

**Comment by nysthi** [comment]
my pulses are 0.0001 seconds long

**Comment by nysthi** [comment]
going to talk to him

**Comment by nysthi** [comment]
contacted, waiting for a reply

**Comment by joopvdl** [comment]
would you like me to send you my test patch?

**Comment by nysthi** [comment]
will be useless, I can't use any other modules in my development environment
what I can add is variable pulse size actionable via contextual menu
but would be better if Marc replies to my messages

**Comment by nysthi** [comment]
I recevied no reply from my question from Marc, maybe he thinks I'm a spammer
I changed unilaterally the pulses lengths from Jannekers from 0.1 msecs to 1 msec (that is the declared standard for Rack)

in 0.6.34

**Comment by joopvdl** [comment]
He responds quickly to Messenger, but he's in a different time zone of
course.


Op zo 9 dec. 2018 om 16:58 schreef nysthi <notifications@github.com>:

**Comment by nysthi** [comment]
resolved
