### ISSUE TITLE
Clock Mult: Divmode 

### ISSUE THREAD

**Issue by patman023** [nysthi/nysthi#117]
Request: add a divider mode to Clock Multiplier. 

Button Toggles all outputs to divide instead of mult.

**Comment by nysthi** [comment]
I like it :)
(becasue you can divide by 2, multiplying by 0.5, but people seems confused by it)

**Comment by patman023** [comment]
My brain doesn't want to math those numbers... 😂🤣😂

**Comment by nysthi** [comment]
done: visible in 0 6 34

**Comment by nysthi** [comment]
-- CLOCK MULTIPLIER
---- add DIVIDER explicit mode
---- the DIVIDER mode is common for all 3 clock MULT/DIV ers
---- the DIVIDER MODE is actived clicking on the "DIVIDER MODE" TAP button
---- until now the division was done multiply for number less than 1.0, for example to divide by 2
    you had to multiply for 0.5000 or to have a divide by 3 you had to multiply by 0.3333
    now you can activate the DIVIDER mode and set 2.0 and 3.0
---- renamed (visually) CLOCK MULT DIV

**Comment by nysthi** [comment]
released

**Comment by NRG70** [comment]
Hello friend!
Could you please add a rigger input for the RESET?
Also when the module is connected to CLOCK input, it should stop when there is no CLOCK coming in.
Otherwise it just keeps running/output messing the patch when the rest is stopped.

**Comment by nysthi** [comment]
please open a new issue witha feature request
