### ISSUE TITLE
Feature Request: Scala Quantizer

### ISSUE THREAD

**Issue by midiguru23** [nysthi/nysthi#118]
It appears the Scala Quantizer doesn't respond to negative voltages when it's set to midinote map mode. Anything below 0V it treats as 0V. Since 0V is Middle C (note 60) on a MIDI keyboard, to use a standard 5-octave MIDI keyboard it's necessary to shift the keyboard up by two octaves (so that note 60 is the bottom key).

This is not a big problem ... but it would be nice if midinote map mode could respond to incoming voltage values down to -3V (MIDI note 12).

**Comment by nysthi** [comment]
can't be done
the midi mode mode was added after and assumes voltages starting from 0
and I can't create more confusion adding an offsetter on board that works only for the midi note mode

**Comment by nysthi** [comment]
I reopen it, I want to investigate more

**Comment by nysthi** [comment]
probably I'll add a contextual menu that supports a start from -5v and from -3v

**Comment by nysthi** [comment]
ok added support for voltage offset when in midimapmode
both for SCALA QUANTIZER and EQUAL DIVISION QUANTIZER
will be released in 0.6.34

**Comment by nysthi** [comment]
released
