### ISSUE TITLE
Persistent functional failure of Smashmaster

### ISSUE THREAD

**Issue by 09philj** [nysthi/nysthi#121]
For no apparent reason Smashmaster no longer functions correctly in any patch. No matter what kind of signal is put in, or how the controls are set up, there is no output signal. The bypass function, however, still works properly. Reinstalling the plugin has not rectified the problem. 
![image](https://user-images.githubusercontent.com/46053472/50353327-ceac7d00-053f-11e9-8ecb-e13fe814f16f.png)
![image](https://user-images.githubusercontent.com/46053472/50353340-d8ce7b80-053f-11e9-9595-f96455b99ee1.png)

**Comment by 09philj** [comment]
I should point out that I only installed it today and that it stopped working after saving a patch containing Smashmaster, closing VCV Rack, then opening it again.

**Comment by 09philj** [comment]
Inexplicably it's started working again.

**Comment by 09philj** [comment]
It stopped working and started working again. I think it's something to do with autosaving or autoloading a patch containing the module but it doesn't happen every time.

**Comment by nysthi** [comment]
I need some time to check
a reproducible case would be great!

**Comment by nysthi** [comment]
this is driving me crazy!

**Comment by 09philj** [comment]
It happened again, I think it might be caused by trying to load a patch while under high CPU load.

**Comment by 09philj** [comment]
The solution is to close VCV, reduce CPU load, then re-open VCV.

**Comment by nysthi** [comment]
thank you for you effort! I reproduced it a couple of times on Windows
yes is something with connection to low memory and cpu load and so timing between things
if I'm in debug mode, never happens!
(it happened on OSX too, but MUCH less frequently)

**Comment by nysthi** [comment]
probably catched ! 
there will be a release 0 6 37

**Comment by nysthi** [comment]
please recheck on  0 6 37
