### ISSUE TITLE
DISFUNCTIONALCONVOLVZILLA suggestion

### ISSUE THREAD

**Issue by blackearth2014** [nysthi/nysthi#124]
Some of the impulse response audio files has a lot of top/bottom end. If there is space, can you add just a tilt feature for lowpass/highpass filtering?

**Comment by SmallTownSound** [comment]
Great timing..  I was just going to suggest the same thing, plus adding pre delay...

**Comment by blackearth2014** [comment]
Cool breeze

**Comment by SmallTownSound** [comment]
It is amazing what i little EQ can do on reverbs....

**Comment by nysthi** [comment]
do you want a filter on the Impulse or on the output  (after the impulse is applied) ?

**Comment by blackearth2014** [comment]
HP/LP filters on the impulses I think would be better than the output. If
we could see the curve as a 6db, 12db and 18db would be great.

**Comment by nysthi** [comment]
great suggestion the predelay too

but I have to rethink a little bit the UI

**Comment by nysthi** [comment]
@SmallTownSound please open a new issue, requesting the predelay, so I can put in the list of things to do!
thanks

**Comment by blackearth2014** [comment]
Cool breeze

**Comment by nysthi** [comment]
very difficult, in standby

**Comment by nysthi** [comment]
this feature is too expensive for my time to be adopted in this module

I won't do the LP/HP on the impulses
sorry

**Comment by blackearth2014** [comment]
It's all good.
