### ISSUE TITLE
Squonk: randomizing "A, B, C, D , E and Rep" separately

### ISSUE THREAD

**Issue by blackearth2014** [nysthi/nysthi#125]
Can we get a context menu feature to randomize "A, B, C, D , E and Rep" individually instead of all of them together.

**Comment by nysthi** [comment]
can be done, the big problem is that won't move the knobs
I have to do some experiment
👍

**Comment by blackearth2014** [comment]
Cool breeze

**Comment by nysthi** [comment]
in 0 6 37
