### ISSUE TITLE
Bug: BIGNUMBER (Beat Count) Reset

### ISSUE THREAD

**Issue by patman023** [nysthi/nysthi#128]
BIGNUMBER should reset to step 0 with Beat Count Mode on. 

It's that same annoying issue as with sequencers, where if a reset trigger sends the beat count to 1, then the next clock trigger (even if only microseconds afterwards) will increment the count to 2.

**Comment by patman023** [comment]
This is the issue/artifact I'm referring to. 
https://github.com/VCVRack/Rack/issues/938

**Comment by patman023** [comment]
and on looking at that thread, one way that was implemented was to ignore incrementing the (whatever) count for 1ms after a reset.

**Comment by patman023** [comment]
Also potentially affected: Squonk, µSEQ-1, µSEQ-2, 208-5steps

**Comment by nysthi** [comment]
what do you think if I adopt the same solution adopted for the "5 steps" ?
there is contextual menu "RESET to the NEXT CLOCK IN"

**Comment by nysthi** [comment]
(SQuonk, if you check is ok, because reset always to the LAST STEP,  not to the FIRST)

**Comment by nysthi** [comment]
probably µSEQ1 and µSEQ2 are affected

**Comment by patman023** [comment]
> 
> 
> what do you think if I adopt the same solution adopted for the "5 steps" ?
> there is contextual menu "RESET to the NEXT CLOCK IN"

you mean it holds the reset command until that time?

**Comment by nysthi** [comment]
yes

**Comment by nysthi** [comment]
it's like on the Nord Modular G2
you can do immediate reset on sequencers
OR
you can ARM a reset, that is executed next CLOCK is in

**Comment by patman023** [comment]
Gotcha. For something so (literally) display related, I'd suggest possibly adding an indicator at the bottom with "RESET QUEUED" or "RESET ARMED". Possibly black text on a green "background", like text backlit by an indicator on a 7-segment alarm clock? trying to upload an image but Github is failing me...

**Comment by patman023** [comment]
https://drive.google.com/open?id=1tNPrk5dGBJ7HAHlgG9vLHNnrtGpB4lpI

**Comment by nysthi** [comment]
in vers 0 6 38

**Comment by nysthi** [comment]
@patman023 
![screen shot 2019-01-06 at 20 17 06](https://user-images.githubusercontent.com/33201978/50740533-30cbda00-11f0-11e9-9421-f4f0d69ee068.png)

**Comment by nysthi** [comment]
"NEXT PULSE RESET" appear if the BIGNUMBER is in "RESET to the next clock IN"
if a RESET comes, the "RESET ARMED" appear (til next clock in)

**Comment by nysthi** [comment]
is out
