### ISSUE TITLE
SQ2 Crashing VCV Rack when rightclicking on 25% GATE

### ISSUE THREAD

**Issue by Petervos2018** [nysthi/nysthi#129]
Just try it yourself.

Greetings Peter.

**Comment by nysthi** [comment]
great, I'll verify, thank you

**Comment by nysthi** [comment]
defaults with right clicks are

NOTE : C2
CV2: 1.00
GATE: 25%
LENGHT:  1/16

**Comment by nysthi** [comment]
is out
