### ISSUE TITLE
Missing step when chaining Squonks

### ISSUE THREAD

**Issue by metaphorz** [nysthi/nysthi#13]
I am attaching a simpler version of what Klirrfaktor covered in his review of Squonk. There are two of them in the patch: let's call the one on the left S1 and the one on the right S2. When the patch first loads, there are some randomly high pitches coming out -- not sure why. But then it settles down.

But the main issue can be seen when hearing S1. S1 begins at 1 and goes through to 11. But exactly when S1 reaches 12, it plays S2's 1 instead of S1's 12. When S2 takes over, it seems to go from 1 to 12 correctly.  

I wasn't sure how to chain S1 and S2 together but I did something similar to Klirrfaktor. LAST is wired to the other START for both. LAST is also wired to STOP of that S.  This results in all 12 pitches being played for S2, but only 11 for S1.

[TestSquonk.vcv.zip](https://github.com/nysthi/nysthi/files/1544436/TestSquonk.vcv.zip)

**Comment by nysthi** [comment]
you are right @metaphorz ! I correct just yesterday!
wait for the next release! (it's a complex beast to debug!)

thank you, I'll keep you informed

**Comment by metaphorz** [comment]
Good to know. I was also curious exactly when the "Last" step port was triggered but assume that the trigger occurs so that the the handoff can occur successfully for the next Squonk.

**Comment by nysthi** [comment]
that is the problem: is triggering LAST step too early (when executing last step)
Also the RESET is resetting to wrong place

**Comment by metaphorz** [comment]
OK. I had also mentioned the issue with pitches being far too high when I started the patch. It settled down after 12 steps. Not sure if this is part of the same issue or another one. The issue was that when a stored patch started by opening the file, the pitches were not correct (they were too high for the knob settings).

**Comment by antoniotuzzi** [comment]
that's new, I'll investigate! Thank you!

**Comment by nysthi** [comment]
@metaphorz can't repro the pitch problem!

**Comment by metaphorz** [comment]
Let us know when you have a beta to test, and I’ll re-test pitch with that. It seemed
to be a transient issue, happening only at the start when the patch is first loaded.
-p

**Comment by nysthi** [comment]
check release!

**Comment by metaphorz** [comment]
Just did. Do you have an example of chained squonks? The one I am using is not working quite right.  S2 is going through all 12 but then back to 1 before S1 gets started. Perhaps I am not wiring it correctly.

On the pitch issue, when I loaded my prior patch, the pitches were very high so I had to move the octave knob on EvenVCO down two notches

**Comment by nysthi** [comment]
probably you are missing that when they are chained, the CV output is STEALED byt the chained S2 if/ the seq is in stop mode) ?

**Comment by metaphorz** [comment]
It seems that regardless of the specifics of stop mode, most users will expect that two Squonks
with N steps (N=12 for example) will proceed as follows:

S1-1, S1-2, ....S1-12, S2-1, S2-2, ....., S2-12

ad infinitum. That is not quite what happens and I cannot seem to create this perfect dual
sequencer operation. However, that is not all -- I cannot do it with SEQ-3 or another sequencer
(mscHack) - I know that the operation there is not chaining, but instead, clock division. Something is not working correctly. usually, the issue is that the first or last note in a sequencer is dropped when cycling.

**Comment by nysthi** [comment]
maybe the problem persists with 12 steps ? (I was testi with 4 and 4 )

**Comment by metaphorz** [comment]
It also occurs to me that the clock value might be the issue (floating point arithmetic). I just
took a patch that sequences two machack sequencers, each set for 4 notes for simplicity.

Things appear to be working. The BPM is set exactly at 60 which is divisible by 1 and 4.
Perhaps that is required for these sequencers to be precisely synchronized?

The thing is…I cannot find a way to accurate specify precise values with knobs. I am using
machack’s BPM clock and 60 is the low end so that is easy to set. But try setting a number
like:  64.00. It isn’t possible. Do you know a way? I tried with LOG’s DC offset and a Sum
module, but that didn’t work
-paul

**Comment by nysthi** [comment]
can't be a problem the number, everything is floating point 32 bits, everywhere
I have no idea how to setup a precise BPM, maybe using JW-Modules bpm tools ?
or ML-modules too !

**Comment by metaphorz** [comment]
I whipped up this which is probably similar to your 4-step sequencers. Look at S2 and I hear (and see) that is going like this

S2-2, S2-3, S2-4, S2-1 and then onto S1 which is not sounding right either. let me know if you get the same behavior on S2.

[TestSqonk2.vcv.zip](https://github.com/nysthi/nysthi/files/1552371/TestSqonk2.vcv.zip)

**Comment by nysthi** [comment]
I programmed a scale C4 to C5 in S1 and S2 with chaining and works, please check it

[TestSquonk2.vcv.zip](https://github.com/nysthi/nysthi/files/1552409/TestSquonk2.vcv.zip)

**Comment by metaphorz** [comment]
Sounds good - and good use of TUNA. I see that you connected S2's TRIG to S1's CHAIN TRIG.  I didn't do this--perhaps that was my problem? I also chained S1's TRIG to S2's CHAIN TRIG. Is that correct?

**Comment by nysthi** [comment]
test this: you'll understand why the trig chaining
[TestSquonk3.vcv.zip](https://github.com/nysthi/nysthi/files/1552639/TestSquonk3.vcv.zip)

**Comment by metaphorz** [comment]
Ok will test tonight

Paul Fishwick, PhD,
Chair, ACM SIGSIM
Distinguished University Chair of Arts & Technology and Professor of Computer Science
The University of Texas at Dallas
Arts & Technology
800 West Campbell Road, AT10
Richardson, TX 75080-3021
Lab: http://creative-automata.com
SIGSIM: http://modelingforeveryone.com
Twitter: @PaulFishwick

**Comment by antoniotuzzi** [comment]
in the meatime, thanks to these tests, I've found another bug, that I've corrected (first step was not doing ratchet when restarting
(next release you'll see it)

**Comment by metaphorz** [comment]
Glad that the bugs are being ironed out. It is a complex procedure to debug, I am sure. On my last point, adding one extra cable from S1-TRIG to S2-CHAINTRIG does not seem to affect the behavior, and that waws the nature of my last question: whether there should be symmetry:

S2-TRIG to S1-CHAINTRIG (as you had already), and
S1-TRIG to S2-CHAINTRIG (for symmetry)

-paul

**Comment by nysthi** [comment]
no, it's just a value copied because we want to connect all the 24 steps using just one port (the TRIG out GENERAL of S1)

all the chaining is done to avoid the use of external mixer (CV or AUDIO) and use MUTE button on them

in SQUONK the MUTE is automatic when S is stopped
and when STOPPED the main ports :  A  B  C  D  E  TRIG present (if there is something plugged) what is their correspondent CHAIN sockets

-Antonio

**Comment by metaphorz** [comment]
Since the LASTs connect both to STOP, and to START of the other sequencer, are these operations done simultaneously or one before the other?

**Comment by antoniotuzzi** [comment]
FROM today, STOP of S2 is happening exactly 7 samples after the START arrives to S1

(till yesterday was at the same sample)

**Comment by metaphorz** [comment]
Pardon my never-ending quetions, but how did you arrive at "7" ? By sample, I assume you mean the audio sample based on the current rate (e.g. 44.1Khz)

**Comment by nysthi** [comment]
you are right, I was considering the Start step of the other sequencer:
both START and STOP are arriving at the same time (8 samples after the sequencer hits LAST STEP

**Comment by nysthi** [comment]
FYI, I have changed it
the LAST signal is armed in last step and executed next time the program reenter the STEP() method (next sample). At this time, the TRIG is started on CABLES and will be received next time
so total delay from last step reached and received signal is 2 samples

**Comment by metaphorz** [comment]
Look forward to trying it.  Thanks
paul

**Comment by metaphorz** [comment]
BTW, The good news is that I have tested, informally, chaining SEQ3 and Machack and was unsuccessful.
You’d think that a clock division would do it, but it is not quite running right. So, you may have the only
trustworthy sequencer for chaining! Plus, I like the rotation, etc.
paul

**Comment by nysthi** [comment]
Hi Paul

thanks for your test (sincerely, without your effort I'd missed completely that step!)

if you have any request  for new features, please tell me!

Antonio

**Comment by nysthi** [comment]
published
v0.5.7

solving the missing reptitions
