### ISSUE TITLE
Jooper programming mode

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#130]
Hey Antonio,
I was thinking about the programming phase of the Jooper/Janneker combination. You know, when Janneker is in record mode.
In that phase, you want the switches in Jooper to wait for the next pulse. So you can "play" the music without strange humps and bumps. (We talked about it before) For that reason I am using ML trigger buffer. 
I've been suggesting to create an 8-channel buffer just for this, but wouln't it be possible to have a "programming" mode for Jooper? In this mode, all button presses will be buffered until the "add" command fom Janneker.
Only thing that might be something to be careful of, is that there is the possibility that, because now there would be a "add" and switching pulses at the same time, there could be a change of scenes getting mixed up.
I don't know how hard this would be, and if you would find it interesting to explore this, but anyway now you know the thinking process.

Joop

**Comment by nysthi** [comment]
sorry, you should explain better! Probably you advanced uses that I'm missing as I'm not a musician!

for me the Jooper is always in RECORD mode, waiting just for you to hit  "ADD"
but I'm missing for sure something from your discourse!

**Comment by joopvdl** [comment]
Here we go :)
How I see it, using Jooper can come in two stages, especially when used with Janneker.
stage one: creating scenes, creating song structure.
stage two: playing back the song you created.

I would not really call the first mode record mode, more like "programming" mode.

But let's make this much easier. Let's keep Jooper the way it is. Because maybe my use is a bit too specialized to make it a special function. I will make a description in the manual (it's partly there, already} and I am trying to explain to Omar how it works, so he can make a video.
The best way I can describe it:  Janneker operates on a musical time grid. This grid is the time between Janneker's pulse inputs. That can be one bar, 4 bars, one beat, etc. 
When you have Janneker control Jooper, you want Jooper to "snap" to that musical time grid, too. 
When you are in the second stage (the playback stage), Janneker will make sure that happens. Because it will send out triggers "quantized" to that musical time grid.
But in the first stage, you will make changes on Jooper. Switch inputs, outputs, etc. If you want those to happen "on the grid" you should push all buttons at once, exactly on the beat. That's not easy, and that's where a trigger buffer helps. You can now push buttons sometime before the change needs to happen. 
Pleas let me know if you now understand what I am saying, because I need to find words to explain this anyway (for the manual).

Anyway, so let's keep Jooper the way it is, it's perfect. 
Could you make something like ML's trigger buffer, but with 8 channels? That's 8 times input, output, and one trigger input to rule them all. The 8 inputs should be named "arm" or something like that.
like this:

trig in
arm1 - out1
arm2 - out2
arm3 - out3
arm4 - out4
arm5 - out5
arm6 - out6
arm7 - out7
arm8 - out8

So you"arm" a channel, and that channel will send a trigger out when the module receives a trig in at the trigger input.

**Comment by nysthi** [comment]
100% let's call it feature request for the multiple armed delayed trig
give the name to the module, and I'll put it in my project
(if I put it in the project, for sure I 'll do it)

we can work out all the functionalities we need

**Comment by joopvdl** [comment]
Let's call it Elsker.
I will explain later.

**Comment by nysthi** [comment]
elsker is in...
