### ISSUE TITLE
Bivio voltage on output

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#132]
If you feed BIVIO a constant voltage on the input, the "inactive" output will continue to output that voltage. Is that normal behaviour, or should it drop down to zero?

**Comment by joopvdl** [comment]
At least it makes a nice sample-and-hold like stepped output possible. Maybe a right click option could be nice? Because having the "off" output emit nothing, niente, nada, is also very useful.

**Comment by nysthi** [comment]
testing it

**Comment by nysthi** [comment]
yes, I remember I had a doubt about it

**Comment by nysthi** [comment]
categorized as feature request

**Comment by nysthi** [comment]
ok done
in 0 6 39

-- BIVIO
---- feature request
---- added a contextual menu to choose if the UNSELECTED output (for BIVIO1 and BIVIO2)
    should output LAST VOLTAGE (kind of sample & hold), or 0 VOLTAGE
