### ISSUE TITLE
Noise gate

### ISSUE THREAD

**Issue by pgatt** [nysthi/nysthi#134]
A noise gate for analog instruments. Preferably one that doesn't kill sustain.

**Comment by patman023** [comment]
So a tuneable release?

**Comment by pgatt** [comment]
Sounds good to me. And maybe a level knob?

**Comment by patman023** [comment]
any specific hardware you're thinking of as a good example?

**Comment by pgatt** [comment]
I’ve been playing with an emulation of a rocktron hush before that was quite good. I don’t have a lot of experience in this area though.

**Comment by nysthi** [comment]
ok! Closed! :D
