### ISSUE TITLE
BUG - NYECHOecoeco taps

### ISSUE THREAD

**Issue by patman023** [nysthi/nysthi#138]
Effect send taps fed unaltered into their same-numbered receives pass no signal

**Comment by nysthi** [comment]
meaning?
if I send 2 out and connect to the 2 IN nothing happens ?

**Comment by nysthi** [comment]
there has been a little of mismatch about the TAP IN TAP OUT

the TAP IN
is not inserting the audio onto the magnetic disk, but is substituting what the READ HEAD is reading from the DISK.

the TAPPED IN audio is then mixed to the other active HEAD and the result can be go in SWELL (feedback) and partially ri-recorded on disk

the TAP OUT
is just reading the DISK with the READ HEAD at that time and 

doing a direct connection on the same TAP IN and TAP OUT is like the same inner circuit, so is doing nothing (musically)

**Comment by patman023** [comment]
What I'm suggesting is that: 

- instead of doing nothing musically, and passing an uneffected signal (as if the tap in/out were bypassed/not connected at all) , 

- it converts into a null signal, effectively muting the Playhead.

**Comment by patman023** [comment]
And the phase variance introduced by the 1 sample delay (per @Vortico on the VCV forum) (in my case, 1/44100 ms) *should be* negligible at lower audio rates (ie bass).

**Comment by patman023** [comment]
https://youtu.be/LP59_wv8-0o

**Comment by nysthi** [comment]
thank you fro the GREAT video
going to check it, but I have a very complex and convoluted code in that area

I'm thinking to remove all the TAP IN 
@patman023 what do you think ?

**Comment by patman023** [comment]
I would suggest leaving it for compatibility reasons...

**Comment by nysthi** [comment]
solved in 0 6 40
