### ISSUE TITLE
Feature request for Hot Tuna

### ISSUE THREAD

**Issue by martin-lueders** [nysthi/nysthi#14]
Ciao,

I was thinking it could be a great addition for the Hot Tuna, if you could also output the pitch CV, which would put correspond to the frequency of the incoming signal. I was wondering whether one could then write a 'autotune' module for samplers, or other untuned oscillators (Elements for some Structure values) by comparing the output CV to the input CV of that module, and adjust the pitch CV such as to get the desired value (I hope it is understandable what I want to say...).

Martin

**Comment by nysthi** [comment]
I'm going to output the CV equivalent to incoming frequencies (using the CV out socket)

**Comment by nysthi** [comment]
published
v0.5.7
