### ISSUE TITLE
Elsker clocked

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#140]
Well, with those wonderful ideas you brought to Elsker, the next (and quite unavoidable) step would be Elsker Clocked, where you have a clock in, and can set delay and length in clock pulses (sort of like Janneker).

Adding just a reminder that, as you mentioned, we need an abort/reset button/trig input.

**Comment by nysthi** [comment]
reset added
randomize too

**Comment by antoniotuzzi** [comment]
that's an enormous task (I was checking it...)

**Comment by joopvdl** [comment]
it is?

**Comment by nysthi** [comment]
I should add 12 clock computers, 
when they are inserted the time in both field will be represented in PPM (pulse per minute)

**Comment by joopvdl** [comment]
yeah, probably quite a task.

**Comment by nysthi** [comment]
not abandoning the idea ;)

**Comment by nysthi** [comment]
I think if I do a clocked module, a GREAT companion would be a 12 lines CLOCKED delays

**Comment by joopvdl** [comment]
yes!
and gates, of course!

**Comment by nysthi** [comment]
this is done 
will be in 0.6.40

**Comment by joopvdl** [comment]
That's awesome.
