### ISSUE TITLE
Bivio/Bridges normalize clock to input

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#141]
I often use Bridges or Bivio to control a clock signal. For that, I usually have to connect the clock input and the main input to the clock.
Is it possible to normalize the clock input to the main input, when there's no connection on the main input?

**Comment by joopvdl** [comment]
Hm. I mean the trig input. But you probably guessed that.

**Comment by nysthi** [comment]
you are lazy ... :)
ok

**Comment by joopvdl** [comment]
yes, I am. But I always have to drag those wires all across the screen, and beyond, and then mis-plug them, and then I forgot where I was, etc...

**Comment by Funk-Burasuta** [comment]
Maybe having a CHAIN TRIG OUT and then patching it into the clock could do the job as good, as it removes the need to drag cables all over the screen, and/or if you need the clock for anything else, it can be sent to something like SQUONK or a Complex DAHD.

**Comment by joopvdl** [comment]
yes, that will work. So Bivio becomes a clock/trig hub as well.

**Comment by nysthi** [comment]
I don't think I have space in BIVIO to have a chain TRIG OUT
but it's a very good idea ! (to have a chain of BIVIOs too )

going to check

**Comment by joopvdl** [comment]
that's why I came with the normalize idea, because it doesn't take up
space.
