### ISSUE TITLE
8ch recorder 24bit recording error

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#143]
I get this when recording in 24 bit: similar waveforms, all with crackles. One time, the extension was wav3, but most of the time just wav.
win10. I have to add I am using two recorders simultaneously.

**Comment by nysthi** [comment]
sorry you need to give me more information and context.
Maybe a VCV file (using only nysthi modules) that is reproducing the case.

Are you saving on a different disk ? An external ? a Virtual ?


I tested on win10 using 2 multitrack recorder, at the same time
recording both at 24 bit
and the result is always correct 

(I tested also with the Master Recorder and standard recorder, using autosave or not, using PRE Choose file and not)

here a capture  from win 10 with a 24 multitrack open in OceanAudio too

![screen shot 2019-02-04 at 16 30 37](https://user-images.githubusercontent.com/33201978/52218299-a338e400-289a-11e9-9e03-73e31cea63e3.png)

**Comment by joopvdl** [comment]
I will do some more testing. I believe it has also functioned properly, so I don't know if I can reproduce it in a new patch. I can send you the patch where it happened (lots of Nysthi, but also other stuff ;)
At first I thought it had to do with the communication with the sound card, so that it's a sync problem. Funny thing is the red record Leds were blinking, but not synchronised like they usually do.
Could it be a buffer or cache problem?

**Comment by joopvdl** [comment]
Well today I created a patch, just Nysthi modules (and audio out) with two recorders, and they recorded fine.

**Comment by nysthi** [comment]
ok reopen it if you find a way to reproduce it

**Comment by joopvdl** [comment]
What if I send you the patch where it crackles? Would that help?

**Comment by nysthi** [comment]
send it to me
but seems more a resource problem, 

did you say you were using 2 recorders ?

**Comment by joopvdl** [comment]
that's right.
it's quite a heavy patch, but it records great on 16bit. some crackles when
recording, but not in the recording itself.

**Comment by nysthi** [comment]
closing
will reopen when replicable
