### ISSUE TITLE
Bivio probability 

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#144]
Right now, the Bivio probability attenuverter (and cv input) will give you more or less switching.
But wouldn't it be great if the probability attenuverter will give you more left/more right? So you can set the balance? More output 1, more output 2? 
You could also make this a right click option.

**Comment by nysthi** [comment]
so you want to exclude the probabily
and use the `probability` just as "DE-MIX" parameter ?

if 'probability` is set at 12, you want always the 50% of the signal to out A and 50 % out B ?
if at 11 60 % via A and 40% via B ? example

**Comment by joopvdl** [comment]
Well, yes, and no, because it keeps switching. So the signal always goes to A or to B, not to both. 
So at 12, there's 50% that Bivio will switch from A to B (or vice versa)
At 10, there's 60% chance that it will stay in A (when it's already in A) and 40% chance it will switch to B. 
When it's in B (still the dial is at 10) there's 40% chance it will stay in B, and 60% chance it will switch back to A.
So you can set the "rather A than B" chance value. 
Hope that's clear :)

**Comment by joopvdl** [comment]
guess you're right. I only use that for triggers, but now that you mention
it, I realise it can also be used for cv. But it cannot route two into one
(like Oivib).

**Comment by joopvdl** [comment]
Just checked, Bernouilli gate can only be used to pass triggers (pulses, clock signals) to A or B, with probability.
So that means this functionality is still not yet available. And (commercial voice on) it can be sooo useful to route two cv signals into a whatever. Or the other way around. Especially with cv controlled probability. Then you can tell your virtual drummer to start lightly, and play more intensely as the song progresses. For instance.

**Comment by joopvdl** [comment]
Well, I just remembered there were some switches very much like I proposed here. PvC Heads and PvC Tails are two-to-one and one-to-two switches with probability and all sorts of extras, like trig and gate out on switching moments, etc. I even helped developing them (a bit) But I thought they had disappeared, the developer seems to have abandoned the VCV ship, and I doubt they will survive the 1.0 transition. Unless someone picks it up, it's open source, after all.

**Comment by nysthi** [comment]
ok, changed but I need a name
In the normal mode (as it is now)
the probability is the probability to move from the current position
so the history is important, 
for example if you are on B
and probabiliy is at 5% means the only 1 times on 20 (on average) the bivio switch to A
(and viceversa)

in the new mode is the probability to go to A or to B
the starting position is not important
if the probability is at 5%, 19 times out of 20 will switch to A, always 

I 've called it "USE equal probabilities in the middle"
but I don't like the name

**Comment by joopvdl** [comment]
what about mode 1: A/B switching probability
mode 2 (the new one) A/B routing probability

**Comment by nysthi** [comment]
I need a name for the menu
do you propose to have 2 menu items ? with full title ? (can be done)

"USE A/B switching probability mode" (the current mode, and default mode)
and
"USE A/B routing probability mode"

a checkflag will indicate the active mode

**Comment by joopvdl** [comment]
well, to me that would be explaining the functionality pretty clearly, so
why not?

**Comment by nysthi** [comment]
done will be in 0.6.40

**Comment by joopvdl** [comment]
now I'm curious, where did the name Bivio come from?

**Comment by nysthi** [comment]
Bivio means fork, bifurcation in italian
a crossroad where one road goes in 2 roads, and you have to choose

**Comment by nysthi** [comment]
pronounced beeveeou (english)
