### ISSUE TITLE
elsker one-shot

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#145]
Well, sorry for my quite intrusive presence here, but I'm just studying the modules for manual writing purposes. So I'm giving them a really good inspection :)

Anyway, I think Elsker should have a one-shot mode. Where "activate' will be switched off after a pulse has been sent. So a next pulse will only be sent when "activate" wil be activated again.

**Comment by nysthi** [comment]
interesting, but I've got no space
have to study

**Comment by nysthi** [comment]
one shot mode added
will be in 0 6 40
