### ISSUE TITLE
Equal Division Quantizer Arithmetic

### ISSUE THREAD

**Issue by midiguru23** [nysthi/nysthi#146]
Trying out various things with Equal Division Quantizer.... I'm assuming that the second value (equal divisions of...) is intended to be a frequency ratio, not a "voltage" offset. This seems to be a good assumption, because 2.0000 produces octave divisions. If this were a voltage value, a value of 1.0000 would produce steps per octave.

The more general problem is that the values of the outputs for channels 2 and 4 are sometimes slightly different from the values for channels 1 and 3 with inputs at 0.0000. This may be an intermittent problem.

At times, a small negative input can cause the output to have a small positive value.

When I choose a small number of steps, there will sometimes be an "extra" step near zero.

The arithmetic is only useful when I choose equal divisions of 2.0000. Any other value here, such as 3.0000 (for the well-known Bohlen-Pierce tunings) does not produce accurate results when one of the inputs is stepped upward so as to produce what ought to be 3.0000 (in this case, a perfect octave + a perfect 5th, a ratio of 3:1). I get a perfect Bohlen-Pierce 3:1 interval when I set equal divisions of 2.9910 ... but this is with 15.000 steps. If I go to 16.000 steps, I get a good interval with equal divisions of 2.9092. I don't think this should be the case. As long as the number of steps is an integer, any setting for "equal divisions of" should produce the same output.

Using the Fixed Voltage Source module, I find that I get a perfect 7:4 ratio (with the first oscillator at 0.000V) with a voltage output of 0.848. But with equal divisions of 1.75, the output for that scale step is 0.84437, or perhaps 0.84422. It's too low.

**Comment by nysthi** [comment]
thanks for the report
I'm going to do a check!
maybe I missed all the maths... :D

**Comment by nysthi** [comment]
I created this spread sheet with inner math of the module

https://docs.google.com/spreadsheets/d/1nQGmHF4biEu7_ChY5fD3AdONKApbmyIk3y59ajmNArw/edit?usp=sharing

there a re very small deviations, but the voltages generated are perfectly aligned

there is something wrong for IN - OUT  2 , 3 and 4 (maybe when incoming voltage is zero, I have to investigate more
)

**Comment by nysthi** [comment]
I've implemented a new GRID engine base on the calculation demonstrated on the spreadsheet I've sent you

the GRID is exactly the same

the grid is not an exact division, is an exponential space (cents are exponentials)


and if I set the grid to  13 - 3 I've the EXACT  Bohlen–Pierce_scale EQUAL temperated

https://en.wikipedia.org/wiki/Bohlen–Pierce_scale


anyway I've left the old quantising in too, (defaulting to the new one) (use the menu to jump to the old one)

**Comment by nysthi** [comment]
solved in 0 6 40
