### ISSUE TITLE
Equal Division Quantizer Arithmetic (6.40)

### ISSUE THREAD

**Issue by midiguru23** [nysthi/nysthi#149]
In 6.40 the tuning issues I observed in 6.39 are still present. Basically, if we go to equal divisions of anything but 2.0, the output is not correct. A 0.0 input should always produce a 0.0 output, but it doesn't. In addition, an integer number of divisions for 2.5 should produce a perfect 5:2 interval, and an integer number of divisions for 3.0 should produce a perfect 3:1 interval, but they don't. github doesn't allow videos to be uploaded, which seems a bit restrictive. I'll put the video on my website server at www.musicwords.net/quantizer.wmv. The desired and actual values are shown in the video, along with a scope to display the relation between the two pitches.

**Comment by nysthi** [comment]
I presented a spreadsheet demonstrating all the inner grids
and demonstrating how the EQUAL TEMPERED scales are perfectly respected
https://docs.google.com/spreadsheets/d/1nQGmHF4biEu7_ChY5fD3AdONKApbmyIk3y59ajmNArw/edit#gid=0

the data I'm creating is perfectly aligned with equal tempered described here
https://en.wikipedia.org/wiki/Bohlen%E2%80%93Pierce_scale

**Comment by nysthi** [comment]
maybe there is an offset problem ? but you can correct easily using the TUNING param
if I set  13EDO3 and tuning to 0.10  (dragging to the very right with a lot of resolutions) 
I get: 0.0 to 0.0
if I set to 1.0 -> 1.09728 (step 8 in spreadsheet)
if I set to 2.0 -> 2.0726  (step 17 in spread sheet)
and so on
![screen shot 2019-02-18 at 21 24 55](https://user-images.githubusercontent.com/33201978/52975002-f5622500-33c3-11e9-81a3-9b5a6070e251.png)
![screen shot 2019-02-18 at 21 26 58](https://user-images.githubusercontent.com/33201978/52975008-f98e4280-33c3-11e9-81ea-b5774bb8a04f.png)

**Comment by nysthi** [comment]
I'm going to add and auto offset to 0.0 -> 0.0 for every computation...

**Comment by nysthi** [comment]
added offset, now 0.0 will ouput 0.0 ...

**Comment by nysthi** [comment]
please check verison 6.42
