### ISSUE TITLE
HOTTUNA Bug/Feature request

### ISSUE THREAD

**Issue by odahan** [nysthi/nysthi#15]
Hi !
This is perhaps a feature but it can be seen as a bug : When CV is used as input ("in voltage"), Hottuna is as slow to display the note name than in audio mode ("in signal"). 
This is really annoying since there is a simple match between volts and note names in a 1V/octave system, so it can be computed in a snap.
In audio mode there can be some lag for computation, perhaps it can be faster (the faster the better) but for "volt mode" the display should be fast as a lightning.
So feature request or bug correction, that is the question ! :-)

**Comment by nysthi** [comment]
published
v0.5.7
