### ISSUE TITLE
Adding passthru outputs for GraphicMeter

### ISSUE THREAD

**Issue by brickzone** [nysthi/nysthi#151]
Could you add passthru outputs in the GraphingMeter module? That's awesome now. But I like loot at all CVs connected to it and then choose the right cable...it's a little bit mess. So passthru outputs (for example on the right side) will be amazing! Thanks in advance!

**Comment by nysthi** [comment]
will be in version 0 6 42 👍 
![screen shot 2019-02-20 at 10 56 14](https://user-images.githubusercontent.com/33201978/53083372-15e2ca00-34ff-11e9-8f1b-ba675e0c5c65.png)
