### ISSUE TITLE
NY Echo rotating graphic.

### ISSUE THREAD

**Issue by veryfungi** [nysthi/nysthi#152]
hello Antonio, I was wanting to experiment with your NY Echo module but found an odd situation that the rotating disk always turning is distracting and causes a bit of vertigo. :( Perhaps if you made a lower contrast grey on grey disk and make an option to keep it selected...

**Comment by nysthi** [comment]
if it's just a color problem, you can change the disk in
YOURRACKINSTALL/plugins/nysthi/res/shapes/JIRAJIRADISK.svg
(attaching one all gray: you should see a stopped disk)
[JIRAJIRADISK.svg.zip](https://github.com/nysthi/nysthi/files/2889140/JIRAJIRADISK.svg.zip)
![screen shot 2019-02-21 at 12 58 45](https://user-images.githubusercontent.com/33201978/53167555-86a9e500-35d8-11e9-96b0-749120c12923.png)

**Comment by veryfungi** [comment]
This should fix the problem, thanks. Do I need to copy the file into the folder every time there is an update? Thanks again!

**Comment by antoniotuzzi** [comment]
yes, because Rack never offered an a directory for storage of perennial data (external to the Rack dir)
