### ISSUE TITLE
4hands global portamento saving

### ISSUE THREAD

**Issue by brickzone** [nysthi/nysthi#155]
So for example I want use all  presets in one instance of module for mixer, so I want some fixed portamento control which can record global value when I hit a save or add button. Is this possible to do?) So boring tap value for portamento it in every window. Cheers

**Comment by nysthi** [comment]
can be done
So you want a way to set a portamento for all 10 fields in one shot ? Correct ?

**Comment by brickzone** [comment]
yes, exactly!

**Comment by nysthi** [comment]
in v1.0.0
---- feature request: added dragging displays with WIN-KEY modifier (CMD-KEY for MAC)
    when dragging on value display with the modifier, the dragging will set the value for all the values in the same category
    for example, if you drag on one of the "PORTAMENTO" value with the modifier and the value is set to 0.80
    all 10 PORTAMENTOs will be set to 0.80 (in real time).
    Same applies for the 10 VOLTAGE A and for the 10 VOLTAGE B values
