### ISSUE TITLE
Recorders -6 / -12 db

### ISSUE THREAD

**Issue by NRG70** [nysthi/nysthi#156]
Hi Antonio!

could you please add a switch/option for optionally -6 and -12 db on all inputs simultaneously.
Sometimes can not change the mix in the patch path, so the sound is too loud for the recorded output.
A 6 or 12 db cut will help a lot in those cases!

**Comment by nysthi** [comment]
sure
will find a way to add it!

**Comment by NRG70** [comment]
Excellente!!

**Comment by nysthi** [comment]
in v1.0.0 
added input attenuations for all 4 recorders
0dB -6dB -12dB -24dB

**Comment by NRG70** [comment]
thanks!!!

**Comment by nysthi** [comment]
reopened
... till the version in shipped... ;)

**Comment by NRG70** [comment]
ah ok! i'm still github newbie :)))

**Comment by nysthi** [comment]
no problema! It's only for me to know when things are released ! (I have too many requests to fulfill!)
