### ISSUE TITLE
UNNSYTHIPLEASURESGRAPHER stops graphing

### ISSUE THREAD

**Issue by joemcmahon** [nysthi/nysthi#157]
I've got a patch that's running a couple instances of UNNSYTHIPLEASURESGRAPHER that stops showing the graph after a while. Restarts and reloads don't seem to correct the issue. I can upload a patch that demonstrates this if you want it.

**Comment by nysthi** [comment]
only if you have a patch that is using only NYSTHI modules 

what's your OS and computer ?
and what version of VCV Rack ? the official 0.6.x ?

**Comment by joemcmahon** [comment]
OS X Mojave 10.14.3, 2018 Macbook Pro. Official 0.6.2c.

I did manage to get the graphers that had stopped graphing to restart by loading a patch that contained a single instance. Don't know if there's a rogue global variable causing trouble, maybe, or a singleton. The patch is relatively simple, with a Turing Machine running an Audible Instruments modal synthesizer through an AS Delay Plus. 

Since I was able to get them to reset, we can close for now, or you can re-open low-priority.

**Comment by nysthi** [comment]
to be checked

**Comment by nysthi** [comment]
let's wait for v1
