### ISSUE TITLE
NYSTHI not loading on linux

### ISSUE THREAD

**Issue by LOGUNIVPM** [nysthi/nysthi#158]
From the log:

[0.865 warn src/plugin.cpp:90] Failed to load library /home/leopard/.Rack/plugins/NYSTHI/plugin.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/leopard/.Rack/plugins/NYSTHI/plugin.so)

20+ other plugins are loading correctly.
My sistem: Rack 0.6.2c, Linux Mint 18.1 (4.4.0-139-generic #165-Ubuntu SMP x86_64)
The latest GLIBCXX I have is: (strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX)
GLIBCXX_3.4.21

I am currently unaware of a more recent version of libstdc++ for my system to upgrade to.

**Comment by patman023** [comment]
I'm assuming you've checked ppas and the like?

**Comment by leopard86** [comment]
Well I've quickly tried a couple of solutions but they failed (my fault, I just gave up too fast). I'm just wondering whether compiling against too recent libraries is sane. Are we fostering a deprived Apple-style upgrade-to-latest-unstable policy? :)

**Comment by nysthi** [comment]
I'm using a debian 26 to compile on a virtual  box running on a win 10 OS, and I use it just to have linux version. Sorry about that but I don't know how to solve it!

**Comment by nysthi** [comment]
shipped in 1.0.1 (compiling on UBUNTU 16.04)
