### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by Miserlou** [nysthi/nysthi#16]
Hi, great modules, but it looks like you forgot to include the `src` directory!

**Comment by phdsg** [comment]
https://github.com/nysthi/nysthi/issues/8

**Comment by Miserlou** [comment]
Hm. That's a shame.. you might want to remove the license file then, since that says this is a free software project, which it isn't. But really, you should just release the source. >_>

**Comment by nysthi** [comment]
correct, I removed the license

**Comment by alikins** [comment]
@nysthi https://github.com/nysthi/nysthi/releases/download/v0.5.13/NYSTHI.zip still (unintentionally?) has a copy of gpl.-3.0.txt and a LICENSE.txt in it.

```
[newswoop:F27:Downloads]$ unzip NYSTHI.zip 
Archive:  NYSTHI.zip
   creating: NYSTHI/
  inflating: NYSTHI/CHANGELOG.txt    
  inflating: NYSTHI/gpl-3.0.txt      
  inflating: NYSTHI/LICENSE.txt      
  inflating: NYSTHI/plugin.dll       
  inflating: NYSTHI/plugin.dylib     
  inflating: NYSTHI/plugin.so        
...
```

**Comment by patman023** [comment]
@nysthi recommend close
