### ISSUE TITLE
LED images bleed through module browser

### ISSUE THREAD

**Issue by jonheal** [nysthi/nysthi#160]
The bottom-most LED images bleed through module browser background. See attached image.

![Bleed](https://user-images.githubusercontent.com/33180867/54622292-b7e2cd00-4a3f-11e9-8c8d-e85fec066a2a.png)

EDIT: Actually, other devices of yours with small IED indicators have the same behavior, such as MONORECORDER and Single Slim VU Meter.

But I hate even bringing this stuff up, because you are a great Roman God.

**Comment by spectromas** [comment]
I can replicate this on linux.

**Comment by jonheal** [comment]
Second EDIT: Maybe it's a Module Browser bug.

https://community.vcvrack.com/t/trying-to-find-the-right-mixer-set-up-tips/2405/16?u=jon

**Comment by nysthi** [comment]
thank you for the report
investigating

**Comment by patman023** [comment]
Win10, it happens with the "CPU" meters as well. Suspect Rack is to blame.

**Comment by nysthi** [comment]
not a bug
it's the Menu that contains holes
