### ISSUE TITLE
FeatReq: Mixers - Input Pad/Output Saturation

### ISSUE THREAD

**Issue by patman023** [nysthi/nysthi#161]
Context menu switches:
Pad all channel inputs by [0,-6,-12] dB
Saturate all channel outputs at [0,+3,+6] dB (or other reasonable thresholds) (RMS/Peak Switch?)

**Comment by nysthi** [comment]
in v1.0.0

-- 4MIX 8MIX 16MIX
---- feature request: added global input (valid for every channel) attenuation via context menu (0dB, - 6dB, -12dB, -24dB)
---- feature request: added MASTER limiter via context menu, with NO LIMITS, HARD LIMIT +0dB, +3dB, +6dB, and SOFT LIMIT at +0dB and +3dB

**Comment by spectromas** [comment]
Fantastic, thanks
