### ISSUE TITLE
Tunathor

### ISSUE THREAD

**Issue by molluskderek** [nysthi/nysthi#162]
Using Tunathor 0.6.42 and VCV Rack 0.6.2c, I calibrated my ES-8 nicely. But there is no way to save the calibration (context menu "save preset" doesn't appear to work), nor does Tunathor recover current settings after closing VCV and reopening it with Tunathor already present.

This would be super helpful to be able to save more easily and not have to re-calibrate every time the app re-opens. This way I can have all my calibration instances present every time VCV opens.

**Comment by nysthi** [comment]
in v1.0.0
save mapping in the patch
+ is possible to save as preset too...

-- TUNATHOR
---- debug: solved the semitone mode that was never finishing the calibration
---- debug: solved the problem of the ADDED +3V when was in MAP mode (@Steve...)
---- feature request: maintain and save last mapping, to be reused and reused
    (works also if you save the preset!)
