### ISSUE TITLE
Tunathor -3V issue

### ISSUE THREAD

**Issue by Torinbob** [nysthi/nysthi#164]
Tunathor does not seem to accept negative voltages and calibrates 0v to 32hz

Would be good to either calibrate -3v to 32hz (so it works at same voltage/hz ratio as sequencers like Phrase Seq) or have a contextual menu option which adds 3v before the calibrated output so that octave values on sequencers and returned pitches match.

**Comment by nysthi** [comment]
I'm going to correct the skew releasing the 1.0

**Comment by nysthi** [comment]
solved in v1.0.0

-- TUNATHOR
---- debug: solved the semitone mode that was never finishing the calibration
---- debug: solved the problem of the ADDED +3V when was in MAP mode (@Steve...)
---- feature request: maintain and save last mapping, to be reused and reused
    (works also if you save the preset!)
