### ISSUE TITLE
[feature request] Include patch name in autosave of MasterRecorder

### ISSUE THREAD

**Issue by spectromas** [nysthi/nysthi#165]
Title says it all really, I like to use the autosave recording feature a lot but you end up with a lot of unidentifiable files which is troublesome when you work on different patches often. As well as the timestamp why not add the patch name, if it exists, to the end of the file? It would make it much easier to find recordings of a particular patch.

**Comment by nysthi** [comment]
1) the patch name is unavailable till the patch is saved
2) from a module accessing the file name is breaking some rules

but I'll investigate
the name is created in a way to avoid any possible collision

**Comment by spectromas** [comment]
For 1. I think it could be left as it currently is, doesn't seem much point in altering/appending the file name if the patch has no name. 

Collision wouldn't be any more of an issue than it is at the moment if the patch name just added to the end. I'm sure some people would like it at the beginning but I actually like the current naming pattern so my vote would be for the name to be appended to the end (as opposed to replacing the current format).

**Comment by nysthi** [comment]
in v1.0.0

-- MASTER RECORDER 1, MONORECORDER, MASTER RECORDER 2, MULTITRACK RECORDER
---- feature request: if the name of the patch exists, prepend it to the autosaving files
    or to the proposed filenames
