### ISSUE TITLE
DC offset problem with Convolvzilla

### ISSUE THREAD

**Issue by stepton-thudfoot** [nysthi/nysthi#166]
Impulses that have DC offset can result in an extreme offset to the point of clipping to silence. This can apparently be resolved by passing it through 4DCBlock or by removing DC offset from the impulse itself.

Issue opened at the request of Antonio, who may add a dcblock directly to the convolver.

Attached is an impulse that produces this problem.

[RoomPool.zip](https://github.com/nysthi/nysthi/files/3025945/RoomPool.zip)

**Comment by nysthi** [comment]
thanks!

I'm going definitively to add the improvement

**Comment by nysthi** [comment]
solved in v1.0.0

-- CONVOLVZILLA
---- added a DEFAULT ON DC block filter on the output: the filter can be set OFF using contextual menu
---- solved a crash when changing block size
