### ISSUE TITLE
Hot Tuna results in NAN.

### ISSUE THREAD

**Issue by martin-lueders** [nysthi/nysthi#17]
Sometimes, when the incoming sound is not well defined, e.g. noise, the result of the pitch CV output is NAN, which sends some plugins (e.g. Vult Lateralus) into Nirvana.  Please, try to avoid NANs on the output, as they propagate through modules.

You can check for NANs for instance using my Voltmeter, which displays NAN when it finds one.

Cheers,
Martin

**Comment by nysthi** [comment]
I'll check it

**Comment by nysthi** [comment]
solved for the next release

**Comment by nysthi** [comment]
solved in release 0.5.12
