### ISSUE TITLE
Modules request: Voltage segmenter

### ISSUE THREAD

**Issue by pgatt** [nysthi/nysthi#171]
Hi Antonio, finally getting round to raising my module request from the other day, I also thought of two more:

1. Voltage segmenter - my idea for this was to have a selectable voltage range. - (0-1V, 0-10V, etc. prefer ably freely selectable like the range from RJ Modules) and then have it splittable into a editable number of "segments", so basically a quantiser but not for notes necessarily. 

So basically the things to split say 0-1V in 53 steps, or 0-10V in 20 steps, etc.

The items below have been raised as separate issues:

2. A module almost exactly the same as fixed voltage source, but as a quantiser. Preferably with 12 selectable frequencies. My idea for this is as a quantiser that can turn any bunch of notes into a 12 step note sequence. For example you could take the output of the first module above splitting 0-1V into 53 steps, then in this module enter 12 frequencies and you could have a 12 note subset of your 53 step divided octave. 

3. Maybe an additional module to number 2. above or as a stand alone thing but something similar to 2 ie. a 12 step selectable quantiser, but instead of quantising it would use whichever frequency it was quantising to select an input much like a sequential switch, maybe even with the option of 12:1 and 1:12

Thanks for considering these Antonio

**Comment by patman023** [comment]
Lots of this looks doable with the quad simpler slicer quantizer (save the voltage range stuff)

**Comment by pgatt** [comment]
Antonio liked the idea and asked me to raise an issue for it.

**Comment by patman023** [comment]
Gotcha.

**Comment by nysthi** [comment]
I'm checking this

as suggested by @patman023 the `Voltage segmenter` can be the 
quad simpler slicer quantizer

just adding a context menu saying:  
QUANTIZE RANGE:
1V
2V
3V
...
10V (default)

@pgatt what do you think ?
are you talking about "EQUAL VOLTAGE QUANTIZING", correct ?

@pgatt please open for every requested module a different ISSUE, so I can track and comment and have a linear dialog! :) grazie mille!

**Comment by nysthi** [comment]
done in v1.0.0

-- QUAD SIMPLER SLICER QUANTIZER
---- bug solved: now considering also last step; example
     if you have 10v in 2 slices, before was considering only 0.0V and 5.0V, missing the
     final step 10v
---- bug solved: the value choosen is the closest one, not the lowest one; till this version
     if you had a 10v sliced in 2 (0, 5, 10), if an incoinng value was 3.33, the slicer quantizer
    would choose 0v as resul. With this version teh 5v will be choosen (the closest to the grid)
---- feature request: is possible using the contextual menu to slice not only 10volts, but also
    1, 2, 3, 4, 5, 6, 7, 8, 9 volts
