### ISSUE TITLE
both quad and complex simplers crash on loading a wav file

### ISSUE THREAD

**Issue by josbouten** [nysthi/nysthi#172]
I'm experiencing crashes on OSX whenever I want to load a sample in the complex or the quad simpler. I'm developing a plugin and running VCV Rack 0.6.2c on OSX 10.14.4
On linux loading a wav-file works well.

**Comment by nysthi** [comment]
can you send me the wave files you are trying to open ?

**Comment by josbouten** [comment]
They are with the vocoder module I made for VCV-Rack. You can find them (fl1_std.wav and jung05.wav) here:
https://github.com/josbouten/Sculpt-O-Sound <https://github.com/josbouten/Sculpt-O-Sound>

Note that I only experience this problem on OSX, not when I run VCV Rack on linux.

Best regards,

Jos

**Comment by nysthi** [comment]
thanks!
I'll check it

**Comment by nysthi** [comment]
@josbouten 
I checked your files on all "simplers" and they load fine

currently I'm on v1 branch

![Screen Shot 2019-05-19 at 10 20 07](https://user-images.githubusercontent.com/33201978/57979571-f553de80-7a1f-11e9-80b5-0cd01607f8b9.png)

and sorry, can't repro
