### ISSUE TITLE
SevenSeas feature request

### ISSUE THREAD

**Issue by Funk-Burasuta** [nysthi/nysthi#173]
i could request a feature to implement for seven seas (which i use a lot)

which is to add a folder to store the wavetables, so that when you boot the module up, the wavetables are already loaded onto the module

kind of like what you did with scalaquantizer

it would save a lot of time setting up the module with loading all the wavetables and stuff

**Comment by nysthi** [comment]
in v1.0.0
a  default GLOBAL table is always loaded in a NEW seven seas
```-- SEVEN SEAS
---- added a default GLOBAL bank automatically loaded when a NEW Seven Seas is created
    default bank lives in `nysthi/res/sevenseas/sevenseas_default.wav`
    so everyone can change it and create a new default
---- removed the "removing clipping ends when importing arbitrary source files" mod: was buggy
```
