### ISSUE TITLE
SevenSeas bug - Save All Banks

### ISSUE THREAD

**Issue by dataphreak1001** [nysthi/nysthi#174]
On SevenSeas it doesn't look like "Save All Banks" is creating the wav files properly. The attached file was a completely full bank. It looks like it's been compressed into the first section of the file. Please find attached the two originals, as well as the exported banks.
[Wavs.zip](https://github.com/nysthi/nysthi/files/3183407/Wavs.zip)

Steps to reproduce:
1. Record a 20 second wav in masterrecorder (ReeseDeep3.wav)
2. Record a 10 second wav in masterrecorder (DeepTable4.wav)
3. Load big bank globally for ReeseDeep3.wav
4.Load big bank globally for DeepTable4.wav (Cause first one sounded half bad)
5. Save All Banks.
6. Clear all banks.
7. Load big bank globally from all_banks.wav

**Comment by patman023** [comment]
### Related rack crash while investigating

1. loaded Fixed_bank as global via context menu
2. was scanning via the lower of the two vult knobs, noticed a wave only on pages 1 and 64. 
3. while on 64, I scanned using the top knob, and rack crashed.

**Comment by patman023** [comment]
@dataphreak1001 next time you try to record a bank, i'd HIGHLY suggest either a compressor or MRec2... Vpp on the reesedeep3 bank 1 wave 16 is ~125V.

**Comment by dataphreak1001** [comment]
HAH! Yes. That's why I recorded deeptable4. To replace that bank. I liked the results, and that's when I tried to export the banks. When I reloaded them, it broke. I've tried using the record feature, but can't seem to get it to work. With deep table 4, I compressed and normalized in audacity to make sure to avoid that.

**Comment by nysthi** [comment]
in v1.0.0. the bug should be gone
I removed the inner attempt to create fake zerocrossing: people are responsible for their table import... :D
