### ISSUE TITLE
Please add sync/reset to The metaAardvark

### ISSUE THREAD

**Issue by fractalgee** [nysthi/nysthi#176]
Please add a tap sync/reset to the metAardvark. I made a patch with 3 of them going fine but after restart of Rack I cannot get the things back in sync again. A rest/tap sync like implemented in many other of your modules would be awesome!

**Comment by nysthi** [comment]
checking it!

**Comment by nysthi** [comment]
in v1.0.0

-- metaAARDVARK
---- feature request: add SYNC/RESET activable via TAP or SYNC PULSE IN.
    An OUT is provided to make sync chains

![Screen Shot 2019-05-20 at 12 43 26](https://user-images.githubusercontent.com/33201978/58016923-471f6600-7aff-11e9-8256-286421556893.png)

**Comment by fractalgee** [comment]
excellent, thanks!
