### ISSUE TITLE
LFOMultiphase sync bug?

### ISSUE THREAD

**Issue by Torinbob** [nysthi/nysthi#178]
When it is LFOMultiphase is synced to a clock, and Frequency knob is in default position, I'm getting a 0 to 5v shark fin wave, even when it is set to sine and bipolar. 

If I divide the clock by 2 I get an (almost) sine wave, but it is still 0 to 5v

I have to move the frequency knob to get a -5v to +5v wave - is that normal?

<img width="834" alt="Screenshot 2019-05-19 at 17 11 13" src="https://user-images.githubusercontent.com/41232273/57985003-8a26fe00-7a59-11e9-9c6c-07ef3fc7393f.png">
<img width="834" alt="Screenshot 2019-05-19 at 17 09 56" src="https://user-images.githubusercontent.com/41232273/57985004-8a26fe00-7a59-11e9-9ff9-2aae89033c74.png">
<img width="834" alt="Screenshot 2019-05-19 at 17 09 39" src="https://user-images.githubusercontent.com/41232273/57985005-8a26fe00-7a59-11e9-8c12-c5ac5145722b.png">

**Comment by patman023** [comment]
This is essentially a "works as intended" concern. 
```
	0.5.12.0
added SYNC, to reset teh phase of the LFO (to do multiple LFO synchronization)
```
![image](https://user-images.githubusercontent.com/36520477/57985600-6a76e200-7a27-11e9-8ccc-947e9f48796c.png)

the **SYNC** TRIG input is a reset essentially. Labelling it as SYNC is more appropriate than "reset" in this case though, as not all waves output would be starting from the 0º zero-crossing position.

To match a clock, go with the orange **TRIG** input instead, as shown above.

@nysthi @antoniotuzzi suggest close.

**Comment by Torinbob** [comment]
@patman023 - thanks for clearing that up. All good now.

**Comment by nysthi** [comment]
thank you both for helping me!
