### ISSUE TITLE
Complex simpler crash on windows 7

### ISSUE THREAD

**Issue by paradiddle16** [nysthi/nysthi#18]
If I try to load a sample or record one, complex simpler crashes vcvrack. Win7 64bit.  No prob on mac osx.

**Comment by nysthi** [comment]
is not my platform, I test only on win10
is the folder in the canonical place ?

**Comment by paradiddle16** [comment]
Hi Antonio, for some reason it's fine now but before it was constantly crashing.  It was in my documents/rack/plugins/.     Sorry for opening an issue on this.  If I get this again, I'll e-mail you on the facebook instead of opening an issue again.

**Comment by antoniotuzzi** [comment]
no no, it's god to open one!
