### ISSUE TITLE
Fixed voltage quantizer

### ISSUE THREAD

**Issue by pgatt** [nysthi/nysthi#181]
A module almost exactly the same as fixed voltage source, but as a quantiser. Preferably with 12 selectable frequencies. My idea for this is as a quantiser that can turn any bunch of notes into a 12 step note sequence. For example you could take the output of the first module above splitting 0-1V into 53 steps, then in this module enter 12 frequencies and you could have a 12 note subset of your 53 step divided octave.

**Comment by nysthi** [comment]
ok, done 
it's called "THE CAGE" in release 1.0.2
