### ISSUE TITLE
Quantised voltage switch

### ISSUE THREAD

**Issue by pgatt** [nysthi/nysthi#182]
Maybe a 12 step selectable quantiser, but instead of quantising it would use whichever frequency it was quantising to select an input much like a sequential switch, maybe even with the option of 12:1 and 1:12

Maybe a block diagram would help - I'll do the 1:12 option, the 12:1 option would be the inverse

Input 1 (this would be the CV you want to send to the selected output) ---> Output
Input 2 (this would select which output receives the voltage from Input 1, eg. if it's 0-0.83V it would go to Output 1, 0.83-1.66V it would got Output 2 etc, the specific voltages would come from the voltage segmenter we talked about in the other issue.

**Comment by nysthi** [comment]
still in my list... ;)

**Comment by nysthi** [comment]
ok, done
it's called "THE CAGE" in release 1.0.2
