### ISSUE TITLE
Request: "Touch" input on NYEcho/JiraJira

### ISSUE THREAD

**Issue by patman023** [nysthi/nysthi#183]
Is it possible to add an input to NYEcho/JiraJira, which offers the same function as "touching" the disk with the mouse? 

Trig/Gate input taken so that the disk can be "held" for any length of time.

I'd love to be able to hold multiple disks at once, but obviously that's not possible in the current environment. This way, I could patch gates from MIDI (using [touchOSC](https://hexler.net/products/touchosc) externally) and do some interesting rhythmic fuckery :-P

**Comment by nysthi** [comment]
yes, can be done

**Comment by nysthi** [comment]
but only with gate (a gate represent correctly a finger on disk)

**Comment by nysthi** [comment]
solved in v1
```-- JIRA JIRA ECHO
---- feature request: added a GATE simulating a finger on disk

-- NYECHOECOECO
---- feature request: added a GATE simulating a finger on disk

```

![Screen Shot 2019-06-09 at 15 59 14](https://user-images.githubusercontent.com/33201978/59159865-ec5ea600-8acf-11e9-9ba2-1a34f1ba3f43.png)
