### ISSUE TITLE
Simpliciter does not restore last slice automatically in certain conditions

### ISSUE THREAD

**Issue by cschol** [nysthi/nysthi#188]
Rack 1.0.0, Simpliciter v1.0.0

Simpliciter does not restore last saved slice automatically if there is only one slice saved.

Steps to reproduce:
- Add Simpliciter to patch
- Load WAV file. Slice selected/total is 0/0.
- While playing select part of WAV file with mouse.
- Save slice. Slice selected/total is 1/1.
- Shut down Rack. Start back up.
- Observe that selection extends to entire WAV file and plays entire file.
- Observe that slice selected/total is 1/1. Clicking slice selection buttons (<, >) does nothing.
- Click Reset button and slice is restored.
- Add another slice. Slice selected/total is 2/2.
- Shut down Rack. Start back up.
- Observe that second slice is automatically selected and plays.
- Select slice 1. Slice selected/total is 1/2.
- Shut down Rack. Start back up.
- Observe that selection extends to entire WAV file and plays entire file.

Expected behavior:
- Restore last saved (and selected) slice on startup even if there is only 1 slice saved.

**Comment by nysthi** [comment]
in version 1.0.2 the current screen selection will be correctly reloaded

(there is no relation between selections and slice sequencer, the slice sequencer is just saying "YOU CURRENT SELECTION IS THIS ONE" )

thanks!
