### ISSUE TITLE
Simpliciter playback restart after pause is not deterministic

### ISSUE THREAD

**Issue by cschol** [nysthi/nysthi#189]
Rack 1.0.0, Simpliciter 1.0.0

Steps to reproduce:
- Select loop range with mouse.
- Press Pause button.
- Select a different loop range that **does not include the current play cursor**.
- Resume Playback.
- Observe that playback does **not always** start at the beginning of the new selection.

Expected behavior:
- Upon resuming the playback the playback should **always** start at the beginning of the new selection.

**Comment by nysthi** [comment]
from the 1.0.2 if the user set pause, and changes the selection, pressing again PAUSE will start from the start of the new selection (and not from the percentage of the already played)
