### ISSUE TITLE
Simpliciter: append file also with drag & drop

### ISSUE THREAD

**Issue by Eurikon** [nysthi/nysthi#192]
So I asked for this:
if possible
Add:
Append wav/aiff when using drag & drop, this way we quickly can create a custom drumkit and more.

Maybe the feature should use "ctrl + drag & drop" ?

====
You replied with that it still would only trigger monophonic. 
I didn't think of that!
:D 
But anyway for non monophonic triggering it would still be welcome, to be able to append file with drag and drop.
So that I can throw in a bunch of percussion sounds, for rapid glitch triggering.

**Comment by nysthi** [comment]
ready in version 1.0.2

**Comment by Eurikon** [comment]
thank you sir!
