### ISSUE TITLE
Feature Request: Multiphase LFO -/+ 10v option?

### ISSUE THREAD

**Issue by Torinbob** [nysthi/nysthi#193]
Multiphase LFO would be ideal for modulating panning in mscHack Mixers other than the fact it outputs a 10v range: -/+ 5v in bipolar mode or 0-10v in unipolar mode. MscHack mixers require a -/+ 10v range to fully pan left and right. 

I could add 'booster' modules to increase the range of the outputs but I'd need a lot of them on a 24 ch mixer... Would it be possible to add a bipolar -/+ 10v bipolar output mode as an option, perhaps in the contextual menu please? Thanks.

**Comment by nysthi** [comment]
in version 1.0.2
-- LFO MULTIPHASE
---- feature request: added -10v to +10v BIPOLAR mode (activable via contextual menu)

**Comment by Torinbob** [comment]
That's brilliant - thank you!
