### ISSUE TITLE
Issue with SQ2

### ISSUE THREAD

**Issue by Jairodallos** [nysthi/nysthi#196]
![65392334_10218685818958055_2075340549753143296_n](https://user-images.githubusercontent.com/22566357/60340383-0bcf4d00-9971-11e9-9ed1-09692b78a39e.jpg)

**Comment by nysthi** [comment]
thanks for the report

I'll evaluate!

**Comment by nysthi** [comment]
this is a special case arised with version 1.0
was very similar to the JANNEKER one
solved in next version 1.0.2
