### ISSUE TITLE
can't open wav is all samplers

### ISSUE THREAD

**Issue by BoomBoomBob** [nysthi/nysthi#199]
When I want to open Wav files in all samplers. Nothing opens.
i am on latest build. (updated everything in rack)

macOs 10.14.5
2,7 GHz Intel Core i5
16 GB 1600 MHz DDR3

**Comment by patman023** [comment]
What steps are you taking when attempting to "open a .wav file", in which sampler(s) specifically, and which version numbers for Rack and NYSTHI (Latest =/= a number)?

**Comment by nysthi** [comment]
please update with correct info

the file you are trying to load would be a good proof

**Comment by cschol** [comment]
I am running into a similar issue when trying to load a **24bit, 48kHz WAV file** recorded with `VCV Recorder`.

The console shows the following message:

```
ERROR: this is a compressed .WAV file and this library does not support decoding them at present
```

**Comment by antoniotuzzi** [comment]
was it working with RACk 1.0.0 ?
if yes... downgrade

and please pass the file or a shorter version to me to test it

**Comment by antoniotuzzi** [comment]
just tested
saved a 24bit 48khz and loaded in a new simpliciter
all OK

**Comment by cschol** [comment]
Here is a short snippet recorded with `VCV Recorder` (24bit 48 kHz).

[Simpliciter-Test.zip](https://github.com/nysthi/nysthi/files/3342198/Simpliciter-Test.zip)

**Comment by antoniotuzzi** [comment]
my test

![Screen Shot 2019-06-29 at 20 34 55](https://user-images.githubusercontent.com/62518/60388130-68d01d80-9aad-11e9-9107-30386855f750.png)

**Comment by cschol** [comment]
The error message I see is from `AudioFile` library:

```
if (audioFormat != 1)
    {
        std::cout << "ERROR: this is a compressed .WAV file and this library does not support decoding them at present" << std::endl;
        return false;
}
```

Can you check the file I provided with your program to check its properties?

**Comment by nysthi** [comment]
yes, but what is RACK version ?

the properties in the file are corrupted

are you using the OSdialog ?
I've seen a lot of BUG reports regarding OS Dialogs in 1.1.0

**Comment by nysthi** [comment]
are you using windows ?

**Comment by cschol** [comment]
Linux. Same behavior with Rack 1.0.0.

The file opens fine in any other player in Rack, e.g. `cf`.

**Comment by nysthi** [comment]
your file contains a AudioFormat  CHUNK `FFFE`  --> -2

mine contains `01 00 `  (PCM)

the rule is 
```PCM = 1 (i.e. Linear quantization)
                               Values other than 1 indicate some 
                               form of compression.```

don't know why the `FFFE` is there,  (is not a classic endianness problem)

**Comment by cschol** [comment]
Yeah, I tested with your recorder and it works fine. Seems to be a `VCV Recorder` issue. I'll look into that.

**Comment by cschol** [comment]
Maybe an issue with `AudioFile` library:

Reference: http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html

Quote:

```
0xFFFE | WAVE_FORMAT_EXTENSIBLE | Determined by SubFormat
```

```
The WAVE_FORMAT_EXTENSIBLE format should be used whenever:

    PCM data has more than 16 bits/sample.
    The number of channels is more than 2.
    The actual number of bits/sample is not equal to the container size.
    The mapping from channels to speakers needs to be specified.
```

I have run into issues with `AudioFile` also in the past and have switched to [Dr Wav](https://github.com/mackron/dr_libs/blob/master/dr_wav.h). I know `cf` has switched to `Dr Wav` a while ago.

**Comment by nysthi** [comment]
yes, but I save with the same lib... 
or you modified the file externally ?

**Comment by cschol** [comment]
No external mod. I think `AudioFile` saves as `PCM` and then reads as `PCM`. `VCV Recorder` saves as `WAV_FORMAT_EXTENSIBLE`, which `AudioFile` does not support apparently.

**Comment by nysthi** [comment]
that is ABSOLUTELY impossible, the SNDFILE writer in my 4 recorder + all my EXPORTS from my SIMPLERs is 100% writing `PCM`

**Comment by nysthi** [comment]
and this is stable in last 20 months
I wrote the first recorder in november  2017
and I  NEVER changed that code (and reused in all recorder)

**Comment by cschol** [comment]
Read again what I wrote. This is not a problem with **your** recorder, but a problem with your **player**. Your recorder records exactly what your player expects. Andrew's `VCV Recorder` records something that your player has issues playing. My assumption is that this is because of the `AudioFile` library. Modules that use an alternative library (as well as external tools like mplayer, Audacity, etc.) do not have any problems with the file created by `VCV Recorder` (Andrew's module).

**Comment by nysthi** [comment]
AH, completely missed the INFO that was the VCV Recorder !

(because I assume that everyone records, with my recorders... :D )

ok
I'investigate how to support the VCV recorder recorded files too

:+1:

**Comment by cschol** [comment]
Awesome, man! Sorry for the confusion. I should have been more clear. :)

**Comment by nysthi** [comment]
@cschol I supported the WAVE_FORMAT_EXTENSIBLE modifying the Audiofile classes.
can you open a separate issue and I can describe the solution ?
thanks

**Comment by cschol** [comment]
Opened #203.

**Comment by nysthi** [comment]
the original bug, was a RACK 1.1.0 bug
closing
