### ISSUE TITLE
Quadsimpler

### ISSUE THREAD

**Issue by robocop77** [nysthi/nysthi#2]
Hi,
I cant set fm independently for the four sample slots... the first slot act as a master for all 4.... its normal? thx

**Comment by nysthi** [comment]
must be a BUG!

**Comment by nysthi** [comment]
I'll check!

**Comment by nysthi** [comment]
bug: 0.5.1 will contain the debugged version

**Comment by nysthi** [comment]
solve in release 0.5.1
