### ISSUE TITLE
Requesting: needle

### ISSUE THREAD

**Issue by LKHSogpit** [nysthi/nysthi#20]
Tuning with this is great but the green and red are sometimes a little out for the actual tune frequency and for setting or fine tuning the exact frequencies the digits are blocked most of the time. I think the numbers should be displayed somewhere else possibly. Perhaps the spacing just needs some tweaking though, Have the decimal point in the centre where the needle rests when in tune and a space either side of the decimal to allow for the higher digits Or maybe extend the bottom of the white space and place the Hz reading in the centre where it can be clearly read.

![hottuna](https://user-images.githubusercontent.com/12150421/34655455-14be9512-f402-11e7-9d33-c0ebeff682e8.JPG)

Notice the 7 in the B1 tune it would be really hard to see if it was a 1. Maybe use the circle and dot on the bottom of the needle as the decimal, idk. The Hz reading could do with being moved else where or tweaked...

**Comment by nysthi** [comment]
I'll check it

**Comment by nysthi** [comment]
solved for the next release

**Comment by LKHSogpit** [comment]
Cool. Great set of modules :+1:  do you have any plans for a Hz Reader for LFO's? Badly needed. Something like HOTtuna or possibly add that enhancement to include low cycles.

**Comment by antoniotuzzi** [comment]
yes, in coming release (check my posts in the FB group)

**Comment by nysthi** [comment]
solved in release 0.5.12
