### ISSUE TITLE
BUG(?): OP Oct range

### ISSUE THREAD

**Issue by patman023** [nysthi/nysthi#200]
![image](https://user-images.githubusercontent.com/36520477/60380089-88f3d400-99fc-11e9-8fa8-893f45ee7b8b.png)

Rclick menu states Oct -8 to +8, Knob only goes -6 to +6

**Comment by patman023** [comment]
Impact: can't drop to LFO/Clock levels without using the Ratio knob

**Comment by nysthi** [comment]
solved in v1.0.2
