### ISSUE TITLE
Bug in AD envelopes

### ISSUE THREAD

**Issue by MaZe6K** [nysthi/nysthi#201]
Hi there!
First of all thank you for this amazing collection, much love!

There seems to be a bug in the decay of the AD envelopes:
When the mono AD Decay is set to maximum, it is set to 0 when the project is loaded (although the knob stays in the maximum position).
The poly AD decay always stays at 0 and the knob doesn't change it at all.
(at least for me - I'm on Windows 7 with the official 1.1.0 release of Rack)

**Comment by nysthi** [comment]
great catch! (this was there since 2017 :D )
solved in version v1.0.2

the bug was also for the DAHD

**Comment by MaZe6K** [comment]
thanks! nice! :) seems nobody cranked it that hard before :D
