### ISSUE TITLE
Dual VU Meter can't be found

### ISSUE THREAD

**Issue by cmountvpr** [nysthi/nysthi#202]
Most of my 0.6.2 patches used the DualVUMeter, it's very efficient. I just upgraded to 1.1, and the DualVUMeter is in there, but can't be found by my patches.

![Screen Shot 2019-06-29 at 12 19 00 PM](https://user-images.githubusercontent.com/34426574/60387636-1a525d00-9a74-11e9-976b-475d27f4f7b2.png)

![Screen Shot 2019-06-29 at 1 45 21 PM](https://user-images.githubusercontent.com/34426574/60387655-54236380-9a74-11e9-9f09-166e2211cad7.png)

**Comment by nysthi** [comment]
yes, is still there but the SLUG is changed 

is now
`VUMeterDual`

open your VCV file and search for all `"DualMeter"`
and change it to `"VUMeterDual"`

**Comment by cmountvpr** [comment]
VCV file, you mean the patch file? Unless there's a macro so that I can do the hundreds of patches I've got, I'd rather just reload the module from the Browser.

What was your reason for changing the slug? It seems arbitrary.

**Comment by nysthi** [comment]
the script would be easy in Python, and probably already exists

As I was forced to change some of the SLUG because of Andrew changes, I decided to rename some of my modules too
