### ISSUE TITLE
Sample players don't play WAV files in WAV_EXTENSIBLE_FORMAT

### ISSUE THREAD

**Issue by cschol** [nysthi/nysthi#203]
Sample players, e.g. Simplicter, don't play WAV files in WAV_EXTENSIBLE_FORMAT. An error message is shown in the console instead.

**Comment by nysthi** [comment]
solved in version 1.0.2
modified the audiolib to load WAV_EXTENSIBLE_FORMAT when in PCM or FLOAT mode

**Comment by cschol** [comment]
Thank you!
