### ISSUE TITLE
BUG: Dynamo Knee and -117kV peaks

### ISSUE THREAD

**Issue by patman023** [nysthi/nysthi#204]
Yes, KILOVOLTS. when changing the Knee on dynamo (I'm using my mouse), I'm peaking in the Left channel output only, at anywhere from 800 to 117,000V.

Pardon the clicks and pops, but I knew it was fucky besides that. https://youtu.be/liIr-ljitmI

[Patch saved as .vcv format, but with .txt extension](https://github.com/nysthi/nysthi/files/3343374/firstone.txt)

**Comment by patman023** [comment]
Oh, the patch is played using the computer keys.

**Comment by nysthi** [comment]
I think I'm going to add a soft clipper at around 14.7V  (when I have time... )

**Comment by patman023** [comment]
Is that closer to 0dBFS (if fed direct into an audio?)

**Comment by antoniotuzzi** [comment]
is more a simulation of what could be a maximum voltage in a studio device (generally they have a -15v +15v linear PSUs)

should be a +10 db max

**Comment by patman023** [comment]
Makes sense!

**Comment by nysthi** [comment]
done in v1.0.2
added to soft limiter
one after the compressor, and one after the POST 
(so you can have 2 different distortions)
