### ISSUE TITLE
Poly DAHD Decay Longer in Voice 1

### ISSUE THREAD

**Issue by midiguru** [nysthi/nysthi#207]
In Windows 7, VCV 1.1.1, I'm finding that when I use Poly DAHD to create polyphonic envelopes, the decay time of voice 1 is significantly longer than the decay of the other voices. (I discovered this Using JW-Modules NoteSeq, which outputs a variable number of voices.) If you're unable to verify, let me know (midiguru23@sbcglobal.net) and I'll test further.

**Comment by nysthi** [comment]
I'll check, thank you

**Comment by nysthi** [comment]
can't reproduce it

here my test VCV
where I test the first 3 envelopes
(press big button to engage GATE) (press again to release it)

[testPolyADSR.vcv.zip](https://github.com/nysthi/nysthi/files/3365399/testPolyADSR.vcv.zip)

**Comment by midiguru** [comment]
Your test patch uses the Poly ADSR. That's not the module with the bug. Replace it with the Poly DAHD (and lengthen the Decay time a bit) and you'll see the bug in the Scopes.

**Comment by nysthi** [comment]
ok, correction in version 1.0.2
