### ISSUE TITLE
Module Request: Voltage based sequential switch

### ISSUE THREAD

**Issue by pgatt** [nysthi/nysthi#209]
Hi Antonio, 

I was wondering if we could have a sequential switch where the step is selected by a bunch of editable voltage ranges.

USE CASE:
Run a tuner on a signal - then output the CV into this switch and if it's in the range of F5-F6 (equiv. voltage) send it one way, if it's A1-A2 send it another way, if it's A3-A4 send it another.

Layout could be a bit like fixed voltage with min and max for each row. 5 or 8 rows would be cool, the more the merrier.

Thanks Antonio!

**Comment by nysthi** [comment]
it's similar to your previous request! ;)
I've already some idea of it
I need only freedom from lazyness !

**Comment by nysthi** [comment]
ok, done
it's called "THE CAGE" in release 1.0.2
