### ISSUE TITLE
Request: gate signal when sample ends (QUAD SIMPLER/COMPLEX SIMPLER)

### ISSUE THREAD

**Issue by VSpellbound** [nysthi/nysthi#21]
Hi! Thanks for your great modules.

Is it possible to add output providing gate/trigger signal when sample ends?
Like  LAST trigger in SQUONK.

**Comment by nysthi** [comment]
have to check if there is space

**Comment by nysthi** [comment]
done: in the next release a PULSE EOC (end of cycle) will be emitted by the Simplers

**Comment by VSpellbound** [comment]
Thank you so much!!!

**Comment by nysthi** [comment]
solved in release 0.5.12
