### ISSUE TITLE
Module Request: Voltage based trigger

### ISSUE THREAD

**Issue by pgatt** [nysthi/nysthi#210]
Similar to the voltage based switch, but a trigger/gate out instead of sequential switch

USE CASE:
If the voltage coming in is in a certain range output a gate or trigger that mutes one thing, if it's in a different range mute something else. It could be a cool like the note based selector that Omri asked for in Jooper as you could press a key on your midi controller that you don't use - maybe the lowest or highest 4 keys and use that to mute certain voices in your piece or trigger certain parts to reset or start playing etc.

**Comment by nysthi** [comment]
very easy, and in line with nysthi line!

**Comment by nysthi** [comment]
ok, done
it's called "THE CAGE" in release 1.0.2
