### ISSUE TITLE
Simpliciter needs a nudge in Varispeed area after stopping recording

### ISSUE THREAD

**Issue by tmladek** [nysthi/nysthi#211]
Hello,
not sure if I'm doing something incorrectly: I have Simpliciter set up in my patch so that the recording gets triggered periodically, but every time the recording ends, and I trigger the playback (using "start" CV input), it's as if the Varispeed/Oct got reset to 1.00 - so if I've got a buffer ready, I change the varispeed, and then I trigger and stop recording, I need to nudge either the Oct knob or the big Varispeed knob to get it to play back the way I set it up before.

What makes me think this is a bug is the fact that if I plug a very attenuated noise signal into the Varispeed CV (just enough to get the display flickering +/- 0.01), it works as I would expect.

Thanks in advance, NYSTHI modules are mindblowing!

**Comment by nysthi** [comment]
I'll check it! thank you

**Comment by nysthi** [comment]
checked

**Comment by nysthi** [comment]
the current settings were not reapplied after a recording
```---- bug: after recording, reapply the current speed to the new recorded snippets```

corrected in version 1.0.2
thank  you
