### ISSUE TITLE
Master Recorder 2 File Save Location

### ISSUE THREAD

**Issue by midiguru** [nysthi/nysthi#216]
In Windows, the Pre Choose Destination File command in Master Recorder 2 is not implemented. No matter what filename I choose, or where I choose to put it, the filename is always the default randomized name, and it always goes into My Documents > Rack.

**Comment by nysthi** [comment]
pretty buggy this OS windows stuff of yours... :D

**Comment by nysthi** [comment]
wait wait, just a reminder: the PRE CHOOSE works only in NOT in AUTOSAVE mode

if you PRE CHOOSE something, and you are in AUTOSAVE, the RECORDER will SAVE automatically in the default position "DOC/RACK" and forget the last "PRE CHOOSEN" path

SHOULD be written in the CHANGE LOG

https://github.com/patman023/nysthimanual/blob/master/changelog1.0.1_parsed.md#master-recorder-2

mods for te version 0.6.39

**Comment by nysthi** [comment]
TARJETA AMARILLA for you if I'm right... :D

**Comment by nysthi** [comment]
@midiguru please let me know if I was right ! 
BTW I retestes on a WINDOWS 10 and works
closing it
