### ISSUE TITLE
The Cage

### ISSUE THREAD

**Issue by pgatt** [nysthi/nysthi#219]
Hi Antonio, 

Awesome to see the Cage out in the wild. 

Couple of issues though - 

1. I'm sending in notes in the 0-1V range... Then running a clock into "by trig" on ¼ note pulse, and it's only playing 3 out of the 4 pulses.

2. If I change the voltage for the first row to -1.0 let's say, I assume I have to unclick "wrapped" but cannot get a voltage of -1.0V to trigger that row at all.

This may be all user error.

**Comment by antoniotuzzi** [comment]
1) you can’t use 2 select modes at the same time: you want to use only the quantize input

2) if you want a standard quantizer: always wrapped, and preferible starting from 0 volts
If you want a generic selector on any voltage: us NO wrapped and set comparators at will
