### ISSUE TITLE
Request: Simpler 

### ISSUE THREAD

**Issue by Coirt** [nysthi/nysthi#22]
Bigger wave display. Its all very squishy but I absolutely love using Quad Simpler just needs more space for each wave display I feel.

Even At 200% it is hard to see where the zero crossing is. A zoom into waveform would be great also.

**Comment by nysthi** [comment]
I'm sorry, but is not going to happen in a short time
the UI is too compact
and I don't want to lose 15 days just to correct a module (I'm doing in my spare time...)
(is the most complex of all my modules)

the day I'll work for money and full time on Rack, I'll do it 💪

**Comment by LKHSogpit** [comment]
You could easily be making money off the modules they are fantastic. I would help with that if there was a Donate!
