### ISSUE TITLE
Simpliciter: playhead rotary knob color red doesn't reset

### ISSUE THREAD

**Issue by Eurikon** [nysthi/nysthi#220]
When the rotary knob has been to the red, it doesn't return blue when we double click to return to default position.

**Comment by antoniotuzzi** [comment]
Yes I know, but I can’t control it (probably I’ll remove the color change :( )

**Comment by nysthi** [comment]
I'm going to use always the blue

**Comment by nysthi** [comment]
solved in v1.0.4
---- bug: speed knob remains red when using dual click as default:
    moved to an always blue knob
