### ISSUE TITLE
8MIX & 4MIX jack numbering changed

### ISSUE THREAD

**Issue by woodywall** [nysthi/nysthi#222]
The jack numbering seems to have changed in the latest release. Some of my existing patches have the cables for volume and pan moved to different locations. I don't have an existing patch using 16MIX so I'm unable to determine if the issue exists in 16MIX.

Here are some specifics for the modules:

8MIX
Level CV inputs are shifted right by two
Pan CV inputs are shifted right by three

4MIX
Level CV inputs are shifted right by two
Pan CV inputs are shifted right by three

Some of my level CVs were pushed down to pan CV inputs.
Some pan CVs were plugged into solo CV inputs.

**Comment by nysthi** [comment]
please can you describe a step by step operation ?

**Comment by nysthi** [comment]
and what is your system ?

**Comment by nysthi** [comment]
sorry can't repro
are you aware that all plugs in channel one are POLY?

**Comment by spectromas** [comment]
I have also experienced this. In this example the two Right channels going in to 4mix have been physically shifted right by one channel. As far as reproducing I'm not sure other than open a patch with a mixer in that was saved before the update. 

![Screenshot_20190716_085143](https://user-images.githubusercontent.com/6443372/61276038-2b56da00-a7a7-11e9-976e-4298c83487c6.png)

**Comment by nysthi** [comment]
1) still nobody told me the OS where this is happening
2) nobody told me if it's opening an old file 0.6.0
3) or from version 1.0.
4) what happen if you create a patch, save and reopen it ?

**Comment by spectromas** [comment]
Sorry. 

1. Linux for me
2. Yes, still happening. The shot below is a 0.6 patch and the stereo ins are colour coded
3. See above
4. Can't reproduce it doing this so it appears to only from patches before the last update. 

![Screenshot_20190716_090831](https://user-images.githubusercontent.com/6443372/61277199-9a353280-a7a9-11e9-9758-91f24866b1eb.png)

**Comment by nysthi** [comment]
ok I  know what happened
starting from 1.0 I've started to use a MACRO from VCV RACK

before my ports where declare like that
#define  k_mix_channels 4
   enum InputIds {
-        IN_CHANNEL_L,
-        IN_CHANNEL_L_LAST = IN_CHANNEL_L + k_mix_channels,
}

        starting from 1.0 I've started to use a MACRO from VCV RACK ENUMS and same declaration is now

     enum InputIds {
         ENUMS(IN_CHANNEL_L, k_mix_channels),
}

but ENUMS expand in  
#define ENUMS(name, count) name, name ## _LAST = name + (count) - 1

that is like to have
   enum InputIds {
-        IN_CHANNEL_L,
-        IN_CHANNEL_L_LAST = IN_CHANNEL_L + (k_mix_channels - 1),
}

so one port less for every declaration

there is no correction possible

Or we go back a people  using the 1.0.0 will suicide
or we stay to 1.0 mode and people opening patches in 0.6 will  have to do some shifting

**Comment by spectromas** [comment]
I don't think this was happening until 1.02 was released but if it can't be fixed then we just have to move on I suppose.

**Comment by nysthi** [comment]
I can release a patch 1.0.3
some people will be pissed off but a lot of patch 0.6 will be saved

**Comment by nysthi** [comment]
please use this release

**Comment by nysthi** [comment]
https://github.com/nysthi/nysthi/releases/tag/v1.0.3
