### ISSUE TITLE
BUG: Simpliciter (+ Conf. Simpler?) - S&H/Uni

### ISSUE THREAD

**Issue by patman023** [nysthi/nysthi#224]
From #215, @Jairodallas never filed it separately in english as requested...

<details>
  <summary>OG Quote via Google Translate</summary>
  
I see that the UNI button does not affect the random wave in the same way as it does with the other waves of the WAVE button; I understand that the button what it does is to alternate between frontal displacement VS oscillating displacement (frontal -reverse), something that does not happen with the random wave.

</details>

Engine Mod's S&H wave not affected by Unipolar switch

**Comment by nysthi** [comment]
@patman023 thank you for reporting it!

I'll check ASAP

**Comment by nysthi** [comment]
v1.0.4
---- bug: when modulating random was not respecting the "unipolar" "inverted" flags
