### ISSUE TITLE
Vector Mixer generaters clicks when dragging

### ISSUE THREAD

**Issue by PrinzNika** [nysthi/nysthi#226]
Vector Mixer generates clicks are to the delay of stepepd/communication between ui thread and engine thread. 
I would like to use it to add and substract different parts of a noise without changin the overall level of the signal.
I am alright with midi mapping x and y but im not sure if i have enough knobs on my devices

**Comment by nysthi** [comment]
thank you for the report, I'll check it !

**Comment by nysthi** [comment]
v1.0.4
-- VECTORMIXER
---- added smoother for mouse controls, from contextual menu is possible to set the smoothing of the action
    from 0.5 (FAST and CLICKY) to 0.999 (super super SLOW and SMOOOOOOOTH). Defaul is 0.9

**Comment by PrinzNika** [comment]
WOW, if it usually works like this I totally should file more of these kind of issues!

**Comment by nysthi** [comment]
it depends, if it is fun or not... :D
