### ISSUE TITLE
Poly AD - Poly in / Mono out

### ISSUE THREAD

**Issue by Ron-DH** [nysthi/nysthi#227]
Input of Poly to either attack or delay is fine but the envelope out is just Mono.

**Comment by nysthi** [comment]
the POLY is determined by the number of POLYTRIGGERS (not other inputs)

```-- POLY AttackDecay
---- a copy of the AttackDecay but POLY
---- added POLY mode via TRIG input and ENV OUT
---- All CV in are poly aware
```
