### ISSUE TITLE
jooper update problem when using multiple joopers

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#228]
I have the impression that, when using multiple joopers (which I do all the time), when you update one of them (update scene), it messes with the other(s), especially when they are not currently at the same scene. 
Could there be some ID confusion? Or could pressing update mean that all joopers are updated, but not all at the same scene?

**Comment by nysthi** [comment]
I don't have any global control in all of my module
what happens in one module, stays in that module
No id references are  used

BTW I retested creating 3 jooper with 4 scene each all different and with all names different

and browsing beween the scenes afffect only the used jooper
