### ISSUE TITLE
Mix4,8,16 attenuators maxed out

### ISSUE THREAD

**Issue by Petervos2018** [nysthi/nysthi#231]
When/why did you change the range for the attenuators on the mixers to go from 0-1V to 0-0.1V.
When I loaded an old 0.62c patch the settings are all maxed out.
0.5, 0.3, 0.2 all became 0.1=max value.

Greetings Peter.

**Comment by nysthi** [comment]
I changed it to remove one multiplication for every CV in
current rule is
CVIN * VCAVALUE (range 0. -> 0.1) + VALUEOFTHEFADER

old rule
CVIN * VCAVALUE (range 0. -> 1.) * 0.1 + VALUEOFTHEFADER

**Comment by nysthi** [comment]
but you are right this is a bug (I can't recover it anymore!)

**Comment by nysthi** [comment]
really sorry, please excuse me
being a one man band show I sometimes forget the old files... :(

**Comment by Petervos2018** [comment]
Hey man no problem, just nice to know that YOU know what happened and at least I know where to look when an old patch is sounding off/wrong ! :+1:
