### ISSUE TITLE
Seven Seas Pops and Clicks

### ISSUE THREAD

**Issue by midiguru** [nysthi/nysthi#233]
Using Seven Seas 1.0.3 in Windows 7, I get intermittent pops and clicks -- a click in one or both channels maybe once every two or three seconds, but sometimes more often. This happens less with the Poly version, but it happens with both modules. When there's a pop, I can _see_ the output waveform display jump. Other oscillators don't do this. Switching to the Windows DirectSound driver doesn't help. The CPU meter in Audio-8 shows 80 available CPU, so I'm pretty sure it's not a CPU or buffer problem. Any combination of Bank and Wave that I try gives similar results.

The attached file shows what it sounds like.

[seven_seas_clicks.zip](https://github.com/nysthi/nysthi/files/3503757/seven_seas_clicks.zip)

**Comment by nysthi** [comment]
did you try to disable the multithreading (using the contextual menu) ?
did you try different block sizes  (if multithreaded)?

grazie mille for your support !
<3

**Comment by midiguru** [comment]
Ah -- yes. When I turn off multithreading, the problem goes away. It sounds very stable now.

**Comment by nysthi** [comment]
curiosity: do you have an i5 cpu ?

**Comment by midiguru** [comment]
No, it's an i7-6700. Windows 64-bit. Only 8GB RAM.

**Comment by Anthony-Lockwood** [comment]
I can confirm this. Multithreading seems to work for me with 512 block size only. Works with multithreading off with all block sizes. There is some static noise though when dragging with the mouse inside the window.
Thanks.
64,win7,i5,intel hd graphics,idt hd audio.

**Comment by nysthi** [comment]
I have solved the part of the clicks whne draggin fast on the displays (or the main screen)
will be in v 1.0.

**Comment by nysthi** [comment]
-- SEVEN SEAS
---- add smoothers on value dragging (and on screen dragging) to avoid zippering noises


-- POLY SEVEN SEAS
---- add smoothers on value dragging (and on screen dragging) to avoid zippering noises

**Comment by glocke01** [comment]
https://drive.google.com/open?id=1FfBwDwYHb0EN5WY6a9UmSzlpQtv-TZ7G

This is on Ubuntu 18.04.3 LTS, 64 bit, Intel® Core™ i7-6700 CPU @ 3.40GHz × 8 . This recording was at 4 threads. Reducing to 1 thread helped but did _not_ make the problem go away.

**Comment by nysthi** [comment]
> https://drive.google.com/open?id=1FfBwDwYHb0EN5WY6a9UmSzlpQtv-TZ7G this is a wav recording of a seven seas sine wave experiencing glitches in phase.
> 
> This is on Ubuntu 18.04.3 LTS, 64 bit, Intel® Core™ i7-6700 CPU @ 3.40GHz × 8 . This recording was at 4 threads. Reducing to 1 thread helped but did _not_ make the problem go away.
> 
> They appear to occur in clusters (a few in short succession)...

can you give me a little bit of context ?
`glitches in phase` ?? 

were you doing some manual use of the UI ?

were you using the standard tables?

**Comment by glocke01** [comment]
`glitches in phase` the pitch stays the same and there are sudden, discontinuous changes in phase

`were you doing some manual use of the UI ?` no, I was doing nothing at all

`were you using the standard tables?` yes, everything bog-standard

`Please can you prepare a minimalisti patch` https://drive.google.com/open?id=1C-kqfL52X9mPZdVurkfvcEza2Bx3mqAN  just wait and you will hear blips. I got this using 1 thread. I assume other settings of the audio are captured in the audio-8 model state. This is on Rack v1.1.5
