### ISSUE TITLE
ConfusingSimpler name of the wave file

### ISSUE THREAD

**Issue by matthleg** [nysthi/nysthi#234]
Hi, I would like to see the name of the wave file appearing in the module. 
Maybe in the right click menu you can have an option between the duration of the file and the name of the file (as in the image) (it could be also in ComplexSimpler and simpliciter). Thanks to think about it and thank for your modules. 
![confusingsimpler](https://user-images.githubusercontent.com/36376831/63086627-933c4400-bf50-11e9-93ca-08a1292be5ad.jpg)

**Comment by nysthi** [comment]
that space is so small

maybe you haven't noticed that you have the file name showed in the contextual menu ?

**Comment by nysthi** [comment]
![Screen Shot 2019-08-17 at 16 36 36](https://user-images.githubusercontent.com/33201978/63213481-3c2f9e00-c10d-11e9-9c38-22fbe7c29936.png)

notice the item in the menu saying "FILE: bla bla bla .wav"

**Comment by nysthi** [comment]
anyway added a title display in the sample zone
both for simpliciter and confusing

will be in version 1.0.4 (that one day I'll distribute...)

![Screen Shot 2019-08-17 at 16 44 42](https://user-images.githubusercontent.com/33201978/63213588-69c91700-c10e-11e9-92b3-36d7006aac9a.png)
![Screen Shot 2019-08-17 at 16 44 27](https://user-images.githubusercontent.com/33201978/63213589-69c91700-c10e-11e9-9f80-1c0fa8f8a817.png)

**Comment by matthleg** [comment]
Thanks a lot it will help me a lot for using it live. I am really happy.
