### ISSUE TITLE
4hands portamento range

### ISSUE THREAD

**Issue by midiguru** [nysthi/nysthi#235]
Feature request: I'm finding that when I set the portamento value of a 4hands channel at less than 0.40, I don't hear any portamento at all. On the other hand, anything above 0.80 has to be dialed back using the Global knob. If you change the calibration, of course it will break existing patches, which is not desirable -- but it would be nice if the lower end of the range were usable.

**Comment by nysthi** [comment]
yes I noticed in the past was to extreme in both "extreme"
I'll think about it!

thank you

**Comment by nysthi** [comment]
yes
from 0 to 0.3 is super super fast and useless
and from 0.92 to 1.00 was un-effective

I've added a new portamente scaling, activable by contextual menu
and is by default on (people with old patch should update flag out the option)

+ the old scaling, I removed the dead zone after 0.92

will be available in version 1.0.4

**Comment by nysthi** [comment]
solved in 1.0.4
-- 4HANDS
---- bug in the portamento when value are bigger than 0.92, rescaled
---- added a new scale mode for portamento, giving more time between 0.00 and 0.30 values
    by default now the new scale mode is active;
    there is a contextual menu to access the old scale mode
