### ISSUE TITLE
enhancement request: quadsimpler

### ISSUE THREAD

**Issue by Eurikon** [nysthi/nysthi#236]
Hello Nysthi friend!

could you make it possible that when the sample direct output is plugged, it does not go to the stereo out? 

this way i can send the mono samples through the direct outs, 
and have the stereo samples going through the stereo output.

**Comment by nysthi** [comment]
I like it ;)

**Comment by Eurikon** [comment]
thank you! :)

**Comment by nysthi** [comment]
in version 1.0.4 (when released)

-- QUAD SIMPLER
---- feature request: add a command via contextual menu, named "Exclude Connected SAMPLES from MIX"
    to exclude single connected samples from the main mix
