### ISSUE TITLE
Sampler with Time stretching

### ISSUE THREAD

**Issue by matthleg** [nysthi/nysthi#237]
Hello Antonio,
                       I write you again...
This time I am thinking about time stretching for sample ( the process of changing the speed or duration of an audio signal without affecting its pitch). I am not technician and I don't know if it is possible but it would be a nice modulation. 
Have a nice day. 
         Matthieu

**Comment by nysthi** [comment]
sorry, can't do it in the current implementation
we need a new sampler with "granular" options
