### ISSUE TITLE
Bug: SPACE bar crashes S.A.M./Rack

### ISSUE THREAD

**Issue by jonheal** [nysthi/nysthi#239]
I small buggy: if you hold down the SPACE bar or press it very fast wen entering text into S.A.M., Rack will crash.

Rack 1.1.4
NYSTHI 1.0.3
Windows 10

**Comment by nysthi** [comment]
had to do a lot of STRESS to have the bug to appear
during a play session you need to change a lot chars and insert a lot o spaces

anyway seems is looping in in a obscure code coming from the original SAM lib
maybe was too abused for the use

Sorry but I can't repair it

**Comment by nysthi** [comment]
I'll put a note in the changelog release for the 1.0.4 (if I ever release it... ) ;)

-- SAM
---- ADVICE: Jon (https://github.com/nysthi/nysthi/issues/239) adviced me and you
    that if the SAM module is very stressed can crash (or enter in the infinite spinning ball mode)
    beware of this anomality that I can't correct because seems related to some obscure part of
    the original ported code !
