### ISSUE TITLE
Cage in v1.0.4 does not play the same note twice.

### ISSUE THREAD

**Issue by mocmichal** [nysthi/nysthi#240]
Thank you for the polyphony in new version! 
But after updating to v1.0.4 my patch stopped working. In picture you can see part of my patch (using v1.0.3):
![debug_nysthi_Cage_v103 vcv](https://user-images.githubusercontent.com/5244956/65028276-1ed43680-d93c-11e9-81e1-d385834013ca.jpg)
When I press the same key twice (C4 here is only example- works the same for all notes) Cage does not interpret it as the same note, instead it "overflows" and uses the last note (numerical value) as seen in the second picture:
![debug_nysthi_Cage_v104 vcv](https://user-images.githubusercontent.com/5244956/65028318-2dbae900-d93c-11e9-9b7d-97cbe31ea8ea.jpg)
Maybe I just don't use Cage correctly.
(And of course Musicalbox would now be more useful for this)

[debug_nysthi_Cage_v3_v4_03.zip](https://github.com/nysthi/nysthi/files/3620347/debug_nysthi_Cage_v3_v4_03.zip)

**Comment by nysthi** [comment]
thanks for the report
I'll check

**Comment by nysthi** [comment]
I don't understand connections
if you use the quantizer you should use the Quantizer output

if you use the RESET you are giving priority to the sequencer mode, and the current step jumps always to the step BEFORE the first step of sequencer mode
