### ISSUE TITLE
Musicalbox cleared samples after save and restart

### ISSUE THREAD

**Issue by espenstoro** [nysthi/nysthi#241]
Hi.
I was using Musicalbox as a drum sampler, loaded a bunch of sounds, everything plays nicely. Saved patch and closed, came back, everything is fine. Saved new version, closed, then all samples were cleared after opening again.
Don't know how consistent that is, but that's something worth looking into. 

Rack 1.1.4, plugin version 1.0.4, Windows 8.1.

**Comment by nysthi** [comment]
I need a precise sequence

are you saying
you have a file AAA with a MB2 with samples
you SAVED AS "BBB" and you closed everything
you OPENED BBB an MB2 was cleared ?

if this is the scenario, I can't repro

remember samples are files that must be ALWAYS in the same place

**Comment by espenstoro** [comment]
I can repro this way:

Load sample(s), close and open Rack twice, and they're gone every time. File paths are the same, no other action taken at all.

**Comment by nysthi** [comment]
tested the sequence many times
using the official app with release 1.0.4 nysthi loaded from the plugin manager
and can't repro on mac os high sierra
going to check win10

**Comment by nysthi** [comment]
tested both, via file open dialog, and drag and drop

**Comment by nysthi** [comment]
what happens when you open a MB2 that was full 
and after you open again  and seems empty
what does say the contextual menu on the waves ? is listing the available samples?
and what happens if you click the NEXT PREV samples buttons ?

**Comment by nysthi** [comment]
sorry can't repro on win10 to
here the sequence of launches
UP:
![Screen Shot 2019-09-17 at 18 49 50](https://user-images.githubusercontent.com/33201978/65062386-329f8d00-d97c-11e9-8130-3cd6127a8085.png)

DOWN:
![Screen Shot 2019-09-17 at 18 50 05](https://user-images.githubusercontent.com/33201978/65062409-3df2b880-d97c-11e9-9c7a-15f6bb2c96ec.png)

UP AGAIN:
![Screen Shot 2019-09-17 at 18 50 50](https://user-images.githubusercontent.com/33201978/65062416-44813000-d97c-11e9-9a0b-71bfb722b06a.png)

**Comment by espenstoro** [comment]
Tested MB2 now, seems to be other issues there. Samples loading in different slots, or not at all, with drag and drop. Will have to check that later. Not the same as MB1.

Context menu says no samples, as if I loaded a blank MB1. It happens consistently every time.

**Comment by nysthi** [comment]
remember 
MB1 can load samples from different DIRECTORIES (drag and drop or context menu on the different channels)

MB2 can load samples from ONLY one directory, and only files less that 2MB

**Comment by espenstoro** [comment]
Watch this. Drag+drop, closing rack. Same happens without exception.
https://youtu.be/7oSyEuQKaKM

**Comment by nysthi** [comment]
AH! the MB1
ok rechecking

**Comment by nysthi** [comment]
reproduced

**Comment by nysthi** [comment]
found... 💪

**Comment by nysthi** [comment]
in v 1.0.5
-- MUSICALBOX
---- bug the module was losing reference to files after second opening

**Comment by espenstoro** [comment]
Yay! That was quick!

**Comment by nysthi** [comment]
you should see the 1.0.5 ASAP
