### ISSUE TITLE
Feature Request. Vector Mixer

### ISSUE THREAD

**Issue by Telerex** [nysthi/nysthi#242]
Any way of having cables connected to the X&Y inputs of the vector mixer and still have the keyframe animator work? I know you said it was probably is not possible because the X&Y inputs have priority, but something as simple (or not) as a switch would do (same switch as the run button would be better).

**Comment by nysthi** [comment]
how about
if the animator is running, the X &  Y will be the sum of the XY input + the keyframe animation ?

**Comment by Telerex** [comment]
Either or would be good. At least then we don't lose the power of the keyframer (and your hard work) just for having cables plugged in. Thanks.

**Comment by nysthi** [comment]
ok, I'll go for the sum
the other option is to give priority to the animator
I think I'm going to add a contextual menu
a) plugged in priority
b) sub
c) KF animator priority

**Comment by Telerex** [comment]
Wonderful.

**Comment by nysthi** [comment]
will be in version 1.0.6

-- VECTORMIXER
---- changed range to smoother from 0.5-0.999 to 0.25-0.999, default to 0.5
---- feature request: added contextual menu for behaviour of XY positions inputs when animator is running
    modes are,
        a) X-Y positions inputs if connected have always priority
        b) X-Y positions inputs if connected are summed to the animator if running
        c) Animator if running have priority on X-Y positions inputs
---- add polyphony to channel A B C D LEFT and RIGHT
    the polyphony in output is computerd using the channel in input with max polyphony
    the polyphony in output is assigned to
    OUT signal A
    OUT signal B
    OUT signal C
    OUT signal D
    OUT signal X
    OUT signal Y
    OUT MIXED SIGNAL LEFT
    OUT MIXED SIGNAL RIGHT

**Comment by nysthi** [comment]
more changes and debugging coming with 1.0.6 VECTORMIXER

---- debug the KEYFRAMER now interpolates correctly between the last and first step, if in LOOP
    If not in loop the joysticks stops at the last KEYFRAME
    the full time of the animation is intended for a LOOPED KEYFRAME animation

---- reminder on the AUTORECORDER
    if you set AUTOREC KFs ON KEyframes will be automatically added during dragging, respecting
the NEXT KF time field: for example if you set to 0.10 means a keyframe every 100 msecs will be saved

---- I removed the auotmatic editing of current keyframe: was too confusing
