### ISSUE TITLE
Feature request / Idea : Record for SUSSUDIO for amazing modular delay effect

### ISSUE THREAD

**Issue by MaZe6K** [nysthi/nysthi#243]
Hey Synthi,
I had this idea for a delay effect floating around in my head for some weeks, and now that you came up with SUSSUDIO it's almost exactly what I imagined, it's just not a delay effect yet.
If SUSSUDIO could get an audio and a sync input, record the audio to a buffer and drop it into the sampler every time it receives a sync input, this would be the most amazing delay effect ever.
What do you think? Would be pretty freaking amazing, right? :)

**Comment by nysthi** [comment]
nice idea, but
1) SUSSUDIO has been already a bloodbath
2) I removed all the code related to recording, and I feel very tired to put it back

I'm working on something similar
