### ISSUE TITLE
Mix4 Mix8 Mix16 slider/fader noise

### ISSUE THREAD

**Issue by Anthony-Lockwood** [nysthi/nysthi#244]
I have noticed noise when moving the sliders/faders on all Mix4,8,16 mixer modules. After testing I have discovered that when the view is zoomed in fully 100% the noise is less. when the view is zoomed out fully 25% the noise is more. It seems to me that the digital text display in the modules may be a possible cause.
Enclosed sound sample 'slider test' with vco-1.
Thanks.
64,win7,i5,intel hd graphics,idt hd audio.
[slider test.zip](https://github.com/nysthi/nysthi/files/3660629/slider.test.zip)

**Comment by nysthi** [comment]
correct (buggy)
but I generally don't use it for real time
but wait for the correction

**Comment by nysthi** [comment]
solved in 1.0.6
-- 4MIX 8MIX 16MIX
---- debug mode: changed all smoothers now you can drag at any speed the faders and the PANs you won't hear anymore clicks! :)
