### ISSUE TITLE
add "fm" tag to u-operator

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#246]
so it shows up when typing fm!

**Comment by joopvdl** [comment]
Well, maybe there isn't, but I use it as a search function anyway.

**Comment by nysthi** [comment]
done
there is no FM tag
but the bogaudio uses the name

I've added some "FM" in the names of OP EN and M1  (all 3 used to do dx7 patches...)

in v 1.0.6

**Comment by joopvdl** [comment]
Yes, i think there is much to win with clever tagging. Let's start a
campaign!
