### ISSUE TITLE
squonk random: exclude mode

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#247]
I believe we might have discussed this before.
I like to randomize the a,b,c,d,e lines of squonk. For that, I can choose which line will be randomized, by context menu. I can also choose to exclude repetitions from randomizing. But I cannot exclude mode. So, after randomizing, I have to re-set mode to the way it was before. 
Can you add "mode" to the contextual menu?

**Comment by nysthi** [comment]
to be checked!

**Comment by joopvdl** [comment]
Could you also make a function where you can copy one column's cv values, eg. A, and paste them to another (B, for example)?

**Comment by nysthi** [comment]
please make a new request! ;)

**Comment by joopvdl** [comment]
After thinking a bit about this, I think I will withdraw the request. I was thinking about polyphonic stuff, but you would need separate clock inputs for that. Better to use multiple squonks, I guess.

**Comment by nysthi** [comment]
solved in 1.0.6
-- SQUONK
---- add more filter on RANDOMIZE, via contextual menu
---- It's possible now to randomize OR not:
------ DIRECTION
------ x10 Multiplier
------ MODE

![Screen Shot 2019-10-15 at 11 45 21](https://user-images.githubusercontent.com/33201978/66820769-95675280-ef41-11e9-894e-d9d61175dfa7.png)
