### ISSUE TITLE
Y Output Vector Mixer is Flipped

### ISSUE THREAD

**Issue by Petervos2018** [nysthi/nysthi#249]
It goes negative when it should be positive and vice verse.

**Comment by nysthi** [comment]
solved in 1.0.7

-- VECTORMIXER
---- bug: inverted Y output
---- add falg to use -5v to +5v ranges

**Comment by nysthi** [comment]
---- changed play mode to have more "ENVELOPE" functionality:
        a new TRIG/PLAY/RUN will restart the animator
