### ISSUE TITLE
xatto crash on Win7

### ISSUE THREAD

**Issue by martin-lueders** [nysthi/nysthi#25]
Xatto is reproducably crashing Rack for me when connecting the MsHack Masterclock output to the clock input.

**Comment by nysthi** [comment]
did you test only with that masterclock ? IS crashing  with other devices too ?
thanks @martin-lueders !

**Comment by patman023** [comment]
Not reproducible with any output on mscHack Master Clock x4.

Also, if was the Chain Output, mscHack uses non-standard method of chaining their clocks, with Voltage=BPM (so crash could have been related to handling of out-of range signals)

Suggest Closing.

**Comment by nysthi** [comment]
no repro
