### ISSUE TITLE
Simpliciter - buggy behaviour in grid slice mode

### ISSUE THREAD

**Issue by MaZe6K** [nysthi/nysthi#251]
Simpliciters Grid Slicing is a dream, but the slice selection sometimes causes slices to multiply their range, so sometimes they are 2, 3, 4... slices in length.
I recently recorded a video that captures it https://youtu.be/BONy3G301Rg?t=49

PS: in the video the slices are never played fully, but you can see how they change their length on the display and if I would let them play to the end they would play the currently displayed length of the selected slice.

**Comment by MaZe6K** [comment]
PS: in the video the slices are never played fully, but you can see how they change their length on the display and if I would let them play to the end they would play the currently displayed length of the selected slice.

**Comment by nysthi** [comment]
in version 1.0.7
---- bug in slice selection when using CV, sometimes was a multiple of a slice. Corrected
