### ISSUE TITLE
janneker timed - gate out

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#252]
I thought it might be interesting to have Janneker timed output gates as well as triggers. The gate length would be the length of the scene. So scene starts, gate up, scene ends, gate down (and end of scene pulse).

**Comment by joopvdl** [comment]
Yes, that's the idea. Or else it would be one long gate, that seems quite
useless to me.

**Comment by nysthi** [comment]
ok added GATE
it's UP during a SCENE
and the JANNEKER must be ACTIVE and NOT RECORDING
the GATE goes done whne the TRIGGER E-O-SCENE is UP (un msec)

in version 1.0.7

![Screen Shot 2019-10-31 at 20 21 05](https://user-images.githubusercontent.com/33201978/67979274-392c5000-fc1c-11e9-95b5-e49a5cff437f.png)
![Screen Shot 2019-10-31 at 20 20 56](https://user-images.githubusercontent.com/33201978/67979276-392c5000-fc1c-11e9-8e84-9328cd5ab7d6.png)

**Comment by joopvdl** [comment]
Cool!

**Comment by joopvdl** [comment]
Now I've been thinking some more, and what about the idea to turn the gate
on or off per step? Is that possible?

Btw I will complete the manual for Janneker with possible usage options.

**Comment by nysthi** [comment]
you want to program the gate, scene by scene ?

it's much more complicated, can be done but with a particular attention to already saved patches

anyway it's another request...
