### ISSUE TITLE
MusicalBox sample names unreadable

### ISSUE THREAD

**Issue by unlessgames** [nysthi/nysthi#254]
Loving the new sampler modules, but could you make the text on the waveforms more readable somehow (talking about MusicalBox 1)?
They are very hard to read especially the middle ones, not good when you are doing something live. Maybe going with less transparent text, text on the top layer or inverted blending mode would work.
![illustration](https://i.imgur.com/cG3JeaT.png)
There is also some bug with the red speed knobs not displaying correctly sometimes, but I couldn't track down yet when this is happening exactly (maybe something with the global speed knob altering the individual ones?).

**Comment by nysthi** [comment]
the renderer won't let me to scale the test respecting the current zoom

I have not idea how I can improve the visual, the screen is full

anyway, IIRC the names are visible using the contextual menu

going to check with different colors...

yes the speed a are ADDED, 
all speeds are added to current  global speed

**Comment by unlessgames** [comment]
I haven't noticed that the font size is absolute (I don't zoom about that much), do you draw with opengl BitmapString? Cause with nanovg nvgText command you can draw text that stays the same size no matter the zoom inside Rack.

Anyways, the scaling is less of a problem imo, it is more the color, or even just the order of drawing. Now it is like waveform->text->selection, but maybe if the text was the last thing it would be enough of a fix, cause the semi-transparent selection rectangle works as a filter for colors, for example the pink is only letting red&blue content through and the green text has none of that.

**Comment by unlessgames** [comment]
But if you are using gl commands you could solve this color filtering problem with some different glBlendFunc maybe.

**Comment by nysthi** [comment]
I'm using nanovg command
and the implementation in Rack misses a lot of INKs (blend functions)

suggest me a color scheme!

**Comment by unlessgames** [comment]
Ah don't put me to that spot :D 
Personally I like the new primary colors look you are going for since Simpliciter (it also goes well with the default cable styles in Rack), but this neon palette has been here since your mixers and it has a cheesy 90s feel to it that is kinda funny too imo. But there are definitely too many different hues on this right now. You should commit to one of those palettes. Either have like 4 less saturated (but same hue) versions of the colors of the knobs/buttons, and have those from sample 1-4 and repeat on 5-8. 
Or spread out the gradient that you have on 1-5 right now to go through all the rows (the hue switch from the 6th row onwards feels wrong to me) so the whole would go from yellow to pink and you could have a neon sunset kinda vibe but then the knobs and buttons would need to match that somehow, and I guess its easier to change the colors of the samples, especially since you seem committed to the colored ports by function idea on your other modules as well.

But these are all polishing stuff that's less important than the readability of the texts. Also just a matter of personal taste.
If you could draw the text above the crop selections, another cheap trick you could do to emulate a more exotic blending mode is to use a color from the same gradient palette but offset by a few steps. Like
background_color = palette[i], text_color = palette[(i + 3) % 8]

Or what about just keeping the samples display grayscale? It would solve a lot of these problems. You could still have the text stay green or have the color palette only on the texts if you must, and the selection area just be a brighter shade than the background. No more color filtering issue, text would pop out, there wouldn't be an issue of matching colors with the knobs, or too many colors in general. Worth a try maybe!

Back to the scaling, without seeing how you draw the text I can't say much about the fixed font size but for example the DUR / SR text on Simplicter doesnt have this behaviour.

**Comment by unlessgames** [comment]
sorry for rambling, just read the last 2 paragraphs x)

**Comment by nysthi** [comment]
I'll do a test using the gray scale, actionable using a contextual menu 💪

**Comment by nysthi** [comment]
done

check it (activable via context menu a new mode)

NORMAL mode
![Screen Shot 2019-11-10 at 17 19 37](https://user-images.githubusercontent.com/33201978/68547163-8cea2680-03de-11ea-8ec7-f54b9dd98e33.png)

NAMEs VISIBLE MODE
![Screen Shot 2019-11-10 at 17 19 29](https://user-images.githubusercontent.com/33201978/68547170-a25f5080-03de-11ea-9ce9-4734af3259f1.png)


the contextual menu to activate:
![Screen Shot 2019-11-10 at 17 19 44](https://user-images.githubusercontent.com/33201978/68547175-b2773000-03de-11ea-89c9-a61c167cf424.png)

**Comment by unlessgames** [comment]
checking it right now, it has become insanely readable!
thank you very much!
