### ISSUE TITLE
Convolvzilla glitches - mirack

### ISSUE THREAD

**Issue by palmort** [nysthi/nysthi#257]
I realize that convolution is processor heavy, but I'm running into an issue, no matter the audio buffer or block settings in mirack. Mirack reports that it's using 1% cpu. Even with a very short ir, it's misbehaving. 

I'm on an older 9.7" ipad "pro". Oddly, this is the only module causing this problem for me. 

https://www.youtube.com/watch?v=MPdfD2SdbLQ&feature=emb_logo

thanks! love your modules!

**Comment by nysthi** [comment]
that's very strange, I use an ipad air 2 that is at least 1/3 of the 12.9 pro power, and using 1024 samples per block I have no crackling

I would need the full source code to debug this + an ipad pro!
