### ISSUE TITLE
LFOMultiphase - Phase

### ISSUE THREAD

**Issue by Coirt** [nysthi/nysthi#26]
Trying to work out which has the incorrect phase. Coding an LFO module based on the Fundamental LFO. When I fired my module up first the phase was off compared to the fundamental's phase thought it was because of my switch being the opposite way around fixed that by swapping the switch file names. Just compared the fundamental LFO phase to LFOmulti's 0° phase and they are both off also. To match the fundamentals phase have to output Multi's from 270°. Flipping the phase on Fundamental to 180° have to output at 90° on multi.

Is the 0° on multi off or is it the fundamental's that is off?

**Comment by nysthi** [comment]
sin(0) is the start of the multi

**Comment by Coirt** [comment]
Just double checked this. What's happening is bi polar is in snyc uni is not.
![lfo dev 2](https://user-images.githubusercontent.com/12150421/36320255-7744a244-133d-11e8-96f9-4742b674bb51.gif)

**Comment by nysthi** [comment]
you can't trust your eyes using that scope... ;) (use an external triggers...)
if you set BIPOLAR the trigger point for the visualization changes
to have the same, you should move the trigger point too !

**Comment by Coirt** [comment]
The 0 crossing should be the same no matter what offset. How do yo mean can't trust my eyes using the scope? Do you see something different. What I see is the 0 crossing on unipolar being off by 270° it uses the phase/0 crossing of the bipolar signal. The 0 crossing on the fundamental uni/bi is slightly off also by a couple of degrees.

![lfo nysthi 0 crossing](https://user-images.githubusercontent.com/12150421/36323068-924af386-1347-11e8-95d1-7b5c7c0630c5.gif)

**Comment by nysthi** [comment]
in the previous example, the master for the trigger was the multi lfo in CHAN ONE
when you changed the from unipolar to bipolar, the TRIG triggered 90 deg before

**Comment by Coirt** [comment]
Right so which is incorrect? LFOmulti or Fundamental LFO.

Whatever the polarity is the 0 crossing should match they don't match on LFOmulti. The 0 crossing is off slightly on the fundamental also but probably within a margin for error.

**Comment by nysthi** [comment]
the trigs triggering 90deg before doesn't means the bipolar is out of phase, if you move the trig to around -5, you'll see it aligned again.

to do this kind of measurements, you have to use an EXTERNAL trig
