### ISSUE TITLE
Jira Echo Echo clicks a lot, if fed random gates

### ISSUE THREAD

**Issue by fractalgee** [nysthi/nysthi#262]
The clickiness gets even worse if the erasing head is enabled.

My use case:

Rack 1.6.2
MacOS 10.11.6
Latest plugin manager installed Nysthi collection

I use the Klirrfactory's The Clock as my random clocked gate module, as it can be set to provide none, 16/32/48 different random gates with random length. I use that for a fancy bernoulli gate replacement. It is part of Klirrfactory's Mixer Free collection, so not a paid module. 

I use 3 of the gates to randomly trigger the on and off of the 1/3/5 recording heads. I had the erase head also enabled at random, but that makes the clickiness even worse. The signal I feed is is the output of two mono FM-OPs and in and out are at default levels, Tried to play with the swell, bias etc controls, nothing I tried would de-click this lovely module, so hope you can find a way as it sounds excellente!!!! and I would love to use it instead of the Chronoblob as a send effect on the mix if that can be solved as this is so much more what I like in a delay unit....

Thanks for all the great modules!

**Comment by nysthi** [comment]
nice touch the " I would love to use it instead of the Chronoblob as a send effect but..."
so moving... and passionate... :D :D

**Comment by nysthi** [comment]
solved in 1.0.9
