### ISSUE TITLE
Musicalbox2 Can't upload any wav file

### ISSUE THREAD

**Issue by OrionDemon** [nysthi/nysthi#268]
Trying to upload a wav file to musicalbox 2 does not add any sample. Tried the same file on musicalbox and it works.

**Comment by nysthi** [comment]
musicalbox 2  doesn't accept files bigger than 2MB

anyway in version 1.0.10 I've added a flag to override the constriction
if you use MAC you can test it the beta release
https://github.com/nysthi/nysthi/releases/tag/v1.0.10beta
