### ISSUE TITLE
Etchasketchascope RGB input

### ISSUE THREAD

**Issue by a1laserboy** [nysthi/nysthi#269]
Hi,
I was wondering if you could add in R,G,B inputs so we can modulate them also. In my eyes it's the most beautiful scope out there

Cheers

**Comment by nysthi** [comment]
sincerely
I had already the R G B input but I removed because was so awfully slow!
but I'll do another check

**Comment by a1laserboy** [comment]
Thank you so much, I'm using it to try to emulate laser output to use for visual effects :)

**Comment by nysthi** [comment]
added in vers 1.0.10

-- ETCHASKETCHOSCOPE
---- add the R G B inputs, they accept from 0 to 10 volts and they are active only if all 3 are plugged
(they are at the bottom left)
