### ISSUE TITLE
One of the oscillators causes the plugin browser to hang/crash

### ISSUE THREAD

**Issue by ShaneCullinane** [nysthi/nysthi#271]
I seem to be experiencing the issue discussed in [this thread](https://community.vcvrack.com/t/rack-hangs-whenever-filtering-modules/8248/10) on the rack community forum. I went through all the developer names in the filter list and this was the only one that caused the issue, so I guess it is one of your oscillator plugins. 

Steps to reproduce:

- Open plugin browser
- Click on the Oscillator filter OR click on the NYSTHI filter OR type 'o' in the filter box

Expected Result:

- Oscillators and/or NYSTHI plugins are displayed

Actual Result:

- Browser and Rack hang for ages, maybe two minutes with 'Not Responding' message in the Rack title bar.

Windows 10

Thanks for the cool plugins :-)

**Comment by nysthi** [comment]
Hi

thank you for the heads-up
I cannot reproduce the crash on my mac
and I don't have a window

could be something related to video drivers ?
don't know!

I'll leave the bug open we wait for more info

**Comment by ShaneCullinane** [comment]
Fair enough!

**Comment by nysthi** [comment]
yesterday I had time to test it on a Win10 system (on an HP book)
and I was unable to reproduce it
with last RACK 1.1.16
and last nysthi 1.0.10

**Comment by kurokawa-ja** [comment]
Hello.
Sorry for the machine translation because I am Japanese.
I have the same problem.
I use Windows 10 and Rack 1.1.16.
It may be caused by "NYSTHI SussStudio", "NYSTHI MusicalBox", or "NYSTHI MusicalBox 2".
・Selecting "NYSTHI" in Brands crashes.
・Choosing "Oscillator" "Sampler" "Quad" in Tags will crash.
・Crash started when updating from NYSTHI 1.0.3 to 1.0.4. (1.0.11 also crashes.)
I hope I can help you. Thank you.

**Comment by Bonmon2** [comment]
I have the same problem. I believe it is caused by the 2 music box modules and their rendering

>

**Comment by nysthi** [comment]
using the plugin.json file you can remove selectively the different modules
can you do some test removing one by one the samplers?

I use an i5 HP notebook win10 and I can't repro the bug !

I need some more precise report

did you check the CRASH LOG ?

**Comment by Bonmon2** [comment]
Sorry didn't check the crash log. I'll try what you said though to narrow it down

**Comment by ShaneCullinane** [comment]
I've attached an excerpt from my log, not sure if it is helpful or not... I clicked the nysthi filter in vcv and it started getting stuck. I had the log open and I noticed that the last line was this one (line 45 in the attached):

`[1885.786 info src/window.cpp:33] Loaded font C:\Users\TOMGRI~1\DOCUME~1/Rack/plugins-v1/NYSTHI/res/fonts/DejaVuSansMono.ttf`

then it got stuck once or twice more. Not sure if the numbers on the left are timestamps or not but if they are then you can see around there that one or two things around that point are taking a while. 

To add to the confusion, everything worked fine for me for a while since I opened the issue, it started happening again this evening after updating something. 

[nysthi.log](https://github.com/nysthi/nysthi/files/4396403/nysthi.log)

**Comment by leeketch** [comment]
I am also experiencing this issue, exactly the same as described by @ShaneCullinane  

I am on Win 10 on a Lenovo X1 Carbon Gen 1. I open Rack, right click to open the plugin browser and it does not open. Rack hangs and eventually displays "Not Responding" in the window title bar. If I manually remove the NYSTHI folder from my plugins folder, the behavior stops and Rack works as expected. Logs are attached. Interestingly, the final line of my log is the same as Shane's.

`[17.906 info src/window.cpp:33] Loaded font C:\Users\HP1\DOCUME~1/Rack/plugins-v1/NYSTHI/res/fonts/DejaVuSansMono.ttf`


[log.txt](https://github.com/nysthi/nysthi/files/4465728/log.txt)

**Comment by nysthi** [comment]
anyone tried to do my suggested procedure (removing one by one the musical box...) ?

@leeketch please put the attached file in the nysthi RES directory and substitute the `MusicalBox.svg`

here the attachment
[MusicalBox.svg.zip](https://github.com/nysthi/nysthi/files/4466180/MusicalBox.svg.zip)

**Comment by leeketch** [comment]
I tried the following steps in this order.

1) In RES directory, moved MusicalBox.svg, MusicalBox2.svg and MusicalBox3.svg out of directory on to desktop. Unzipped the MusicalBox.svg.zip attachment and moved the new MusicalBox.svg into RES directory.
2) I opened plugin.json and removed code referencing module MusicalBox2, leaving only MusicalBox.svg in the RES directory and in the plugin.json file. Crash still occurs (log attached).
[log.txt](https://github.com/nysthi/nysthi/files/4466698/log.txt)

Then I moved MusicalBox.svg, MusicalBox2.svg and MusicalBox3.svg out of the RES directory and I removed references to the all MusicalBox modules in the plugin.json file. Everything starts working again and the plugin browser opens normally, lets me select a module, etc.

**Comment by nysthi** [comment]
there must be something related to the svg file, thanks for the test

**Comment by tomfug** [comment]
I'm having the same issue here... Lenovo Thinkpad T430S, Windows 10 (build 1909).

I removed MusicBox.svg, MusicBox2.svg and MusicBox3.svg out of the RES folder and also deleted the references to MusicBox and MusicBox2 in the plugins.json (couldn't find MusicBox3 in there). However, it still hangs for a long time. Here's the part where it hangs in the logs:

[13.728 info src/window.cpp:33] Loaded font C:\Users\T430S\DOCUME~1/Rack/plugins-v1/NYSTHI/res/fonts/DejaVuSansMono.ttf
[78.193 info src/window.cpp:72] Loaded SVG C:\Users\T430S\DOCUME~1/Rack/plugins-v1/NYSTHI/res/MusicalBox.svg

**Comment by nysthi** [comment]
very sad, don't know how to repro it!
I think should be a problem of openGL driver

**Comment by tomfug** [comment]
Ah, thanks for mentioning openGL.  Got me thinking about my display driver. My Lenovo has an onboard Intel HD Graphics 4000. Found the latest drivers (from Intel - NOT from Lenovo). Once installed everything is running smoothly!

**Comment by antoniotuzzi** [comment]
FANTASTIC !

**Comment by leeketch** [comment]
Same here.

1) Installed drivers from here: https://downloadcenter.intel.com/product/81499/Intel-HD-Graphics-4000 

2) Rebooted

3) Restored the NYSTHI plugin-v1 folder to it's original state with the MusicalBox modules. Everything works perfectly.

Thanks @tomfug !

**Comment by nysthi** [comment]
was one of my first suggestions (second post: "could be something related to video drivers ?" ) 
:)

**Comment by tomfug** [comment]
Yeah, I saw that and thought "well i've got the latest drivers from Lenovo". Didn't occur to me to go straight to the source (intel) until later.

**Comment by nysthi** [comment]
this will be closed

it's an obvious graphic card bug
