### ISSUE TITLE
Two suggestions about Scale and Offset

### ISSUE THREAD

**Issue by nesdnuma** [nysthi/nysthi#273]
Hello,

Scale and Offset is a nice module!

Two suggestions to improve it :
1. Allow an offset from -10 to +10 instead of -9.9 to 9.9.
2. While it's nice for the potentiometers to move by a .1 value, it would be nice for the GUI to reflect when a value with more precision is encoded (ex : 1.25 is displayed as 1.2).

Thank you.

**Comment by nysthi** [comment]
ok 1 is in
ok, I'm going to add 2 decimals

**Comment by nysthi** [comment]
ok will be in in version 1.0.12

don't forget the context menu to switch from free mode to 0.1 steps mode !

**Comment by nesdnuma** [comment]
Thanks a lot! It's always appreciated when suggestions are integrated.
