### ISSUE TITLE
TUNATHOR - range input -  feature request

### ISSUE THREAD

**Issue by ale47p** [nysthi/nysthi#275]
Hi there, I think TUNATHOR always looks for the range between C1 and C7, so, if the oscillator can’t reach 30-4200Hz it stops working.

If the user could set the “range” every problem would disappear.

Cheers
Alessandro

**Comment by nysthi** [comment]
thanks! I'll check it ASAP

**Comment by nysthi** [comment]
added ranges via contextual menu

solved in version 1..0.12

![Screen Shot 2020-05-30 at 18 01 17](https://user-images.githubusercontent.com/33201978/83333198-ab8f0c80-a29f-11ea-9e43-4b067fa50c2e.png)

**Comment by ale47p** [comment]
grazie! siccome non ho mai avuto a che fare con github, come si fa di solito? si ringrazia lì, si chiude...eccetera?
inoltre vedo che non è ancora disponibile nella libreria ufficiale di vcvrack

grazie ancora 😉

un saluto
A


________________________________
Da: nysthi <notifications@github.com>
Inviato: sabato 30 maggio 2020 18:02
A: nysthi/nysthi <nysthi@noreply.github.com>
Cc: ale47p <ale47p@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [nysthi/nysthi] TUNATHOR - range input - feature request (#275)


added ranges via contextual menu

solved in version 1..0.12

[Screen Shot 2020-05-30 at 18 01 17]<https://user-images.githubusercontent.com/33201978/83333198-ab8f0c80-a29f-11ea-9e43-4b067fa50c2e.png>

**Comment by nysthi** [comment]
faccio io la chiusura, poi quando distribuisco
grazie mille!

**Comment by ale47p** [comment]
grazie a te 😉
A


________________________________
Da: nysthi <notifications@github.com>
Inviato: lunedì 1 giugno 2020 12:29
A: nysthi/nysthi <nysthi@noreply.github.com>
Cc: ale47p <ale47p@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [nysthi/nysthi] TUNATHOR - range input - feature request (#275)


faccio io la chiusura, poi quando distribuisco
grazie mille!

**Comment by Trigger1998** [comment]
Hi! I want to calibrate my behringer crave, but tunathor always stucks, because of range. Crave can be calibrated only for 2 octaves with dc coupled audio interface. But there is range about 4 octaves as minimum. Can it be changed?! Or can i set up the range it manual.

**Comment by ale47p** [comment]
Hi, I don't think you can tune it with TUNATHOR, and I don't know if you could with VCV Rack. The other "tuning" modules for VCV Rack (as far as I know) are the ones from EXPERT SLEEPERS, but I don't know if they could work for you.

I see that the Crave has 10 octave range and there are 2 screws for tuning it manually...I would go for it...https://www.youtube.com/watch?v=Ex5Pi5V-364

bye!
A


________________________________
Da: Trigger1998 ***@***.***>
Inviato: domenica 15 maggio 2022 04:08
A: nysthi/nysthi ***@***.***>
Cc: ale47p ***@***.***>; Author ***@***.***>
Oggetto: Re: [nysthi/nysthi] TUNATHOR - range input - feature request (#275)


Hi! I want to calibrate my behringer crave, but tunathor always stucks, because of range. Crave can be calibrated only for 2 octaves with dc coupled audio interface. But there is range about 4 octaves as minimum. Can it be changed?! Or can i set up the range it manual.
