### ISSUE TITLE
Quadsimpler plays all samples on startup

### ISSUE THREAD

**Issue by Deevje** [nysthi/nysthi#276]
Hello, first of all: thanks for your amazing library of plugins!

Second: I am having a problem with Quadsimpler, it immediately plays all the samples that are loaded into it when I open Rack, which makes for very unpleasant surprises to say the least!

Is there something I'm missing or doing wrong? Or could it be a bug?

I hope you can help!

Kind regards,
Deev

**Comment by nysthi** [comment]
was not a bug, but I've added a new command from menu

in version 1.0.12 

# QUAD SIMPLER
# COMPLEX SIMPLER
# CONFUSING SIMPLER
# SIMPLICITER
*	[FEATURE REQ] add "Autoplay on LOAD" command from MENU
	* 	if ON (by default) the sampler will play, on LOAD
	*	if OFF a START command (or a trig) is needed

**Comment by Deevje** [comment]
Awesome! Thank you!

Op za 30 mei 2020 15:15 schreef nysthi <notifications@github.com>:
