### ISSUE TITLE
DX7 Envelope Polyphonic Tag

### ISSUE THREAD

**Issue by Telerex** [nysthi/nysthi#277]
I was just about to send you a groveling request for a polyphonic DX7 envelope, when I noticed that it was already polyphonic. Thanks. 
I will still grovel a little and say, please add the polyphonic tag when you get the chance.

**Comment by nysthi** [comment]
oops

will be in 
in the next version!

thanks

**Comment by nysthi** [comment]
will be in version 1.0.12
