### ISSUE TITLE
Simpliciter crash when saving wav

### ISSUE THREAD

**Issue by ivbelov** [nysthi/nysthi#278]
Hello, ive got xps 7590, windows 10 (build 1909), and after i've recorded some stuff (about 14 second of it) and trying to export in a file, i've got a vcv rack crash. Audio has been recorded correctly.
stacktrace:

6: ZN4rack10appDestroyEv 0x456435
5: gai_strerrorW 0x739800
4: _C_specific_handler 0x7b27fb0
3: _chkstk 0x90410b0
2: RtlRaiseException 0x9009e70
1: KiUserExceptionDispatcher 0x903fe10
0: KiUserExceptionDispatcher 0x903fe10

**Comment by nysthi** [comment]
So the file was saved but after you got the crash ?

this is just a report of the exception being reported
do you have a bigger log ?
thanks

**Comment by nysthi** [comment]
ok no log
