### ISSUE TITLE
POLYREC64 deletes file of a long recording (~7 minutes?)

### ISSUE THREAD

**Issue by ROGAVKA** [nysthi/nysthi#279]
Today I noticed that POLYREC64 creates a temporary file in a chosen folder but after I press stop it deletes the file and leaves no trace of recording itself :(
Sometimes Windows displays the size of resilting file for a second but then the file disappears. 
Here's the video: 
https://youtu.be/SsIXpBXNC2s

**Comment by ROGAVKA** [comment]
Couple of notes after some experiments:
- doesn't happen with short recordings
- doesn't happen when saving as PCM 
- doesn't seem to depend on "consolidate tracks" setting
- if I connect only first "16" port of POLYREC64 then the recording length after which file doesn't save seems to double

**Comment by nysthi** [comment]
there is a 2GB limit on wav files, are you hitting it ?

if you think you are going OVER the 2GB, you must use PCM

**Comment by nysthi** [comment]
anyway I never seen the behaviour you are seeing
a file should be saved anyway (corrupted)
maybe you have physical limit to 4gb per file on WIN ?

**Comment by ROGAVKA** [comment]
>maybe you have physical limit to 4gb per file on WIN ?
definitely not the case:)

i don't know about hitting 2GB limit (cause I can't measure the file size, it just shows 0b for pcm while recording and deletes afterwards) but it really seems like "hitting the max size" issue, so you are probably right. don't know why file gets deleted though

a question: is "consolidate tracks" applied before or after conversion to wav? if after, may be the allowed length could be extended by first removing unnecessary tracks and then converting to wav?

and one more feature suggestion from me: may be write separate tracks wav files as an additional option (with the option to group consequent pairs to stereo tracks)? besides size issues, it seems that "multitrack wav" is very alien to a lot of software (including some of major DAWs) and decoding recordings is a huge a pain sometimes, at least for me :)

cheers

**Comment by nysthi** [comment]
what you see is a temporary file (the pcm at zero)
probably you are seeing it not flushed
if you try to duplicate it, you should see the real size of it

I use temp files and at the end of the recording I start an offline process to obtain the final file
only this way I'm able to write on disk 64 tracks with only 3% of CPU occupied

the consolidate is applied at the end, one by one the track are checked, and discarded if at ZERO

regarding the space on disk
if you are running a 48khz and you want to save 16 bits wav files 16 tracks
you are consuming 48000 * 2 * 16 * 60 bytes per minute -> 92 Mb per minute
max 21 minutes on a WAV
if you are using 32bit float at 48000 for 64 tracks your consume will be 738 Mb per minute
and you can record only 2 minutes and 47 seconds

I think I can work on the separated wav (one day)
but you must open a separated ISSUE, with a feature request ;)

grazie mille !

**Comment by nysthi** [comment]
probably  I'm going to add a new saving mode: one by one tracks in WAV format

**Comment by ROGAVKA** [comment]
YES works like a charm now! Just recorded 30 minutes 32 tracks easily,thanks a lot!

**Comment by antoniotuzzi** [comment]
that was hard (only on win, and I don't use it!)
