### ISSUE TITLE
simpler crashes on load

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#28]
simpler crashes on load when opening a patch from a different computer, if the wav directory is not exactly the same

**Comment by nysthi** [comment]
what is your system ?
the directory is "nysthi/cache" and should be always present

**Comment by joopvdl** [comment]
this was long before 0.6...
I had rack in a different directory than the default.
the cache dir was there.
Win10

**Comment by antoniotuzzi** [comment]
thank you for the report !

**Comment by josbouten** [comment]
I'm experiencing crashes whenever I want to load a sample in the complex or the quad simpler. I'm developing a plugin and running VCV Rack 0.6.2c on OSX 10.14.4

**Comment by patman023** [comment]
open a new bug report with more details @josbouten? This issue was closed over a year and tens of nysthi versions ago.
