### ISSUE TITLE
Feature request: Dopplab - reverse path option

### ISSUE THREAD

**Issue by cwcage** [nysthi/nysthi#281]
It would be great if I could reverse the direction of the movement on the Dopplab path.

I’ve been looking for anything on iOS that would allow me to move sounds in space on a controlled path over an extended period of time. Dopplab in miRack is the best solution I’ve found so far. I’m finally get the hang of running multiple instances in sync. Now it would be amazing if I could have one going clockwise and another going counter-clockwise.

**Comment by nysthi** [comment]
ok the new feature will be available in version 1.0.12 (to be released)
