### ISSUE TITLE
DX7 Envelope Polyphonic Behaviour

### ISSUE THREAD

**Issue by Telerex** [nysthi/nysthi#282]
Having finally just got the chance to us DX7 Envelope properly in a patch, I have noticed that it seems to act up when used polyphonically.
When placed in a patch all voices channels other than voice one are not set to the control settings and you have to move each of the controls for all the voices to fall in line. This state also occurs when you initialize the module.
Hopefully, it's not just me that this happening for and that you can replicate the problem to see what I mean.
![DX7 Envelope](https://user-images.githubusercontent.com/55559146/81511058-85182a00-930e-11ea-9ebe-736c2766872d.JPG)

**Comment by nysthi** [comment]
I've seen the defect...
working on it...
thanks

**Comment by nysthi** [comment]
solved in next version 1.0.12
