### ISSUE TITLE
8Mix draws on top of plugin browser

### ISSUE THREAD

**Issue by jpnielsen** [nysthi/nysthi#283]
at low zoom%, pixels from 8mix can be seen on top of the plugin browser (windows 10)

https://drive.google.com/open?id=1oS7GXTfuKzf8I3zqngMBaeNnBoZntADl
https://drive.google.com/open?id=1cyrc7XSU0XP3LPuTjy0rhr5qisUtKO98

**Comment by nysthi** [comment]
this is an outstanding bug coming form the graphic vector library, nothing related to the nysthi drawing tecniques
is still here since the 0.6 version!
