### ISSUE TITLE
Simpliciter not saving correct length when in START and LENGTH mode

### ISSUE THREAD

**Issue by MaZe6K** [nysthi/nysthi#285]
When I save a patch with Simpliciter in START and LENGTH mode and open it up again, the length setting is not correct, but seems to be stored as if it was the end point in regular mode.

**Comment by nysthi** [comment]
solved in 1.0.17 version
and I solved the dragging case too (in START and LENGHT mode the END knob should not move!

## SIMPLICITER  
*	bug: START and LENGHT mode was not correctly reloaded (#285)
