### ISSUE TITLE
alt binson graphic

### ISSUE THREAD

**Issue by armandvedel** [nysthi/nysthi#286]
Maybe someone will find this usefull...I made this more mellow binson graphic to keep my eyes from falling out of my head. It uses slightly offset concentric circles to indicate movement. 

[JIRAJIRADISK.svg.zip](https://github.com/nysthi/nysthi/files/4740124/JIRAJIRADISK.svg.zip)

**Comment by nysthi** [comment]
ok
added to the resource as
`JIRAJIRADISK_concentric`

so in next 1.0.12 release people are going to use it, maybe ;)

**Comment by armandvedel** [comment]
Cool! how do you change disks, anyway? I have been renaming the resource files, but maybe i've missed it?

**Comment by nysthi** [comment]
it's the only way, change the resource

**Comment by armandvedel** [comment]
thanks!
