### ISSUE TITLE
SQ 1

### ISSUE THREAD

**Issue by XtremeSounds** [nysthi/nysthi#288]
Hi would it be possible to fit a scale and root note settings in this little guy? Even if it was a right click menu item

**Comment by modman2019** [comment]
Never mind. I would also need a note threshhold as well. I will work around it. Thanks

**Comment by nysthi** [comment]
scale, base ? 
basic quantizer?

what is a note threshhold ?

**Comment by modman2019** [comment]
Its ok I will put it together outside of the sequencer.
