### ISSUE TITLE
Bug: ExpiredTime not counting in seconds 

### ISSUE THREAD

**Issue by patman023** [nysthi/nysthi#289]
https://github.com/patman023/nysthimanual/issues/18

Via @wilpar

I put ExpiredTime into my rack, and it's counting at about 2.5 to 3 X real time. Is this expected? I already feel like I spend too much time inside VCV, this makes me feel even worse!

MacOS latest.
VCV Rack 1.1.6

**Comment by nysthi** [comment]
pity 
I don't have last macosx... :)
but the time is based on the sampling rate in the patch
I can't see what could be the problem...

**Comment by nysthi** [comment]
tested it
the times uses the current sample rate of the system
and uses the process function for the updates (and so the AUDIO clock)
for me it's not a bug
