### ISSUE TITLE
Multiple instances of QuadSimpler in a patch

### ISSUE THREAD

**Issue by pgatt** [nysthi/nysthi#290]
Hi Antonio,

I have two instances of QuadSimpler in a patch and when I reopen the patch both QuadSimplers are remembering one of the QuadSimplers samples. Sometimes they are both set to the first instances samples (but not the other settings) sometimes they are both set to the second, but never to the two different sets of samples loaded.

**Comment by nysthi** [comment]
because probably you used the Copy and paste to create the copy

probably now they share the same ID and doesn't work

**Comment by nysthi** [comment]
probably, as the QuadSimpler are not recording, I could change them to avoid the use of CACHE

**Comment by pgatt** [comment]
Yeah I probably did copy and paste.

**Comment by nysthi** [comment]
closing
this is a problem coming from VCV rack
