### ISSUE TITLE
TZOP FINE tuning is not working

### ISSUE THREAD

**Issue by MaZe6K** [nysthi/nysthi#291]
The FINE tuning knob doesn't seem to tune with the expected range of +- 100 cents.
It seems to me it tunes linear... can't really tell, but the range is definitely too small.

Great Oscillator by the way, thanks very much!

**Comment by nysthi** [comment]
I'll check it
I remember I was not very precise regarding the "FINE"

**Comment by nysthi** [comment]
ok done
now the FINE will correctly do -1 semitone to +1 semitone

in version 1.0.14

**Comment by MaZe6K** [comment]
Thank You!

I also noticed that the 3 tuning knobs below the ratio-knob stop working when an oscillator is connected as an expander... they only start working again if the V/Oct input is plugged... don't know if this might be on purpose.

**Comment by nysthi** [comment]
on purpose
if connected as MODULATOR the
OCT and SEMI are disabled (the FINE and RATIO are always working)

to make it working and detach from the CV coming from the CARRIER you have 2 ways

press the DETACH button (so you can build inharmonic FM chains, check on DX7 manuals)

or you can attach e direct CV in (in that case OCT and SEMI are working too)

**Comment by MaZe6K** [comment]
Is the update still coming or could you provide a windows build?

**Comment by nysthi** [comment]
I've delayed all the operations
my job is getting all the time
I'll try to do a release by the next weeken
thank you

**Comment by MaZe6K** [comment]
Ok cool, no hurry and no worry, take your time.
