### ISSUE TITLE
GRAN TUNISMO/HOT TUNA Voltage Meter

### ISSUE THREAD

**Issue by Telerex** [nysthi/nysthi#293]
A bit of a personal request here, that I think others would use.

I have done patches that emulate the EMS VCS3 and the Analog Solutions Colossus, but one thing I need to make them look the part is a version of their meters. For my VCS3 patch I put Gran Tunismo in there just for the look if not the function.

Could we please have a voltage meter in the style of Gran Tunismo and/or Hot Tuna? Even if a voltage mode was added to those two modules, that would be great.

I hope that this isn't too big an ask. Thanks.

**Comment by nysthi** [comment]
so you want a meter doing just form 0 to 10v
and from -5 to +5 ? (like in the synthi ?)

**Comment by Telerex** [comment]
That would be lovely. If you can think of any other modes that you would like, that would be good to. Thanks.

**Comment by nysthi** [comment]
going to verify

**Comment by nysthi** [comment]
coming in version 1.0.14
![Screen Shot 2020-07-06 at 20 05 34](https://user-images.githubusercontent.com/33201978/86624811-41ffcd80-bfc4-11ea-9b36-afb1a8f5d58e.png)

**Comment by nysthi** [comment]
I've omitted the output that in a real EMS meter should invert the signal
you can do inversion in 10k different modes in VCV !

**Comment by Telerex** [comment]
That's a thing of beauty. Thank you so much.
