### ISSUE TITLE
poly Jooper

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#295]
Hey Antonio, 
would it be hard to make Jooper polyphonic? Or even to make a small poly Jooper, with just one channel (instead of the 8 ones from Jooper)? If it's still quite hard, you could even drop the scenes (so it's just a switch). Yes, I need a polyphonic switch :)
Hope you are doing ok, btw. 
Cheers, Joop

**Comment by nysthi** [comment]
I'll check it

**Comment by nysthi** [comment]
verified..

added POLY

in vers 1.0.14

**Comment by joopvdl** [comment]
Nysthi is my hero.
