### ISSUE TITLE
Etchasketchoscope alternate mode request

### ISSUE THREAD

**Issue by Eurikon** [nysthi/nysthi#296]
Hi Antonio!, 

could it be possible to get a special mode on Etchasketchoscope so that it behaves/mimics more like this one:
https://github.com/kritzikratzi/Oscilloscope/

Currently when trying to visualize a [OsciStudio](https://oscilloscopemusic.com/oscistudio.php) wave file, the current oscilloscopes in VCV including Nysthi oscilloscope will show many extra drawing lines.

But when i use the the "oscilloscope" from the above github link, or the built-in oscilloscope from OsciStudio, i get better visual performance for the Lissajous style.
Could it be that those oscilloscope behave more like a vector oscilloscope?

**Comment by VegaDeftwing** [comment]
I believe those extra lines may be because of the sample rate. I can't test right now, but does increasing your oversampling (like 88/96khz) help?

**Comment by Eurikon** [comment]
@VegaDeftwing hi,
if you mean the "Engine sample rate" , then the answer is no, it did not give any better results.

however, changing the Etchasketchoscope to "show points" made it look a lot better, and close to the other scope from the link i posted earlier.

It is still not as the other, much better with the points drawing.

**Comment by nysthi** [comment]
please send me a (small) OsciStudio  wav file you think is incorrectly visualized

**Comment by Eurikon** [comment]
here you go.
[eu-logo-osci.zip](https://github.com/nysthi/nysthi/files/4878190/eu-logo-osci.zip)

don't get me wrong , i don't say it is displayed incorrectly!
it is displayed differently either with many lines :)
but when i set the scope to dots it looks slightly better.

however if you load this same wav file in the oscilloscope from the other github page, it plays way smoother with less artifacts. 

of course i can also be totally wrong about this all, it is new terrain for me anyway :)

**Comment by nysthi** [comment]
btw @VegaDeftwing is correct about the sampling rate
the more higher, the more precise is the beam

in the meantime I've added a new filter for the drawing
it's a knob called "Max drawable vector length" and goes from 1 (pixel) to 400 pixels that is the default (like it is now)
with the filter you can exclude big jumps of the beam from drawing

I can see with correct calibrations and 88 kHz the correct animation you sent me

will be in version 1.0.14

**Comment by Eurikon** [comment]
ok thank you very much! 

so do we talk about the sample rate of the wav file itself, or the sample engine from the Rack top menu?
because the higher i set the sample rate of the engine, the faster the sample will play in simpler etc. which is not desired.

**Comment by nysthi** [comment]
you are wrong, or you never used simpler or simpliciter ;)

my samplers are aware of sampling rate of the system (they do auto subsampling or oversampling)

of course if you record  88kHz you have double of informations
and if you set the engine sampling rate to 88 you'll get the same

if you set the engine to 44 one out of 2 samples will be jumped

if we invert
the file is recorderd at 22khz and the system rate is 44
the sampler will create intermediate samples interpolating

**Comment by Eurikon** [comment]
ah! you guys are right, i just checked again @192 seemed to work just fine.
i probably had a wrong audio driver selected before, when i saw it fluctuate speed. so my bad!

and lol, i am one of your biggest simpler fans :P so i know them pretty much in and out.

I will wait for the new release and do all again with higher quality conversions, 
that together with the new mode on the oscilloscope should be pure awesomeness :D

thanks again!

**Comment by nysthi** [comment]
added lights-on mode too
so will be visible with modular fungi plugin
