### ISSUE TITLE
TZEN Bug when placing a module to the left

### ISSUE THREAD

**Issue by Petervos2018** [nysthi/nysthi#297]
![afbeelding](https://user-images.githubusercontent.com/46076474/87167600-84c7eb00-c2cd-11ea-8880-48220ec0c867.png)

When a place a module directly to the left of the TZEN it stops doing what it's supposed to do.(bottom row)
When I leave a space, it works as it should (top row).
Here is the patch to try.

[Nysthi TZEN TZOP Bug 10072020.zip](https://github.com/nysthi/nysthi/files/4903805/Nysthi.TZEN.TZOP.Bug.10072020.zip)

Greetings Peter.

**Comment by nysthi** [comment]
good catch!

**Comment by nysthi** [comment]
solved in  vers 1.0.14

**Comment by nysthi** [comment]
@jeremywen 
as you are a huge user
better you know about it! ;)
