### ISSUE TITLE
Version 1.0.13 is crashing Rack when opening Module Browser

### ISSUE THREAD

**Issue by MaZe6K** [nysthi/nysthi#298]
I didn't have this problem on my last 2 installs on Win 7 and 10, but now on my laptop with a new Windows 10, Rack crashes when the Module Browser is trying to display the NYSTHI modules
[log.txt](https://github.com/nysthi/nysthi/files/4905691/log.txt)
this is the log

**Comment by nysthi** [comment]
you have outdated openGL drivers on your new laptop

check same problems here
https://github.com/nysthi/nysthi/issues/271

**Comment by MaZe6K** [comment]
You're right, Thank You! everything working again.
