### ISSUE TITLE
HotTuna feature request - show midi note number

### ISSUE THREAD

**Issue by unlessgames** [nysthi/nysthi#299]
Would be useful to see rounded midi note number (for example 60 for C4, or without rounding, using cents 60+.34) in the right-bottom corner of the display.

**Comment by nysthi** [comment]
coming in version 1.0.14
![Screen Shot 2020-07-15 at 19 13 42](https://user-images.githubusercontent.com/33201978/87574896-5e3ff080-c6cf-11ea-97e0-598f1edff3a7.png)
![Screen Shot 2020-07-15 at 19 13 28](https://user-images.githubusercontent.com/33201978/87574904-5f711d80-c6cf-11ea-8a19-69fe18d92435.png)
