### ISSUE TITLE
Editing the Patch files for 0.5.0

### ISSUE THREAD

**Issue by metaphorz** [nysthi/nysthi#3]
@Nysthi: some of my favorite patches from 0.4.0 are not loading the nysthi MVerb in particular. For example:

![screenshot 2017-11-22 11 07 43_preview](https://user-images.githubusercontent.com/3519631/33140396-79e1c240-cf75-11e7-93d7-e63b2d4a29db.png)

Arable has not been updated to 0.5.0, but the nysthi loading problem happens on many other patches.

Is there a clean way to edit the patch .vcv file to solve this issue for patches? My guess is that the way you store this inside the json file is different from the way you did it for 0.4.0. I would think a text editor might fix this?

**Comment by antoniotuzzi** [comment]
send me the patch
and I'll find a solution

**Comment by metaphorz** [comment]
Sure - here is the first one of 5 "demo patches" from Strum.

[2_voices_and_drums.vcv.zip](https://github.com/nysthi/nysthi/files/1496939/2_voices_and_drums.vcv.zip)

**Comment by antoniotuzzi** [comment]
try to change
"nysthi"
to
"NYSTHI"

and let me know

**Comment by metaphorz** [comment]
That worked. Thanks - I'll use similar edits on other 0.4.0 patches.

**Comment by nysthi** [comment]
great!
