### ISSUE TITLE
Request: DX7 Envelope as expander to TZOP

### ISSUE THREAD

**Issue by dheles** [nysthi/nysthi#301]
I have really been enjoying reverse-engineering (and mucking about with) old DX7 patches using TZOP and the your DX7 Envelope. I think it would be quite useful if the DX7 Envelope could act as an expander to TZOP in the same way that TZEN does.

Thanks for your huge (and hugely useful) collection of modules!

**Comment by nysthi** [comment]
too much time
and still is not perfect
