### ISSUE TITLE
Ambuance No sound from right channel

### ISSUE THREAD

**Issue by Petervos2018** [nysthi/nysthi#307]
Hi Antonio,

The signal is panned hard L/R.
As you can see from the picture, there is no sound coming from Ambuance when the left channel is connected (bottom).
When I remove the left channel (top) there is sound.

![afbeelding](https://user-images.githubusercontent.com/46076474/93682991-18c4e880-faaf-11ea-8281-97f1de1950ef.png)

Any idea why ?

Greetings Peter.

**Comment by nysthi** [comment]
I'll check, thanks for the report

**Comment by nysthi** [comment]
great catch! I've seen the bug... :D 👍

**Comment by nysthi** [comment]
solved in 1.0.15
