### ISSUE TITLE
Simpliciter crashing the patch, possible memory leak?

### ISSUE THREAD

**Issue by Eurikon** [nysthi/nysthi#309]
Hi Antonio, can you please look at the debug report in this issue posted by Marc.
I am having a patch that crashes, and the problem was traced back to Simpliciter.

https://github.com/MarcBoule/MindMeldModular/issues/52#issuecomment-698368083

Please let me know if i can provide any other information that you need?

**Comment by nysthi** [comment]
I need reproducibilty
I need a patch with  just simpliciter + a nysthi mixer that causes a crash
+ the file audio used in

I tested it, CAN'T repro

**Comment by Eurikon** [comment]
I can send you the patch as it is with the audio file that is used, if that helps?

**Comment by nysthi** [comment]
if it's a minimal patch with only nysthi modules, would be great (otherwise it's almost impossible to debug it)
send it or attach the zip to this thread, thank you

**Comment by Eurikon** [comment]
Hi Antonio,
actually i managed to shrink the patch down to only Simpliciter loaded, triggered by CLKD and an audio module for compatibility.
As soon as i hit start, the crash will occur after a couple of seconds.
If i initialize the Simpliciter module before clicking start, no crash will occur.
plugin version: 1.0.14
 
[Blue wheel of fortune_debug version.zip](https://github.com/nysthi/nysthi/files/5283290/Blue.wheel.of.fortune_debug.version.zip)

hope this helps

**Comment by nysthi** [comment]
@Eurikon thank you
going to verify

**Comment by nysthi** [comment]
I think I nailed it
it's a very convoluted situation
regarding peak point and peak grid mode

solved in version 1.0.16

**Comment by Eurikon** [comment]
I am relieved to hear you found something, cause this bug was very weird to pin point. 
Hope it solves it, I'll wait for the update and test again. 
Thanks my friend!

**Comment by nysthi** [comment]
are you on windows ?

**Comment by Eurikon** [comment]
yes

**Comment by nysthi** [comment]
@Eurikon can you test this demo release, thanks (only win)
https://github.com/nysthi/nysthi/releases/tag/v1.0.16beta1

**Comment by Eurikon** [comment]
Thanks, tested, no crash! 

vintage approved 👍

**Comment by nysthi** [comment]
final official release
https://github.com/nysthi/nysthi/releases/tag/v1.0.16
