### ISSUE TITLE
Simple patch that crashes when using Scala module

### ISSUE THREAD

**Issue by Chaircrusher** [nysthi/nysthi#31]
[crashesScalaModule.zip](https://github.com/nysthi/nysthi/files/1842370/crashesScalaModule.zip)
1. Load the enclosed primes-2.scl
2. increase the rate of the LFO. BLAMMO!

PS: Probably should include the standard equal tempered 12 tone scale as a scala file....

**Comment by nysthi** [comment]
testing it
sorry I missed it!

**Comment by nysthi** [comment]
I need to do a serious revision of the parser! thanks for the report

**Comment by nysthi** [comment]
checked the file and the rules for creating an SCL file
step are expressed as "cents" or as ratios
ratios are always represented with a single integer  (for example 2 means  "2/1" )
or a with a fraction example "4/3"

the rule is not written, but "ratios" must be > than 1/1

I can change the parse and add a rule that if a ratio is less than 1.0, I add 1.0
but that is not what you expect from you work about PRIMES
3/151 --> .019867549668874 --> 1.019867549668874
79/107 --> .738317757009346 --> 1.738317757009346

or maybe the scale should be more something like
31/29 // 1.068965517241379  (added by me as example)
107/79  //1.354430379746835
139/101 //1.376237623762376
151/107 //1.411214953271028
61/43 //1.418604651162791

**Comment by Chaircrusher** [comment]
OK Interesting.  So really I was doing it wrong but no one bothered explaining how I was doing it wrong.

I modified my generating script so that it only generates ratios in the range 1.0 < X < 2.0, and tacks 2/1 on the end to complete the octave.  Don't know if that part is necessary.

Then I uncovered another Scala crash -- see attached zip. Using the provided scala file, driving Scala with a unipolar ramp wave seems to crash 0.6 Rack reliably.  If it doesn't do it immediately, mess with the rate knob on the LFO.
[lfoScalaCrash.zip](https://github.com/nysthi/nysthi/files/1862564/lfoScalaCrash.zip)

**Comment by nysthi** [comment]
ok, I'll test/check it ASAP

anyway, SCL files can contain ratios BIGGER than 2/1 (having checked other files)
but as I'm replicating the quantizing on 14 octaves if the ratio is bigger than 4/! I consider it as NOT RECURRING (becomes a FIXED grid not repeated)

**Comment by nysthi** [comment]
checked, tested the **testprimes.scl** SCL file  and seems well built
and I used the **lfoScalaCrash.vcv** file
but I was unable to repro the crash, I played very hard with the LFO rate, using both SAW and TRI waves

since 0.5.13 I removed any std:string movement or copy during the engine thread

but I still think is something related to strings

maybe I have to try harder ! :)
