### ISSUE TITLE
Quadsimpler sound is late compared to trigger

### ISSUE THREAD

**Issue by jamshark70** [nysthi/nysthi#310]
I am getting about 44 ms of delay when triggering samples in quadsimpler.

Here's the patch:

![desynced-quadsimpler](https://user-images.githubusercontent.com/318301/94335774-67730500-0010-11eb-8ea7-3f53f55d1ea9.png)

There's one LFO serving as a clock source, driving an envelope generator on the one hand and triggering quadsimpler on the other.

The patch screenshot might not show it, but I recorded a bit with the enveloped synth in the left channel and the sample player on the right. Expected them to be synced (because of being driven by the same clock), but obviously they are not.

![desynced-quadsimpler-audio](https://user-images.githubusercontent.com/318301/94335796-85406a00-0010-11eb-8a85-42be3e54e23d.png)

This makes it difficult to synchronize drums played in quadsimpler vs synth sequences.

If I add a clockable delay to the gate signal being passed to the envelope and set it to 0.044 sec (and pass through wet only), then the two play together.

Note also that I edited the sample to remove all empty space from the beginning -- the sound from the sample begins immediately. So I have to conclude that quadsimpler is just not playing on time.

Edit: I also tried with a 4x smaller block size (256 samples vs 1024 samples) and the delay is still about 44 ms.

**Comment by espenstoro** [comment]
Can confirm.
Complex Simpler, Quad Simpler and Confusing Simpler all have the same delay. Testing the same audio with all three versus Simpliciter demonstrates the issue. Simpliciter is always on, the others are not. The previous versions used to play back correctly.

Plugin version 10.0.15, Rack 1.1.6, Windows.

**Comment by jamshark70** [comment]
One other finding: I also tried MusicalBox. It has the delay when I raise anti-click, but it's on time when anti-click is 0. Maybe anti-click logic was added into the other modules...?

**Comment by nysthi** [comment]
interesting
I've must have exaggerate with smoothing stuff... I hate smoothers... :)

I've to investigate
sorry about that

**Comment by nysthi** [comment]
> One other finding: I also tried MusicalBox. It has the delay when I raise anti-click, but it's on time when anti-click is 0. Maybe anti-click logic was added into the other modules...?

can you test the simpliciter too with anti-click at zero ?

**Comment by espenstoro** [comment]
Simpliciter does not have any delay that I can detect on default settings.

**Comment by nysthi** [comment]
found 
as I was suspecting
I did some change in simpliciter
and on the base file oscillator
and I forgot the changes were affecting old samplers too

corrected in 1.0.16 version, thank you !

**Comment by nysthi** [comment]
@jamshark70 @espenstoro can you test this beta release ? (only win)
https://github.com/nysthi/nysthi/releases/tag/v1.0.16beta1

**Comment by jamshark70** [comment]
> @jamshark70 @espenstoro can you test this beta release ? (only win)

I'm on Linux. Maybe I can try tomorrow in my teaching office (win10 machine there).

**Comment by espenstoro** [comment]
Seems to work great now, no delay. :)

**Comment by nysthi** [comment]
final revision here
with special @espenstoro command too... :D
https://github.com/nysthi/nysthi/releases/tag/v1.0.16

**Comment by espenstoro** [comment]
I don't really understand how it works. The start and end will still click. What's the workflow here?

Also, think I found an issue. Deleting the selection can make outputs go high, need to delete and reload the module. Just record something, apply that trick to a selection a couple of times, then delete selection, and outputs go maxed out. Can't make it happen consistently, but it happened three times just now.

**Comment by nysthi** [comment]
removing it
I can't repro on my mac
and I can't use the win to test it

**Comment by espenstoro** [comment]
This is weird, it only happens sometimes.

Record audio from a vco
Disconnect inputs
Apply trick twice
Delete selection

That's all I did. It's not consistent, it happens every now and then, which is weird. I've tried to do several combinations. Can't find a reliable way to do it.

**Comment by nysthi** [comment]
@espenstoro 
can you test this new release ?

(same place
https://github.com/nysthi/nysthi/releases/tag/v1.0.16
)

your command should be ok now... :D

**Comment by espenstoro** [comment]
Yay! Tested and works. That's awesome. :) 
Curiosity, how long is the xfade, and is there a way to adjust it? Might not be important, just tried it a couple of times, and it's smooth.

**Comment by nysthi** [comment]
cool

440 samples are lost in the transition (440 sample are the area in the middle doing the cross equal power fade

**Comment by nysthi** [comment]
I did test with 25, 50, 100, and 200 samples
but I feel 400 was better for the xfade

**Comment by espenstoro** [comment]
Yeah, the bigger the better for smooth transitions on complex sounds.
