### ISSUE TITLE
Poly Scala Quantizer Feature Request

### ISSUE THREAD

**Issue by Mr-MG** [nysthi/nysthi#313]
Greetings.

When creating a .scl file in Scala, the program defaults to C4 having a frequency of 261.625565 Hz, but in the Scala program that base frequency can be set to whatever the user desires. However, as no base frequency can be set in the actual .scl file, the Poly Scala Quantizer defaults to this same frequency of C4 = 261.625565 Hz.

It would be very helpful if it were possible to set one's own base frequency, reference key, and key for 1/1 as that would expand the usefulness of bringing in .scl files tremendously.

Thank you.

**Comment by nysthi** [comment]
thank you for the report, I'll check if it's doable

**Comment by Mr-MG** [comment]
Thank you! I understand that C default may be intrinsic to the underlying VCV platform - so I appreciate you're looking into it.

**Comment by nysthi** [comment]
the root parameter has been added
the root freq is the freq were the SCALA is computed
and can be set via CV too (from 0 to 10v -> from 131 to 523 Hz

from version 1.0.17
![Screen Shot 2020-11-18 at 21 15 04](https://user-images.githubusercontent.com/33201978/99583168-65f80480-29e3-11eb-85fb-36f2c1926a32.png)

**Comment by Mr-MG** [comment]
That's awesome! Thank you so much!

Kind regards,
-Matthew

**Comment by nysthi** [comment]
## POLY SCALA QUANTIZER
*	FEATURE REQUEST: add root frequency for the applied, scala.   (#313)
	The base it's always C4 (261.626 Hz)  
	The field is editable and value is in Hz  
	You can write also in note form : "C3 -> B4"   
	the filed will autotranslate in correct frequency
	The frequency can be modulate via CV where 
	0 -> 10v are maped from C3 to C5 range  
	Added a Reset scale root command (to C4) via contextual menu
