### ISSUE TITLE
Jooper D input bug

### ISSUE THREAD

**Issue by midiguru23** [nysthi/nysthi#314]
Using Jooper 1.0.16 (Windows build), the D input channels on the left side all seem to send 0.0 to the output, no matter what the input value is. This is true in every routing mode, on several outputs, and seems to be true on several of the rows. (I didn't check every row.) I'm testing this with Fixed Voltage Source and MultiVoltiMetro, so I'm pretty sure I have a straightforward view of the signal values. If you need a test patch, let me know and I'll whip one up.

--Jim Aikin

**Comment by nysthi** [comment]
Thank you for the report @midiguru23 ! I'll check ASAP

**Comment by nysthi** [comment]
ok
simple cut and paste bug (checkin on port 3 but was port 4...)
will be solved in version 1.0.17
