### ISSUE TITLE
SQ1:remember the step position

### ISSUE THREAD

**Issue by nnbveh** [nysthi/nysthi#317]
Hi! I'm using sq1 as a sort of fixed voltages bank, setting steps to different voltages and then switching between them with a button, it's useful for pre-defining different bpm speeds for example...the only problem i have is that it doesn't remember the step position when you close the patch, and always resets to the first one...i know what i'm doing is not the intended use, but it is so tiny and useable otherwise, would be great addition to functionality i think.

thanks!

**Comment by nysthi** [comment]
please use SQUONK for this kind of use (you have a keyboard to switch ! or a TRIG or a VOLTAGE)

thank you!
Anto

**Comment by nnbveh** [comment]
Squonk is too BIG to use as an utility module, so thanks but that won't
work...

[image: Screen Shot 2020-10-29 at 20.33.48.png]
