### ISSUE TITLE
Some modules do not read skin from res_user

### ISSUE THREAD

**Issue by spectromas** [nysthi/nysthi#318]
The following files do not draw their skin from the res-users directory, only the default res directory. Could this be changed so that they can be reskinned? 

- MusicalBox.svg
- MusicalBox2.svg
- nysthipyer2_simpliciter_bg.svg
- Sussudio.svg
- TheCage.svg

**Comment by nysthi** [comment]
Ok
I'll check if can be done

**Comment by nysthi** [comment]
solved in version 1.0.17 (to be released)
every module is skinnable now
