### ISSUE TITLE
Jooper request: multiplexer mode without summing

### ISSUE THREAD

**Issue by nnbveh** [nysthi/nysthi#319]
Hi!
I've just tried to use the jooper module to create a structure, of course i didn't read the manual first so i've assumed that it could be used as a sort of 'switch mixer' by sending audio signals to different inputs and muting and unmuting the outputs...and it sort of works, in a sense that you can definitely feed it with the audio signal, but it sums all the outputs, which renders it useless for this particular purpose. I can still use it of course by feeding a constant voltage to one input of each row and then controlling some mixer module with it, but it would be fantastic if there was a mode in which one input goes only to one output per row, so A always goes to A, B to B and so on. Of course there's no point of setting up both inputs and outputs in this case since they would have to be identical in their configuration(which channels are on and which are off) so ins and outs could be coupled.

I hope i was able to describe what i mean more or less!

Thanks for the great collection of tools!

**Comment by nysthi** [comment]
you are using in multiplex mode
but you want the EXCLUSIVE mode

A IN  goes to A OUT , and if the OUT is off, there is no OUT

**Comment by nnbveh** [comment]
Okey, then just tell me, how do i make more than one channel active at the
same time in exclusive mode? Because that's what i was suggesting, and i
don't see how exclusive can be used that way...

**Comment by nnbveh** [comment]
Okey, then just tell me, how do i make more than one channel active at the same time in exclusive mode? Because that's what i was suggesting, and i don't see how exclusive can be used that way...

**Comment by nysthi** [comment]
oops
you want another mode

I have to think about it

reopening

**Comment by nysthi** [comment]
kind of "exclusive multiplex"

**Comment by nnbveh** [comment]
Exactly :) sorry for trouble, just seems to be natural addition to this
already excellent tool!

**Comment by nysthi** [comment]
seems easy, but internally is so complex because it is poliphonic too !
but don't worry
As soon as I'll check it, we'll find a solution

**Comment by nysthi** [comment]
solved
In next version

*	feature request: add MULTIPLEX in EXCLUSIVE mode (no summing of nodes)  
	A goes to A (if both active)  
	B goes to B (if both active)  
	C goes to C (if both active)  
	D goes to D (if both active)  
	
	always polyphonic, it's a superswitch-superbridge


![Screen Shot 2020-11-16 at 16 05 19](https://user-images.githubusercontent.com/33201978/99268910-09031f80-2826-11eb-9e96-05aad1aeeb81.png)
