### ISSUE TITLE
simpliciter great - but could the Gui be updated please

### ISSUE THREAD

**Issue by XtremeSounds** [nysthi/nysthi#321]
HI this is a great plugin.  I was just hoping it could get a better skin something dark skin with colorful neon lights flickering off it.   If not how can I make a skin for it?

**Comment by nysthi** [comment]
in next version 1.0.17 third party can skin it (if they want to)

**Comment by spectromas** [comment]
It can already be reskinned, I have done a version here - https://github.com/spectromas/NYSTHI-Dark-Theme. See [this issue](https://github.com/spectromas/NYSTHI-Dark-Theme/issues/1) for instructions for installing the dark skin for the samplers until the next update is out.

**Comment by XtremeSounds** [comment]
Oh yeah. Any idea what tools we need to do this?  I have Gimp

**Comment by spectromas** [comment]
If gimp can open svg files then I'm sure it would work. I use inkscape.

**Comment by XtremeSounds** [comment]
Ok thanks.  I do not see the choose theme option in vcv per the instructions

**Comment by XtremeSounds** [comment]
I see the change color option but it doesn’t affect simpliciter in any way. Oh well. thanks

**Comment by spectromas** [comment]
Please read the thread I linked above. The Extras zip will show you the files you need to edit.
