### ISSUE TITLE
Clock mult div frequency output?

### ISSUE THREAD

**Issue by nnbveh** [nysthi/nysthi#322]
Hi!

The module shows the frequencies for the clocks, but outputs only pulses, would it be possible to add either a second output for freq or a switch to choose the type of the signal?

Thanks!

**Comment by nnbveh** [comment]
Oh and maybe an output for the original clock as well in hz?

**Comment by nysthi** [comment]
what kind of output ?
I don't understand

maybe you are looking for the Freq2Voltage module ?

**Comment by nysthi** [comment]
![Screen Shot 2020-11-20 at 16 00 07](https://user-images.githubusercontent.com/33201978/99814619-804bf280-2b49-11eb-8604-9d2b1aa72a4c.png)

**Comment by nnbveh** [comment]
<img width="323" alt="Screen Shot 2020-11-20 at 18 06 06" src="https://user-images.githubusercontent.com/39271290/99815262-06395f00-2b85-11eb-9271-3528a662d197.png">

I want to be able to do this: the module receives clock which is 120bpm, converts it into HZ which is 2hz, sends it to the lfo and lfo is set to 2hz

**Comment by nysthi** [comment]
so you want to use the "p2V2 module

you can do this with tuners or with the p2v

example

but I'll try to add voltage converter too ... :D
![Screen Shot 2020-11-20 at 16 11 39](https://user-images.githubusercontent.com/33201978/99815832-2815f000-2b4b-11eb-99e4-756d075620a6.png)

**Comment by nysthi** [comment]
next version 1.0.17 
![Screen Shot 2020-11-21 at 17 18 10](https://user-images.githubusercontent.com/33201978/99882303-b065c500-2c1f-11eb-8b9a-ee2bd0e33864.png)
 there will be a Voltage output too
in same zone as the clock output

**Comment by nnbveh** [comment]
Cool! Thanks)
