### ISSUE TITLE
BZ-Envelope not actually producing the displayed envelope?

### ISSUE THREAD

**Issue by NoxyNixie** [nysthi/nysthi#324]
I was trying out BZ-Envelope with the goal to create some nice and unusual functions but to my surprise my initial test already resulted in very unexpected (and probably incorrect) behavior:

![image](https://user-images.githubusercontent.com/211381/100968238-3b549280-3531-11eb-8641-4ca1151bff10.png)

I only moved green markers (and not the in-between empty blue ones) and I set it to `From 1 to 10 seconds` mode.

In the screenshot you can clearly see that the envelopes between 1, 2 and 3 seem correct but then between 3 and 4 is very wrong followed by a very jagged wrongness between 4 and 5 and 6 seems to completely ignore the curve and doesn't even do a correct linear interpolation.

Your thoughts? (Like this its unusable for what I wanted it for).

**Comment by nysthi** [comment]
( are you low on memory ?)  :D 
I use a mac, correct results

the third example is a replica of your test,

![Screen Shot 2020-12-03 at 12 18 14](https://user-images.githubusercontent.com/33201978/101007484-bc2b8280-3561-11eb-8179-71dad03982f5.png)
![Screen Shot 2020-12-03 at 12 14 50](https://user-images.githubusercontent.com/33201978/101007517-bdf54600-3561-11eb-9a62-bd7d84bc456a.png)
![Screen Shot 2020-12-03 at 12 23 32](https://user-images.githubusercontent.com/33201978/101010754-af5b5e80-3562-11eb-84e3-c8a620657f4b.png)

**Comment by NoxyNixie** [comment]
In your replica you moved the blue empty markers (the ones in-between). Try initializing then only changing number 2, 4 and 6 and not touching any of the other points.

And no not out of memory however I did find that when moving around the points slightly I could get rid of the errors.

**Comment by nysthi** [comment]
sorry can't repro

this time I moved only the NODES (CONTROLPOINTS (blue) untouched)

![Screen Shot 2020-12-03 at 12 43 24](https://user-images.githubusercontent.com/33201978/101013858-3c9fb280-3565-11eb-94b4-ea7fa0440f5d.png)

**Comment by NoxyNixie** [comment]
Looks like you move 3 and 5 though ... here is a different but still very noticeably bad one 
[nysthi_envelope_bugs.zip](https://github.com/nysthi/nysthi/files/5635836/nysthi_envelope_bugs.zip)

![image](https://user-images.githubusercontent.com/211381/101014567-5988b580-3566-11eb-8ef1-1f959ba0384c.png)

**Comment by nysthi** [comment]
not in the second one
I see you have time at max
going to check again

**Comment by NoxyNixie** [comment]
I also provided the vcv file which should have the values exactly like I have them

**Comment by nysthi** [comment]
seen
there is a bug

**Comment by NoxyNixie** [comment]
Awesome, I probably should have provided a vcv file from the start though I didn't expect it to be so hard to replicate :P

Looking forward to a fix ;)

**Comment by nysthi** [comment]
wait for communication in this channel ! :D thanks Mark !

**Comment by nysthi** [comment]
found
very nasty math bug

**Comment by nysthi** [comment]
solved in 1.0.17 for both bz-mapper and bz-envelope

## BZ-MAPPER
## BZ-ENVELOPE
*	bug: in same situations with very aligned controlpoints and nodes, we were hitting some bizarre math limits... :D (thanks Mark Sanders for the #324)
