### ISSUE TITLE
feature request: output ramp wave associated with playback position

### ISSUE THREAD

**Issue by glocke01** [nysthi/nysthi#325]
I'd like to get a ramp wave indicating where the playhead is WRT the buffer or slice (for my intended application, slice is preferable).

You suggested on the community forum that the envelope follower output could be overloaded via right click window https://community.vcvrack.com/t/sampler-that-outputs-a-ramp-wave/11754/2?u=george_locke

Thanks!

**Comment by nysthi** [comment]
done 
will be in version 1.0.17

##SIMPLICITER
feature request: add RAMP OUT representing the position of the playhead
can be relative to slice or relative to the full sample (#325)

![Screen Shot 2020-12-05 at 13 08 04](https://user-images.githubusercontent.com/33201978/101242791-0183b780-36fc-11eb-8cf1-b378831898e7.png)
![Screen Shot 2020-12-05 at 12 37 40](https://user-images.githubusercontent.com/33201978/101242794-03e61180-36fc-11eb-8045-c1f4c4369751.png)

**Comment by glocke01** [comment]
DOPE! thanks dood!!
