### ISSUE TITLE
Programmer Ratchet Unstable in Up/Down Variations

### ISSUE THREAD

**Issue by midiguru23** [nysthi/nysthi#326]
I love the Programmer! (I used to own a Serge TKB, so I understand the concept.) What I've noticed (and I can do a video if you're unable to duplicate this) is that when both the up and down clock inputs are active, the ratchet count becomes unstable. I'm using the Audible Bernoulli Gate module, so that sometimes the up input is triggered and sometimes the down input is triggered. As long as the Bernoulli Gate is set either fully to the left output or fully to the right output, the ratcheting works as expected. But when the clock trigger goes sometimes to the up input and sometimes to the down input, sometimes I get only 3 ratchet pulses instead of 4, or only 2 pulses and they're not evenly spaced.

The attached file shows this. There are 5 active steps in the Programmer. Step 3 ratchets 4 times and step 5 ratchets twice. But when the Bernoulli knob is not in the fully left or fully right position, you'll hear odd ratcheting.

[programmer_up_and_down.zip](https://github.com/nysthi/nysthi/files/5650855/programmer_up_and_down.zip)

**Comment by nysthi** [comment]
I know, but that can't be changed
the repetitions timing are computed on clock pulse differentials
and of course with a little delay (at least 2 pulses are needed)
this means that if you have a non steady clock, the repetitions are not in sync

and SECOND rule
there are 2 different time computers for the clock speed
one is for forward pulse IN and second one for the backward pulse in
(you should notice, if you have 2 steady clock to have 2 different timing)
