### ISSUE TITLE
Unable to edit colour of Programmer 

### ISSUE THREAD

**Issue by spectromas** [nysthi/nysthi#327]
Perhaps not a bug but more of a how-to but I can't find a way to edit the colour of the Programmer panel. In inkscape it doesn't appear as an object. 

I haven't come across this before. Is there a way of changing the colour?

**Comment by nysthi** [comment]
should be ok
I removed all the blocks on use of custom panel
this one was edited with version 1.0.1 (c497b03c, 2020-09-10) MAC


did you try to ungroup ?

**Comment by spectromas** [comment]
Thanks, I found the problem, the panel object was locked.
