### ISSUE TITLE
Feature request: Trigger 02NAGOL to reload .csv

### ISSUE THREAD

**Issue by strangebuttrue** [nysthi/nysthi#328]
A feature I'd be very happy to see on 02NAGOL: Send it a trigger, and it re-loads the .csv that's loaded into it. This way I can edit the values in the file outside Rack and just load them right in to 02NAGOL automatically. Using CV to select a file from a directory would also be interesting, but I don't want to ask for too much, of course...

THANK YOU!

m.l.

**Comment by nysthi** [comment]
the reload trigger will be in version 1.0.18

of course it's an operation that will create a little hiccup in the execution, having to deal with substitution of real time running  piece  of arrays


## 02NAGOL  
*	feature request: add reload trigger

**Comment by strangebuttrue** [comment]
HOORAY, THANK YOU!!!!!!!!!!!
