### ISSUE TITLE
Suggestion for Scala: MIDI Note Mode

### ISSUE THREAD

**Issue by Chaircrusher** [nysthi/nysthi#33]
The way Scala works is fine, as far as it goes but I noticed something: If you split an octave with more than 12 tones but drive it with a note sequencer (or midi input) it does this conversion:

MIDI Note (0...127) -> CV (0..10V) -> Scala (use voltage, quantize to nearest scale note)

This isn't how a lot of synths outside VCV rack work, which is more like:

MIDI Note(0..127) -> Play Nth Note in current scale.  In other words if there's a 15 note scale, notes 0..14 play the first octave, 15..29 play the second octave etc.

The issue is this: if you use the MIDI->CV interface or a sequencer that quantizes to standard scales, you're going to always play the notes that lay closest to equal temperament, and miss the 'in-between' notes.

I'm in no hurry on this, but it doesn't seem like a heavy lift -- add a checkbox in the context menu, and convert voltage into a lookup index in the scale table.

**Comment by nysthi** [comment]
in v0.6.2

**Comment by nysthi** [comment]
@Chaircrusher published, 
please let me know
https://github.com/nysthi/nysthi/releases/tag/v0.6.2
