### ISSUE TITLE
16MIX name issue: the name in the module browser is mix16 although the module is titled 16MIX...

### ISSUE THREAD

**Issue by nesdnuma** [nysthi/nysthi#330]
...so one can miss it when looking for it in the browser.

**Comment by nysthi** [comment]
:D :D !

**Comment by nysthi** [comment]
solved in version 1 0 18 (to be released)

## mix4 mix8 mix16   
* 	visually renamed with real name (before was 4MIX 8MIX and 16MIX)

**Comment by nesdnuma** [comment]
Thanks a lot!
