### ISSUE TITLE
Feature Request: Simpliciter

### ISSUE THREAD

**Issue by dataphreak1001** [nysthi/nysthi#331]
Simpliciter
CV control over the position of the play head. Function as trigger on change.

![image](https://user-images.githubusercontent.com/11288314/103583508-0b384080-4e9d-11eb-9c7f-ad25e09534f9.png)
This bit. Being able to midi map it would be a bonus.

**Comment by nysthi** [comment]
can't be done
because the CV in will win on the free run of the samplehead and there will be no sound at all
