### ISSUE TITLE
Scala Quant ignores Midi Voltage adjust on 11 seperate outs

### ISSUE THREAD

**Issue by fractalgee** [nysthi/nysthi#333]
Hi Antonio,

As already discussed in PM, here is issue of Scala Quant seemingly ignoring what I set the MIDI adjust voltage to on the separate 11 in-outs. For most scala files I use that is +4V. The main (poly) in follows it just fine, however I usually use the separate outs to avoid one more merge and split if not lifting poly cables already ;) . Would be great if you could enable that on all in/outs, as otherwise using both a same time requires some octave shifting for the 11 outs versus the poly one or I set the poly one to 0V and ignore that the MIDI voltage adjust feature even exists. Not so nice.... ;)

**Comment by nysthi** [comment]
found
will be released in V2 asap... :)

(I'll close the issue when released...)

**Comment by fractalgee** [comment]
woohoo, another naught bug bites the dust!!!!!

Looking forward to v2, looking better and better by the day
