### ISSUE TITLE
Master Recorder 2 renders at a variable and low bit rate for MP3 despite 320kbps being selected

### ISSUE THREAD

**Issue by spectromas** [nysthi/nysthi#336]
With MP3 and 320 selected in the right click menu I am getting MP3 files which are really bad quality, they have a variable bit rate but average around 70 kbps. 

Running latest version of Rack on Ubuntu.

**Comment by nysthi** [comment]
I think I nailed it
now is a CBR

will be out in version 2.0.0

anyway there is something wrong in the system, if there is no audio module sometime the behaviour is strange

keep and eye on it when will out !

thanks

I'll close it when the v2 is out 
thank you
