### ISSUE TITLE
Request and bug report for appending samples in Simpliciter

### ISSUE THREAD

**Issue by MaZe6K** [nysthi/nysthi#338]
Hello!
I got a bug and a request for you that I already wrote about on the forum, hope it's ok to put it into one issue.

The bug:
When recording and stopping the recording via the "STOP and append" option in the right click menu, the stereo channels are switched for alle appended samples.

The request:
It would be much more convenient if you didn't have to use the right click menu for the "STOP and append" functionality.
If possible, using a right click on the record button would be much more convenient.

**Comment by nysthi** [comment]
check

**Comment by nysthi** [comment]
the inverted append is debugged

was in Simpliciter and confusing simpler

**Comment by nysthi** [comment]
added the modifier too
press REC with SHIFT key to append the recording session

**Comment by MaZe6K** [comment]
ok then I'm happy with that choice :) thank you!
