### ISSUE TITLE
timed switch or switcher

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#339]
Hey Antonio,

I am looking for a switch that will switch in a certain time frame.
It'may be a bit hard to explain, but here's an example:"
the switch should be opened sometime after one minute, but before 1'30"
So there's a time frame, with a start time and an end time, and the switch chooses when it will open (or close) in that time frame.
It could be a proper switch, or it could send out a trigger. So it's somewhere between Bivio and Janneker. It could of course also do both. 
There should be a reset button. I think a choice between time based and pulse based would be great, just as there are two Jannekers.
I can do something this now with a combination of switches and bernoulli gate, but it's quite hard to set up. And not always working.

Joop

**Comment by nysthi** [comment]
Ciao Joop
As soon as I'l return to program something I'll create it

anto

**Comment by joopvdl** [comment]
That's great!
I was thinking about it, and realized it could be a standalone unit. But it
could also be a third incarnation of Janneker. (And fourth, even, one click
based, the other time based). So you can have scenes.
There's two controls: "not before", and "not after". The device picks a
value between those two.

**Comment by nysthi** [comment]
Hi Joop

can we use an extended version of ELSKER  for this ?
maybe using 2 field more
un probability for the time of the event
and probability about the length of the GATE

**Comment by nysthi** [comment]
@joopvdl 
Hi Joop

can we use an extended version of ELSKER for this ?
maybe using 2 field more
un probability for the time of the event
and probability about the length of the GATE

**Comment by joopvdl** [comment]
I think that would work, yes!

**Comment by nysthi** [comment]
RAEL is in!

**Comment by joopvdl** [comment]
Great!

Op wo 3 nov. 2021 om 10:53 schreef nysthi ***@***.***>:
