### ISSUE TITLE
Will you update modules for  rack v 0.6 ?

### ISSUE THREAD

**Issue by VSpellbound** [nysthi/nysthi#34]
Hi!
PLEASE!! ^_^

**Comment by nysthi** [comment]
??
are already updated...
here
here for example

https://github.com/nysthi/nysthi/releases/download/v0.6.1/NYSTHI.zip

**Comment by VSpellbound** [comment]
ok, sorry
i was looking at
![123](https://user-images.githubusercontent.com/35103326/38172800-5f77b098-35bb-11e8-8035-83fa469c5200.PNG)

https://vcvrack.com/plugins.html

**Comment by VSpellbound** [comment]
thanks for modules!

**Comment by antoniotuzzi** [comment]
I've been ostracized ... ;)
