### ISSUE TITLE
An issue with PolyRec 	 	 	 	

### ISSUE THREAD

**Issue by aflerov** [nysthi/nysthi#340]
Hi! I have some problems with the PolyRec64 plugin in VCV Rack. Yesterday I tried to take multitrack record, using PolyRec64 plugin and all was good, but today PolyRec plugin fell down and stopped working. When I click on a plugin computer asks me where I want to save my record, but after pushing the start button there nothing happens (including timer changes). I asked my friend to try my patch on his computer, and it works well.

I'm using Win10 on ASUS ZenBook 15 UX533FD laptop, i have no external sound card, only built-in and i have the last version of audio driver. I'm trying to save record on internal system SSD in desktop directory.

I tried to reinstall plugin and reinstall VCV Rack program, but it did not help. I also tried to use basic VCV Rec plugin, and it works good. Moreover, i tried to use PolyRec plugin (the purple one), and had the same issue. Is there any way to fix it?

**Comment by nysthi** [comment]
no idea
