### ISSUE TITLE
Simpliciter clicking noise mid-sample

### ISSUE THREAD

**Issue by dwat3r** [nysthi/nysthi#341]
Hi!

First and foremost, thank you for this awesome Simpliciter module.
I'm aware that Simpliciter has clicks, and also that it has the anti-click button.

My use case would be that I have a choir sample, and want to make it a constant ambience.
So the "anti-click button"-introduced fade-in fade-out disrupts the level of audio when playing back a small slice.

![simpli_clicking](https://user-images.githubusercontent.com/6506116/117561601-7e92ce80-b098-11eb-83f2-fe2c6f462822.PNG)
In this example patch, I'm trying to play the sample back and forth with a square lfo, and I've discovered that simpliciter makes a popping sound when the direction changes.

Could this pop somehow be eliminated? 
update:
I've also tried out the internal lfo in square mode, and that also creates a popping sound.

**Comment by dwat3r** [comment]
Update 2: Now I'm thinking that an awesome feature of Simpliciter could be a crossfading looping ability, that the sample/slice would crossfade on itself when the loop restarts or switches to another slice.

Maybe this is too much to ask, so I'm thinking how could I do it with the help of other modules.

**Comment by nysthi** [comment]
sorry, too much efforts needed 

try to use a smoothed square wave
