### ISSUE TITLE
Spectre draw implementation?

### ISSUE THREAD

**Issue by wlaub** [nysthi/nysthi#343]
This isn't really an issue with the nysthi plugin specifically, but I haven't been able to find the source for this plugin, and I'm trying to understand an unusual interaction with my own plugin. I'm working on developing a module that takes a screenshot of the current patch by manually rendering everything to a separate framebuffer, and I find that when Spectre is present, the screenshot gets cropped to about the size of my display. Is Spectre doing anything unusual in its draw function that might account for this behavior?

**Comment by nysthi** [comment]
yes spectre uses offscreen buffers
and not only spectre, IIRC 7seas too and nysthiunpleasuregrapher e something else I don't remember

**Comment by wlaub** [comment]
Ah, so I just need to rebind my framebuffer after drawing the module. That seems to have fixed it. Thanks.
