### ISSUE TITLE
BZ-ENVELOPE and BZ-MAPPER unresponsive to control point x position when using 2 nodes

### ISSUE THREAD

**Issue by nathansnider** [nysthi/nysthi#344]
There seems to be a bug with BZ-ENVELOPE and BZ-MAPPER (v1.0.17) when using two nodes.

Basically, the output of the functions is unresponsive to the x position of the control point. The splines are drawn as expected in the GUI, but the actual output remains the same as if the control point was horizontally centered.

![nysthi_bezier_bug](https://user-images.githubusercontent.com/15080079/125341180-30a07e00-e308-11eb-9279-e5554750b89e.gif)

When using more than 2 nodes, the output seems to match the curve in the GUI.

**Comment by nysthi** [comment]
can't repro on my mac

I have the correct output on both modules with 2 nodes

what is your system ? and pc ?

thanks
