### ISSUE TITLE
Confusing Simpler: RND cv input

### ISSUE THREAD

**Issue by Eurikon** [nysthi/nysthi#346]
Hello my friend, long time :) 

Could you please make the button for RND itself also a cv input for RND on/off (gate high/low) 
(same as grid button)

:D

**Comment by nysthi** [comment]
the RND btn on slice assembler ?
please let me understand !

**Comment by nysthi** [comment]
will be in version 2.0.0b3
*  add a grid on off microbutton (in GRID area, close to GRID title)
*  add a RND on EOC mode for the SLICE sequencer, is valid in GRID MODE is OFF

**Comment by nysthi** [comment]
in confusing simpler, not in Simpliciter

**Comment by nysthi** [comment]
added to simpliciter too

**Comment by Eurikon** [comment]
Hi Antonio, sorry for getting back to you so late, 
my studio is currently in boxes due to construction work in my house :) 

Here is an image to illustrate what i meant: 

![Screenshot 2021-10-30 at 19 43 54](https://user-images.githubusercontent.com/40998416/139543666-cde6c09f-3908-4b55-9cf3-5b0f0a766370.png)

It would be super useful if i can attach a patch cable to the RND button (i guess it is in the slice assembler section?) 
see the red circle in the image,

This way i can control with a gate, to turn on/off the RND function.

Hope this is more understandable now :)

**Comment by Eurikon** [comment]
I like what you have done with the GRID button, splitted the function into a dedicated switch and a dedicated patch input. 

If you could do that for the RND button as well, then it would be perfect and consistent :)  
![Screenshot 2021-11-02 at 22 16 30](https://user-images.githubusercontent.com/40998416/139953262-5f3298fb-e101-4e2d-9a26-4e53da5d7f2e.png)

**Comment by nysthi** [comment]
soved bis
added the extra RND input

in versione 2.0.0.b4

<img width="560" alt="Screenshot 2021-11-03 at 16 24 49" src="https://user-images.githubusercontent.com/33201978/140090624-541fe4b0-75cc-4c5d-935c-b1aba7712a2f.png">

**Comment by Eurikon** [comment]
Grazie mille!!
