### ISSUE TITLE
Feature request: 4HANDS "insert" button

### ISSUE THREAD

**Issue by cosmoproductions** [nysthi/nysthi#348]
Hello!  Could we please get an insert button in 4hands for inserting scenes after the current scene?  Like the insert button in Jooper. 4Hands is amazing and I use it in a lot of patches.  Once I have more than about 5 scenes I find myself wishing I could insert.  Thanks!

**Comment by nysthi** [comment]
added an INSERT button and insert TRIG (will be in version 2.0.0b3

the scene will be inserted BEFORE the current one (like in JOOPER)

if you need to add a scene at end, just use ADD

**Comment by cosmoproductions** [comment]
Amazing tools.  So excited for VCV2.  Thank you!
