### ISSUE TITLE
Will NYSTHI plugins be updated for 0.6.0? My patches are highly dependent on them.

### ISSUE THREAD

**Issue by vogelscheiss** [nysthi/nysthi#35]
Will NYSTHI plugins be updated for 0.6.0? My patches are highly dependent on them.

**Comment by joopvdl** [comment]
they have been updated!

**Comment by vogelscheiss** [comment]
Is that compiled for Mac?

![image](https://user-images.githubusercontent.com/38222883/38524054-5738defa-3c1b-11e8-8640-d04f9a9d42d4.png)

**Comment by nysthi** [comment]
there must be some miscommunication between us: I'm pointing you to the 0.6.2 and you show me the 0.5.13 ?

**Comment by vogelscheiss** [comment]
At any rate, thanks very much, I downloaded the zip file, unzipped it in my plugins folder, restarted VCV Rack, and patches loaded correctly. Problem solved. (Still would be nice if the VCV plugins manager page pointed to the updated file.)

**Comment by nysthi** [comment]
thanks! I'm working on it (to reenter in the plugin manager !)
