### ISSUE TITLE
Scala Quant v2.0.0b3 does not open saved scale on patch open

### ISSUE THREAD

**Issue by fractalgee** [nysthi/nysthi#350]
I always get the default scale (ancient Greek....) as it's the first in the list when I open a patch saved with say Hijaz 8-Tone scala file.  It is in patch.json properly saved, but still opens with the Ancient Greek first in list scala file.

Remove .txt , you will find the scala quant has saved the scale fine. 

[patch.json.txt](https://github.com/nysthi/nysthi/files/7492546/patch.json.txt)

**Comment by nysthi** [comment]
just opened your file and scala is loaded
must be something on your system
maybe a delay opening files, mayb erelated to the new v2 api ?
don't know

<img width="677" alt="Screenshot" src="https://user-images.githubusercontent.com/33201978/140715693-c135d473-38a9-4c9d-b923-24a0980ee388.png">

**Comment by fractalgee** [comment]
Bizarre as I can repro this with this very patch on v2. On v1.1.6 all works as expected so not sure what I would check for any possible issue. Hrmph, the scala file is there, it is in patch file and still nothing.   I shall wait for v2 GA and see if still issue before digging further on my system, which appears sane from what I can tell.....

**Comment by nysthi** [comment]
@fractalgee I think I have seen it
probably happens when reopening a patch that is now a "DEFAULT" patch

is it something related to the new V" implementation

**Comment by nysthi** [comment]
solved
in next release

V2 changed the sequence of initializations

in vers 2.0.0b4

**Comment by fractalgee** [comment]
confirmed fixed, thanks
