### ISSUE TITLE
Quadsimpler : load next - prev sample in folder

### ISSUE THREAD

**Issue by Eurikon** [nysthi/nysthi#352]
Hi Antonio,

is it possible to have 2 small switches in the screens, 
for selecting the next or previous sample in the current folder from where the samples were loaded? 

Because it is very annoying to have to open the file browser everytime and "try" a different sample, this can be quicker! : )
![QD](https://user-images.githubusercontent.com/40998416/141016919-6d860ccb-36f8-4714-98d3-5d03f2a72ae4.png)

**Comment by nysthi** [comment]
will be only for
complex simpler
and slim simpler (slimpler)
