### ISSUE TITLE
Module Browser instant crash with Nysthi Beta3

### ISSUE THREAD

**Issue by Chaircrusher** [nysthi/nysthi#353]
Windows 11
Rack Community built from source git 219bbaf137d5dc70c96bd4206c3f8aad5524a81b
Installed the Nysthi pluging to Rack2/plugins
Load patch
right click to bring up module browser
Instant crash.

EDIT: Ran it under the debugger and get this: 
what():  Failed to load SVG E:/Documents.Kent/Rack2/plugins/NYSTHI/res/ctrls/Tampoco.svg

**Comment by nysthi** [comment]
I've just reinstalled the windows release on my debug rack  same git `219bbaf137d5dc70c96bd4206c3f8aad5524a81b`

and no crashes
and the Tampoco.svg is correctly in the  release res directory

/plugins/NYSTHI/res/ctrls/Tampoco.svg


very strange!


there is only one module using that resource
Dica33

**Comment by nysthi** [comment]
please verify with beta6 (vers 2.0.6)
grazie !

**Comment by Chaircrusher** [comment]
Beta6 looking good!

**Comment by nysthi** [comment]
grazie mille Mr Kent ! @Chaircrusher  <3
