### ISSUE TITLE
bug in musicalbox

### ISSUE THREAD

**Issue by matthleg** [nysthi/nysthi#354]
Hi Antonio,
I just found a new bug in musicalbox:

When you plug the prev or next socket (for the second, third... eighth sample) the speed and octave will depend of the first sample...
for example if the first sample plays reverse (and the knob of the second sample is normal) the second will play also reverse...
I am using win10

And I have still a problem I told you before: when I select a file in a folder, musicalbox will read the first file of the folder and not the one I had choose) so I have to click right and to click current sample. Not a big problem but sometimes in live it is not really practical...

I know it's lot of work all this modules (and also with v2) but if you can have a look I would be happy.
Ciao, have a nice week,
all the best from Brno
Matthieu

**Comment by nysthi** [comment]
bug ! 
really strange !

**Comment by nysthi** [comment]
solved! Almost impossible to find it
that code is so complex and confusing (simpler... :D )

in next beta 4  version
