### ISSUE TITLE
Single - Solo Simpler

### ISSUE THREAD

**Issue by Eurikon** [nysthi/nysthi#355]
Hi Antonio, 
can we have a single file player in the Simpler family? 

![Screenshot 2021-11-16 at 17 14 30](https://user-images.githubusercontent.com/40998416/142074907-0cc6408d-f636-480b-8931-9291b4667ec7.png)

This but then vertical with stereo output.
:)

**Comment by nysthi** [comment]
the complexSimpler is one file player !
<img width="328" alt="Screenshot 2021-11-17 at 12 54 55" src="https://user-images.githubusercontent.com/33201978/142196053-745ccfc7-6b8f-43e8-b274-f4313b660755.png">

**Comment by Eurikon** [comment]
Yes i know, but its so big! :D

**Comment by nysthi** [comment]
AH, ok you want a SLIM simpler ;)

**Comment by Eurikon** [comment]
siiii please!! :D

**Comment by nysthi** [comment]
solved
in next release: SlimSimpler
<img width="532" alt="Screenshot 2021-11-17 at 23 22 07" src="https://user-images.githubusercontent.com/33201978/142292064-ccae4cb1-5df0-46d8-bd22-a6e966d7207b.png">


here 7 in the complexSimpler space

**Comment by Eurikon** [comment]
Whoaaaa! YesYesYes!! Grazie mille :D :D :D

**Comment by nysthi** [comment]
added an expander for complex and slimsimpler to browse/navigate samples in the same directory

<img width="264" alt="Screenshot 2021-11-19 at 17 56 16" src="https://user-images.githubusercontent.com/33201978/142661656-b9256ff3-cd4b-4cd5-8893-04ff8682bc4b.png">

**Comment by Eurikon** [comment]
Ahhhh fantastico! This will be sooo cool :D 

Hope to see the build for latest VCV beta any of this days.

Thanks again Antonio!

**Comment by nysthi** [comment]
solved 
created 2 modules
in next beta 4 version

**Comment by Eurikon** [comment]
Hello! :) 
I been playing with this and having a lot of fun :D

Was wondering if you could do one more thing to it? 

Can you please make it so , that when we turn Start-SA to **negative** from default position, 
it will turn change END of the sample back (to make playback shorter from the end).

![Screenshot 2021-12-08 at 01 45 17](https://user-images.githubusercontent.com/40998416/145128641-9c10e9ae-a0e1-4ab4-a67f-fbbd74a16d34.png)


Thanks :)

**Comment by nysthi** [comment]
a)
as this module uses the same objects of complex simpler
I can add one function more that is visible only for the SLIM
the POT rotating from 0 to -1 will move the END (5 turns )
and rotating from 0 to 1 will move the START (5 turns)

can't have both functionality using a contextual menu

b)
for the snap to ZERO, please open a new feature request

**Comment by Eurikon** [comment]
Understood! That will be fine :)
