### ISSUE TITLE
Simplicitor Right Click Menu Scrolling Issue.

### ISSUE THREAD

**Issue by midnightstepper** [nysthi/nysthi#356]
Hey Antonio

When using the right click menu in Simplicitor I am unable to access the Save Wav option as it drops below the bottom of my screen.

Many thanks

Neville

https://user-images.githubusercontent.com/94717236/142686437-50b854f9-c0ad-46bc-96fe-594ce460283a.mp4

**Comment by nysthi** [comment]
I couldn't check because all my monitor are big
but I shortened the menu using some submenus +
I moved the "file actions" on top of menu

**Comment by nysthi** [comment]
will be in beta4

**Comment by midnightstepper** [comment]
Apologies for the late reply.

Thanks man, I managed to access it by using full screen mode.
