### ISSUE TITLE
ClockableDelay 2.0.0beta4-win some font position/clipping error 

### ISSUE THREAD

**Issue by jpnielsen** [nysthi/nysthi#357]
<img width="151" alt="image" src="https://user-images.githubusercontent.com/27916597/143786318-c8cd1f37-fc63-4eec-b7dc-bcf32e10fddf.png">

sometimes last 0 in 10.000 is cut - sometimes 10.000 is displayed ok.

**Comment by jpnielsen** [comment]
It is not zoom level related. 
It seems that the first time "10.000" is written, it is wrong - and at the next update, it's correct (the middle Clockabledelay was added last)

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/27916597/143787980-474d978d-273c-497e-af63-84b3a890286a.png">

**Comment by nysthi** [comment]
do you have a precise sequence to reproduce it ?
I can't on my mac!

thanks!

**Comment by jpnielsen** [comment]
No, I haven't found out what triggers it yet.

I will let you know.

**Comment by jpnielsen** [comment]
It is different on 199% zoom - here I can see 1 pixel more of the 0, when it bugs out.

<img width="421" alt="image" src="https://user-images.githubusercontent.com/27916597/143800215-f0c18d67-064d-42be-8916-9eb7434a83dc.png">


In windows 11, I use 150% zoom - or else the fonts are too small.
<img width="562" alt="image" src="https://user-images.githubusercontent.com/27916597/143800348-7968eb79-343d-4923-96cf-5e2e879b342b.png">

**Comment by nysthi** [comment]
I've changed the fields for the next version
let's wait version nysthi beta 5

**Comment by nysthi** [comment]
let me know!

**Comment by jpnielsen** [comment]
No error yet.
