### ISSUE TITLE
crash on opening 1.0 file

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#361]
Hey Antonio,

sorry to bother you but when I try to open my Rack 1.0 template into Rack 2.0 it crashes.
I suspect there may be an issue with the Nysthi stuff (because of course the template is full of nysthi), but I am no coder, so I'm not sure.

Here's the last bit of the log file:

[14.722 info src/engine/Module.cpp:167 fromJson] Patch created with NYSTHI v1.0.17, currently using v2.0.6.
[15.112 fatal adapters/standalone.cpp:60 fatalSignalHandler] Fatal signal 11 SIG. Stack trace:
32:  0x0
31:  0x0
30: _C_specific_handler 0x7ffbd7817f60
29: _chkstk 0x7ffbd7e11fb0
28: RtlRaiseException 0x7ffbd7dc1020
27: KiUserExceptionDispatcher 0x7ffbd7e10bd0
26: ZN4rack

If this is caused by something else, please ignore this message.

Thanks for your wonderful modules, Joop

**Comment by nysthi** [comment]
confirmed crash from jooper AND pepper
Andrew changed the sequence of the startup
and I have to change how the string are reassigned on reopening

**Comment by nysthi** [comment]
solved in version 2 0 7

@joopvdl  please test this
https://github.com/nysthi/nysthi/releases/download/v2.0.6/NYSTHI-2.0.7-mac.vcvplugin

and confirm 

thanks

**Comment by joopvdl** [comment]
Yes, it's working fine now on a Mac.
Although I usually work on a pc.

Thanks

**Comment by nysthi** [comment]
thanks for the test
Ok solved in next release 

I'll pass you the link
