### ISSUE TITLE
Master Recorder 2 crashes Rack when stop is clicked if recording mp3

### ISSUE THREAD

**Issue by spectromas** [nysthi/nysthi#363]
When I set Master Recorder 2 to record in mp3 this crashes rack once the stop button is pressed (it freezes for a few seconds and then rack segfaults). The log shows this: 

```
[38.182 fatal adapters/standalone.cpp:60 fatalSignalHandler] Fatal signal 11 SIGSEGMENTATION FAULT. Stack trace:
8: /home/alex/.local/share/VCV/Rack2Pro/Rack() [0x403d8f]
7: /usr/lib/libc.so.6(+0x3cda0) [0x7fb563572da0]
6: /home/alex/.Rack2/plugins/NYSTHI/plugin.so(AnalyzeSamples+0xc5) [0x7fb55630db24]
5: /home/alex/.Rack2/plugins/NYSTHI/plugin.so(+0x7d15a4) [0x7fb5563155a4]
4: /home/alex/.Rack2/plugins/NYSTHI/plugin.so(_ZN10lameHelper6encodeENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_10settings_t+0x41e) [0x7fb556303e7e]
3: /home/alex/.Rack2/plugins/NYSTHI/plugin.so(_Z19recordhelper_threadP18recordhelper_infos+0x904) [0x7fb55609cca4]
2: ./libRack.so(+0x82b740) [0x7fb56409c740]
1: /usr/lib/libpthread.so.0(+0x9259) [0x7fb56351e259]
0: /usr/lib/libc.so.6(clone+0x43) [0x7fb5636345e3]
```

An mp3 file is created but it is a few kb in size and there is also a pcm file created. 

This is with plugin 2.0.10, standalone Rack 2.0.1 on linux.

**Comment by nysthi** [comment]
this must be an old bug from lamemp3 encoder that is back
is unable to encode 320kbs in CBR mode

from version 2 0 11 the 320 is switched in VBR mode (and will be of course variable)

can you please check if the other 5 bitrate are working ?

(128 160 192 224 256)

thanks

**Comment by nysthi** [comment]
(for me are working on MAC)

**Comment by spectromas** [comment]
I tested all the rates and it is only 320 that causes the crash

**Comment by nysthi** [comment]
solved in 2 0 11

**Comment by nysthi** [comment]
solved in
https://github.com/nysthi/nysthi/releases/tag/v2.0.11
