### ISSUE TITLE
Certain Nysthi modules causes crash when loaded using patcher

### ISSUE THREAD

**Issue by Geekachuqt** [nysthi/nysthi#364]
Hi,

I've encountered abug with a subset of your modules.

Using FL Studio Patcher to load a VCVRack 2 FX instance with the Envelope Follower module in it causes a fatal error that crashes the host. 

Error message:

"There was an error sending the settings to the vst plugin "VCV Rack 2 FX". The settings have not been loaded."

The VCVRack patch then fails to load completly, and attempting to remove the VST or change something about it causes it to be **unable to open any other saved patches** until the vcvrack vst instance is restarted.

Steps to reproduce:

Add VCV Rack 2 FX plugin to a patcher instance.
Add Nysthi Envelope Follower to the patch.
Save the patcher preset.
Load the patcher preset.

The crash *only* occurs with Nysthi modules. I can reproduce the bug with the Envelope Follower module, and the Simpliciter module, so it seems to be a recurring bug within a subset of your modules. Per example, the chorus module works fine.

Kind regards,
Robin Hammar

**Comment by nysthi** [comment]
did you try with version 2.0.10 before doing this report ?

https://github.com/nysthi/nysthi/releases/tag/v2.0.10

**Comment by Geekachuqt** [comment]
I have not, because VCVRack is unable to successfully update. It stops the update at around 60%. Which I suppose should be another big report, but I suspect this will fix itself with a simple cleanout of the module package.

**Comment by spectromas** [comment]
Yes, delete the directory, add this one and don't update.

**Comment by Geekachuqt** [comment]
After updating the modules I can now confirm that the bug is fixed.

**Comment by nysthi** [comment]
solved in 2 0 10
