### ISSUE TITLE
Programmer incorrect row settings

### ISSUE THREAD

**Issue by paulpiko** [nysthi/nysthi#366]
Using Rack 2.0.1 Pro standalone.
NYSTHI 2.0.10
Win 10

New patch, add Programmer. Set knobs in rows A-D randomly. Save patch. Exit Rack. Restart Rack. Knobs of A-D are not at the same position as when saved. Reload saved patch. Knobs not in correct position. 

E.g. one knob was at .71 on saving and after reloading was at .07.

**Comment by nysthi** [comment]
this is another victim of new load mode of files in V2

all the developer that have done something a little more creative and nerdy are punished

I had to redo all the loads for all my screens and I have hundreds

thanks for the report

**Comment by nysthi** [comment]
solved
and I've found another bug to

the trigger, don't know why, starts with status at TRUE in V2

this was resetting the current position on load

solved both in 2 0 11

**Comment by paulpiko** [comment]
Many thanks!

**Comment by nysthi** [comment]
solved in
https://github.com/nysthi/nysthi/releases/tag/v2.0.11
