### ISSUE TITLE
"One Sample Playback" For Big Samplers?

### ISSUE THREAD

**Issue by bigggmoustache** [nysthi/nysthi#367]
It's be really nice if there were 'cut all by current' option in the big samplers. Like a hit hat choke on a drum machine (open OR closed), but for every channel. I was trying to patch a solution for this into musicalbox2 and everything I thought of got hairy super quick lol. Then again I'm a noob so if there's a good easy patch solution for it please do share!

Was I supposed to label this? Sorry if I was and I don't see where to edit it in the editor. :[

**Comment by nysthi** [comment]
??

sorry don't understand

maybe you are using musician terms ? don't know

explain better

**Comment by bigggmoustache** [comment]
Sorry. It would be nice if the musicbox had an 'only allow one sample to play back at a time' function, maybe in context menu. The meaning is literal: a function that limits module output to the last played sample. Every time a new sample is played the previous one stops.

**Comment by nysthi** [comment]
ok a special feature req! to check

**Comment by nysthi** [comment]
ok added special EXCLUSIVE PLAY MODE via contextual menu
for MusicalBox and MusicalBox2

will be in version 2  0 12

**Comment by bigggmoustache** [comment]
Is it inappropriate to say thank you here? Thank you very much!!
