### ISSUE TITLE
poly equal division quantizer resets to 12ed2 when loading a patch

### ISSUE THREAD

**Issue by mikaelagrondahl** [nysthi/nysthi#368]
nysthi 2.0.10 in vcv rack 2.0.2 standalone. more v2 shenanigans, i'm afraid...

**Comment by nysthi** [comment]
ouch!, I'll check !

**Comment by nysthi** [comment]
this must be the same bug as in the cage (and yes is due to the change on the startup sequence in v2 rack)

**Comment by nysthi** [comment]
ok done in v2 0 11

**Comment by nysthi** [comment]
solved in
https://github.com/nysthi/nysthi/releases/tag/v2.0.11
