### ISSUE TITLE
Request . Pause recording on Simpliciter.

### ISSUE THREAD

**Issue by GenCode00** [nysthi/nysthi#369]
Please consider implementing Pause Recording button on " Simpliciter "so we could pause recording while selecting new variation of sound we want to add/record to same audio file . there's feature to "append Wav "but you can only add one variation . idea of pause button would be to pause recording and as many times as necessary and add as many variation as we'd like to same audio file.

**Comment by nysthi** [comment]
you can append during record to 
if you press STOP record with commandkey down (or something like that, search in the CHANGELOG

**Comment by nysthi** [comment]
added pause pressing with COMMAND KEY down on the RED button (rec)

when i pause the simpliciter will stay in REC mode but paused with the rec timer stopped , til next click on the same REC button

will be in version 2 0 12
