### ISSUE TITLE
Request/suggestion: change default settings of REC to PLAY crossfade time to 0 seconds for Simpliciter

### ISSUE THREAD

**Issue by Geekachuqt** [nysthi/nysthi#370]
Currently, if you create a new instance of Simpliciter, the default setting for the REC to PLAY crossfade time is set to 1 second.

What this means in practise is that if you plug a clock to the rec input, Simpliciter will *not* sync to the clock due to this crossfade time being a static, unsynced parameter, and gives you no indication as to why it doesn't.

I had a tough time learning how this module works due to this, as my expected result when patching a clock signal to the rec button would be that it would record and loop a time-synced part of the incoming audio, but the actual result is that it will continuously go out of sync with the clock signal as you record.

After hours of digging around in parameters I finally discovered this parameter, and setting it to 0 seconds yielded the expected looping behaviour of the module.

Having said that: your modules work just phenomenally well, and are super interesting. Thank you so much for your contribution!

**Comment by nysthi** [comment]
I'll check it

**Comment by nysthi** [comment]
ok
from next version 2 0 12 by default will be 0 secs
