### ISSUE TITLE
specific bug mapping musicalbox "octave knobs" with midicat

### ISSUE THREAD

**Issue by matthleg** [nysthi/nysthi#371]
Hi,
I found a specific bug (in v2) and I am not sure it is from you or from Stoermelder...
When I map the octave knobs of musical box with midi-cat ( in mode pick-up jump) it doesn't work...
But it is working for all the other knobs, and it is working if it isn't with the mode pick-up jump...

Strange.
I am using win11.
Have a nice day
and thanks again for your amazing collection.
Matthieu

**Comment by nysthi** [comment]
you trust me a lot... :D

**Comment by nysthi** [comment]
is not a bug from my side
that parameter is moved using a SNAPPED knob with, I think, 13 positions (from -6 V to +6V), 
maybe there is something more you need to do ?
