### ISSUE TITLE
Simpliciter reproducible crash

### ISSUE THREAD

**Issue by Geekachuqt** [nysthi/nysthi#372]
Hi Nysthi,

Sorry to be here again, but I've encountered a reproducible crash bug with Simpliciter.

When using it inside of the VCV Rack 2 Pro VST FX, the following conditions will cause a reproducible crash:

Simplcitier receives a Rec Trig while **the VST window is hidden/closed.**, ergo - while the plugin is currently not being rendered.

This seems to cause a non-fatal crash in simpliciter, which in turn triggers some form of failsafe in the FL Studio VST wrapper which disables the whole Rack VST instance. All modules in VCV Rack are still interactable, but no settings change upon interacting with them (example: changing the playback speed of Simpliciter does **not** change the number written below the dial). Attempting to remove the VST then triggers a fatal crash that brings down the DAW.

This crash is reproducible using the latest version of FL Studio, with the latest version of VCV Rack, and with version 2.0.10 (edit: reproduced with 2.0.11) of NYSTHI.

Hope this helps somehow, and thank you for your wonderful work.

**Comment by nysthi** [comment]
thanks for this report

as you know, I don't own a DAW and or the VST part so it's impossible to verify it

but I guess is related to a status where is assumend that some UI is present

**Comment by nysthi** [comment]
I think I've found a possible problem

let' wait for next release

2 0 12
