### ISSUE TITLE
Request: End of cycle/phrase output for SAM

### ISSUE THREAD

**Issue by puutelias** [nysthi/nysthi#374]
I think it would be great to have an output that sends a trigger either once an entered phrase ends or restarts. I found that by sending SAM through a vocoder with a low-frequency carrier, I could get a unique rhythm, but I couldn't quite match it to a clock, but I would be able to use an end of cycle trigger as a base clock in a patch.

Thanks for all the modules!

**Comment by nysthi** [comment]
will be in version 2 0 12

**Comment by nysthi** [comment]
please don't close
I have to do it
after the release, thanks!
