### ISSUE TITLE
Programmer recalls wrong parameter values for the knobs!

### ISSUE THREAD

**Issue by jaffasplaffa** [nysthi/nysthi#375]
Hey :) 

I was just playing around with Programmer in VCV2 Pro and I noticed that when I reopen a patch the knobs has the wrong values.

For example if I set a value of 1.6, when I reopen the patch the value is 0.16. So it kind of divides by 10, moves the comma one number to the left.

I'd also like to suggest adding higher precision for the knobs, so you can set more decimals. I am using it so set slicepoints for the Lomas sampler and higher precision would be most welcome as slice points has to be precise :) 

Best wishes, 
Jakob

**Comment by nysthi** [comment]
please check the other open issues
this was already covered

**Comment by nysthi** [comment]
in 2 0 12

I don't understand the bigger precision stuff: just click with right mouse btn

and please  use my samplers ;)

**Comment by nysthi** [comment]
it's the same bug 

corrected in 2 0 12

**Comment by nysthi** [comment]
btw I was wrong
this debug is already out in version 2 0 11 (2 0 11 is not on the LIBRARY, is only distributed by me)

here
https://github.com/nysthi/nysthi/releases/tag/v2.0.11

**Comment by jaffasplaffa** [comment]
Hey :) 

Thanks, this one keeps the right values, thank you. 

But there is still something going on with the parameters. 

If I put in a value of 0.3125, it sets the value 3.12. But thats workable, it just multiplies the value you put in with 10. But yeah, would still be lovely with higher resolution, so you can set more precise values ;)

**Comment by nysthi** [comment]
reopening because there is a "visual" bug (in the resolution)
(it's only the representation that is clipped)

**Comment by nysthi** [comment]
solved in next version 2 0 12
