### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jpnielsen** [nysthi/nysthi#376]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/27916597/146654418-1c50b866-f57c-4883-8304-27e54525621b.png">

Please add channel Z = beam intensity to ETCHASKETCHOSCOPE

https://github.com/nixiebunny/SCTVcode

**Comment by nysthi** [comment]
I think I've implemented but I removed it because was too expensive  (larger segments in front and/or beam intensity)

but I'll recheck

**Comment by nysthi** [comment]
added history in the Beam size (same lenght as X and Y)
now the CV input can act as Z channel
the formula is VALUE + IN:_CV * VCA 
the history is active by default, and can be excluded via contextual menu
in version 2 0 12
