### ISSUE TITLE
the cage does not remember the scale

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#377]
I am using the Cage as a sort of programmer. Maybe it's not exactly what it's meant to do, but i like it, and it has some advantages. I use it in combination with Stroke from Stoermelder to be able to use my keyboard to switch settings on a Jooper (of course, Jooper to the rescue always)
So I programmed it to have 12 steps, from 0 to 10V. 
But it does not remember the settings in the latest version (it did work excellently before)
Can you check if this is the case?
Also, what does the number field on the bottom do?

As always, thank you very much, Joop

**Comment by nysthi** [comment]
yes I know
it's a problem of the V2 rack 
I corrected it I think in version 2 0 11 (release on github, not in library)

let me know

**Comment by nysthi** [comment]
the bottom is closing of the cage...

if you have 12 semitones you need to trap it between 13 values... (are the limits top bottom)

**Comment by joopvdl** [comment]
I see.
I have 2 0 11 installed, but it still forgets the settings.

**Comment by nysthi** [comment]
> I have 2 0 11 installed, but it still forgets the settings.

I see
I'll check again

**Comment by nysthi** [comment]
you are right
the V2 Rack broke many of my modules because of the creation sequence change

will be ok in version 2 0 12
