### ISSUE TITLE
Polyphonic LPG Bypass does NOT work

### ISSUE THREAD

**Issue by Petervos2018** [nysthi/nysthi#378]
![afbeelding](https://user-images.githubusercontent.com/46076474/146842205-86cb02aa-68cf-4bf2-a361-03dfc63eea59.png)

;)

Greetings Peter.

Windows 10 Rack V2 2.0.3. NYSTHI 2.0.10

**Comment by nysthi** [comment]
ouch!

**Comment by nysthi** [comment]
will be in 2 0 12
