### ISSUE TITLE
Request for mverb module source code

### ISSUE THREAD

**Issue by falkTX** [nysthi/nysthi#379]
Hi there.

Your module collection includes a port of [mverb](https://github.com/martineastwood/mverb/), which is originally licensed as GPLv3.
Per the terms of the license, derivatives works must have their source code available under the same license upon request.

So here is that request :)

**Comment by nysthi** [comment]
et voila ;)

this is the full m_verb ported in template format
[nysthi_mverb_original.h.zip](https://github.com/nysthi/nysthi/files/7793255/nysthi_mverb_original.h.zip)

**Comment by falkTX** [comment]
I am sorry, but this is not it..

When you use GPL source code on a project, such project must be licensed as GPL as well.
You cannot just take GPL source, put it in a closed-source project, and pretend everything is fine.

GNU (creates of the GPL) has a dedicated section about this https://www.gnu.org/licenses/gpl-faq.en.html#GPLInProprietarySystem

> A system incorporating a GPL-covered program is an extended version of that program. The GPL says that any extended version of the program must be released under the GPL if it is released at all
> ...
> if the two programs are combined so that they become effectively two parts of one program, then you can't treat them as two separate programs. So the GPL has to cover the whole thing

**Comment by falkTX** [comment]
Just noticed you also make use of audiofile library, which being LGPL makes it problematic to use as static library in proprietary projects.

https://softwareengineering.stackexchange.com/questions/179084/is-there-a-modified-lgpl-license-that-allows-static-linking has a whole discussion about it, so you don't read just license text.

As someone that works daily on open-source, GPL-licensed software, it hurts to see others taking GPL-licensed software and reusing them in proprietary products.
You cannot do this under the terms of the license.

**Comment by nysthi** [comment]
I'm not using any audiofile library, that is a relic
removed the license 


and I'll remove the mverb and connected from the library (twisted mVerb) from my release

**Comment by falkTX** [comment]
It has been more than 2 weeks now, situation is still unresolved.
do you have plans to rectify this? I saw the ihtsyn repo some days ago, but now it is private or deleted... so we are back to the beginning.

**Comment by patman023** [comment]
> so we are back to the beginning.

It may be private/deleted for other reasons (potentially some outside of Antonio's control, especially given A.Belt's severe control issues - don't quote me, but I seem to recall some BS popping up in the last 3-4 years about forbidding splitting modules off from a main plugin) , but is the code in question re-incorporated into mainline NYSTHI? Has everything reverted to 2021/12/29?

Maybe there's issues, developments, or discussions we are not privy to, perhaps with regards to the other people mentioned and/or tagged in this post from Antonio on the main forum? https://community.vcvrack.com/t/nysthi-v2-0-14-release/625/561

Also, he's one singular human being who has been coding stuff in his spare time. He isn't a corporation, nor is he deriving any income or profit from the project. He's even refused donation offers. I'm not saying that an issue does not exist at all here; just saying that you and the others who sure *seem* to be brigading the guy, need to have a little thing called patience.

**Comment by mxmilkiib** [comment]
I've only seen public evidence of two people bringing this entire issue issue up, dreamer on the forum and falktx here, so describe that as "brigading" sure seems like unfair exaggeration (maybe some patience over choosing words would help). The GPL violation situation was resolved but then became unresolved again. It has been more than 72 hours since the new repo was removed, and more than a fortnight since the previous comment here, so I'd think it was fair by now to ask what's happening, given there hasn't been a statement and no-one else has actually asked since then.

**Comment by patman023** [comment]
@mxmilkiib 
First off, I'm Neurodivergent AND deal with varying cognitive impairment, and as such my word choices are often affected by where my head is at in any given moment. I can assure you that I took damn near a half hour to word my entire comment. Even if I hadn't, that wouldn't completely invalidate my overall point. 

Second, and more to the subject, this is a part time passion project for Antonio/@nysthi. Yes, I absolutely understand that breaching the terms of an open source license is a big faux pas that deserves to be rectified, whether it was intentional or otherwise. All I'm conveying here, is that something may be going on in the guy's life that takes massive priority over the project, or that there may be other circumstances at play that we're not privy to. He doesn't owe us an hour by hour accounting of his whereabouts on every platform. Just because it's been a while since things happened here, doesn't mean he hasn't been active elsewhere.

Yes it needs to be addressed, but not with the vigor one pursues someone making bank off a breach.

**Comment by mxmilkiib** [comment]
I'm similar and spend similar times. No one is asking for hourly accounting, and if one can see someone posting online then it's appropriate to try communicating with them. I just don't think the timing and tone of the post you're responding to is vigorous. You and I are the only ones being somewhat vigorous at the moment. I just wanted to step in to comment as I thought your descriptions of the situation were painting an unfair narrative.

**Comment by falkTX** [comment]
We can calm down about the whole situation, I only meant to ask what is going on. I think asking for updates after 2 weeks is not a lot of pressure... forgive me if that is the case.

The whole situation just seems very weird that's all.
There was a GPL violation for 5 years, and no one did anything about it, not even Andrew who by his own words likes and understands all these licensing stuff.
And as I write this, the GPL license for [nysthi modules hosted by VCV](https://library.vcvrack.com/NYSTHI/MVerb) still continues to be in violation, which can be a liability for the company. This seems quite messed up to me...

Note, I am not making demands here, just asking. Can quite understand these things take time, it is why I waited 2 weeks to ask for an update.
The fact that Antonio releases all his work for free (gratis) is unrelated to the topic, the seriousness of the violation is the same be it commercial or not. In fact, he could have released it commercially just fine, as long as the source code was still available (GPL + commercial is a completely valid thing, commercial doesnt imply closed-source)

Will still wait patiently for any changes on the situation, but I am a bit appalled for how this goes on for so long..

**Comment by falkTX** [comment]
Hi, it has been 2 weeks since my last post, and 1 month since the original post.
mverb is removed from the latest builds, but sadly it is now gone overall too.

There is a copy of when mverb/ihtsyn was public at https://github.com/CardinalModules/ihtsyn
But are we allowed to use this? License-wise it is fine as far as I can tell, but regardless of that @nysthi might still dislike and not approve of it.

Would be great to know how to continue.
@martineastwood the author of mverb has been pretty much been absent from github, so I am not sure if you should count on an answer/reply to your query.

**Comment by nysthi** [comment]
@falkTX yes please, use it, I opened again to public the repo. (I was waiting for the approval of my  version 2 0 15 in the lib, but the team seems very overwhelmed)

**Comment by falkTX** [comment]
> @falkTX yes please, use it, I opened again to public the repo. (I was waiting for the approval of my version 2 0 15 in the lib, but the team seems very overwhelmed)

that is very appreciated, thank you.
can I assume the panels/artwork to be licensed in the same way, or do you have a custom license for those?

**Comment by nysthi** [comment]
knobs are from the vcvRack (or maybe  I've reduced in size) (so don't know ... )
back panels are mine, with changed tonality

**Comment by falkTX** [comment]
> back panels are mine, with changed tonality

yes, that is why I ask you the license you set for them.
it can be either the same as in the repo (GPLv3+), a CC one, or custom. knowing the license terms is crucial, so we know what is allowed and what is not. like modifications, redistribution, etc

sorry to insist so much on this, but licenses are a very important thing, and a blocker for packaging and redistribution in linux distributions

**Comment by nysthi** [comment]
let's say that  are GPLv3+

**Comment by falkTX** [comment]
haha, alright, thanks a lot!

**Comment by martineastwood** [comment]
If it helps, I'm happy for you to use mverb under a different licence. I've had a number of requests recently about changing the licence to something less restrictive so it's something that will likely change in the near future. At this stage, do you have any thoughts on what licence would be easier for you to work with?

**Comment by nysthi** [comment]
@martineastwood no problem now
I was that I was distributing some derivative work starting from your mverb in a closed (FREE) plugin system

I've now a different distribution available containing those derivatives (here https://github.com/nysthi/ihtsyn ) complete with the source code

thank you very much for your efforts !
