### ISSUE TITLE
PROGRAMMER does not save knob positions in v2

### ISSUE THREAD

**Issue by terrytheplatypus** [nysthi/nysthi#380]
when closing and reopening a patch using programmer, none of the knob positions are saved, though the gate switches and ratchets are saved.

**Comment by nysthi** [comment]
are you using version 2 0 13 ?

**Comment by terrytheplatypus** [comment]
no i was using 2.0.10 because that was what was on the library. i'll try 2.0.13

**Comment by terrytheplatypus** [comment]
worked fine in 2.0.13
