### ISSUE TITLE
Deleting Janneker not working as expected

### ISSUE THREAD

**Issue by SmaOne** [nysthi/nysthi#383]
Hi,

Seems to me that deleting Janneker by hovering over with the cursor and hitting <backspace/delete> button isn’t working as expected.

Hovering over + <delete> button: not working
Select module with mouse (turns red) + <backspace/delete>: works

Testing several other Nysthi modules (about twenty) revealed that no other modules seem to be affected.

(MacOS 11.6.2 (BigSur); MacMini M1 2020, 16GB; RackPro-2.0.5; Janneker: 2.0.10)

**Comment by nysthi** [comment]
solved in 2 0 15
