### ISSUE TITLE
Simpliciter Multi Feature Request

### ISSUE THREAD

**Issue by blackearth2014** [nysthi/nysthi#385]
Is it possible to drag and drop a folder worth of lengthy samples on Simpliciter's  sample wave graph area and auto generate slices based off the sample file titles.

For example, if I have like 5 samples ranging in length from 1sec to 8sec, I want to drag and drop them and each slice is the generate by the length of the sample.

**Comment by nysthi** [comment]
that would be possibile
but I have no control of the memory the users have in their computer

a sample in memory occupy "current sample rate * seconds * 8 bytes"

so if you load a 60 secs sample at 48kHx, you need 23Mb

if you load a directory with 10 files of 1 hours STEREO files you need 
10 x 60 x 60 x 2 x 8 x 48000 bytes = 26GB of memory


if you can live with the crashes you are going to create, I can implement it... :)

**Comment by nysthi** [comment]
and remember now files can be multitrack 
1 hour 8 tracks
is
60 x 60 x 8 x 8 x 48000 = 10 Gb

**Comment by nysthi** [comment]
verifying it I've just rediscovered that you can already import "BUNCH of files in APPEND mode"  
if you maintain the COMMAND-KEY down

(ok it's missing the "slice" generation part, but it's a good start !

**Comment by blackearth2014** [comment]
Memory issues should be in the hands of the user. If you implement powerful
features then user should be using a powerful computer. Don't let anything
stop you even if it's for a few users.

**Comment by nysthi** [comment]
will be in version 2 0 15

**Comment by nysthi** [comment]
The import will be by append, by default
