### ISSUE TITLE
First 3 clocks are missed by SQUONK (no triggers out)

### ISSUE THREAD

**Issue by Petervos2018** [nysthi/nysthi#386]
As seen here, after a reload/restart of VCV the first 3 clocks are not made into triggers.
When I stop and start the clock again, all is well, so its only when you load/start the project the first time.

![afbeelding](https://user-images.githubusercontent.com/46076474/148649244-6ebde07d-5b75-4124-b678-bb8d1d7e9635.png)

**Comment by nysthi** [comment]
this is not a bug
it's the nature of the inner sync: needs at least 3 pulse to have the inner clock in sync with external clock (for the ratcheting)

anyway, I've added a special case for the start: reuse the incoming clock if the inner is still in "evaluating mode"

will be in 2 0 15

**Comment by Petervos2018** [comment]
I somehow knew you once said something like this, but now I'm sure. Is it not possible f.i. for Squonk to get the bpm from the clock bpm out ? Just a thought ;)
Thanks for the "reuse incoming clock if etc" that will fix the restart issue as far as I can see.

Thanks for all your great modules,

Peter.

**Comment by nysthi** [comment]
> Is it not possible f.i. for Squonk to get the bpm from the clock bpm out ? Just a thought ;)

no... will be impossibile: I have a completely separated clocking system for SQUONK 

and it's too old (2017) and big (5k lines) to change it 
💪 

good luck ! 
I love the squonk

probably one day I'll do another version , in horizontal
but should something different from the Programmer and the Squonk !

**Comment by Petervos2018** [comment]
Hi Antonio,

just to let you know that 2.0.15 still misses the first 3 clocks, but I don't mind, I know it does, so I first start the seq, wait a moment and stop, reset, and........... now the fun begins... ;)

Thanks again for all your work and modules,

greetings Peter.
