### ISSUE TITLE
Poly envelopes: mono trigger -> poly out

### ISSUE THREAD

**Issue by BlamesJake** [nysthi/nysthi#387]
Poly DAHD, ADSR and AD get a monophonic output when a single trigger is used. There are two requests in one:

- **Output polyphonic VCA when a poly VCA input is used**. The number of VCA channels is determined by the VCA IN when that number is less than the number of input triggers. **Same behaviour with CV inputs**. 
(Would also be nice to be able to merge them as an option in the menu but may be overkilling)

- Poly AD could have a right-click menu option to select the number of channels (same as VCV Merge module). When the selected option is greater than 1, last channel is copied to the non triggered ones. A more simple approach could be just adding a paraphonic option in the menu to restric input to 1 gate.

I have not checked TZEN and DX7 but would be nice they also behave in a similar manner.

**Comment by nysthi** [comment]
Poly DAHD, and Poly ADSR 

corrected the count of the dual VCAs

the number in output will be the minor between  "incoming VCA signals" and "count of trigs"

**Comment by nysthi** [comment]
## Poly DelayAttackHoldDecay (POLY  DAHD)
## Poly AttackDecaySustainRelease (POLY ADSR)
* correct number of VCA1 and VCA2 input (can be poly and in different number from GATERs and/or TRIGGERs)

## Poly AttackDecay (POLY AD)
* added menu for polyphony
 now polyphony is the given by the minimum between POLY TRIGGERS and polyphony from Menu
* added paraphonic mode: polyphony is always decided by the poly menu, but the output will be always FROM inner AD 1

**Comment by nysthi** [comment]
will be in 2 0 15
