### ISSUE TITLE
VCV v2: NYSTHI Programmer does not save the position of the knobs. Not even in the preset or template.

### ISSUE THREAD

**Issue by faustoserone** [nysthi/nysthi#389]
Hi Antonio.

When I save a sequence and then reload it, I find Programmer initialized at default. In VCV Rack V1 it's work perfectly.

Can you take a look?

Many Thanks

Fausto Serone

**Comment by nysthi** [comment]
Ciao Fausto

devi usare una versione superiore alla  2 0 12

qui trovi la 2 0 14
https://github.com/nysthi/nysthi/releases/tag/v2.0.14
