### ISSUE TITLE
Poly "Envelope Out" on Multi-Envelope-Modules like 4 AT SUS REL and 8 ATTACK DECAY

### ISSUE THREAD

**Issue by mosesve** [nysthi/nysthi#390]
Hey Synthi!

As a Feature Request I would love to see a polyphonic Envelope out on your Multi-Envelope Modules.

Thanks in Advance!

mo

**Comment by nysthi** [comment]
oki doki

**Comment by nysthi** [comment]
fist done
## 8 AttackDecay
* added a menu command to transform first channel in poly 8 AD

**Comment by nysthi** [comment]
solved

## 8 AttackDecay
* added a menu command to transform first channel in poly 8 AD

## 4 Attack(Sustain) Release - 8 Attack(Sustain) Release- 16 Attack(Sustain) Release
* added a menu command to transform first channel in poly 4-8-116 ASR


will be in 2 0 15
