### ISSUE TITLE
Dual Pulser "mod" slider does nothing with no input patched

### ISSUE THREAD

**Issue by OracleToes** [nysthi/nysthi#391]
I am following along with this video https://youtu.be/qRu6hcMISfw?t=444
He adjusts the modulation slider here with no CV patched into the input, and it adjust the output of the pulser.
However when ever I adjust the slider with nothing patched in the "mod" input, nothing happens.
When there is CV patched into the mod input, the slider works as expected.
I'm using VCV Rack 2, and it looks like Omri in the video is using an older version of VCV and NYSTHI plugins, so I assume this is a bug.

**Comment by nysthi** [comment]
works correctly
the left slider is the VCA for controlling the modulation input  that will be summed to the current timing (right slider)

the right slider is the distance in seconds between pulses
