### ISSUE TITLE
Poly Equal Division Quantizer doesn't save settings

### ISSUE THREAD

**Issue by daard23** [nysthi/nysthi#392]
Hi Antonio!
Minor issue:
Poly Equal Division Quantizer doesn't save settings. If you open a saved project up it will revert back to 12 TET/EDO.
I'm not sure how many people use this module (I think most of us use Poly Scala), so it can probably go in the "when you get around to it" file.
Thanks for all the hard work and the cool modules!

**Comment by nysthi** [comment]
thank you for the report!
this must be another victim of the changes done in the load of the modules in V2...

**Comment by nysthi** [comment]
@daard23  are you using version 2 0 15 ?

it's only distributed by  me !
https://github.com/nysthi/nysthi/releases/tag/v2.0.15

I remember the bug in  previous versions (2 0 12)

**Comment by daard23** [comment]
I'm using the one in the library (2.0.10). If it's fixed in 2.0.15 then go ahead and close the ticket.

**Comment by nysthi** [comment]
checked: solved 100% since 2 01 3

**Comment by daard23** [comment]
Sorry to waste your time on that one.
Thanks for looking into it!

**Comment by nysthi** [comment]
no problema!

better always to report! you did correctly ! 

thank you 
Antonio
