### ISSUE TITLE
.WAV files not shown in the open file dilaog box

### ISSUE THREAD

**Issue by jeanmartin13** [nysthi/nysthi#397]
I've been trying the Musicalbox, Musicalbox 2 and Sussudio modules and there is an annoying issue : if the sound file is .WAV format it doens't show in the dialog box that opens when you want to laod a sample. I you change .WAV by .wav (upper to lower case), then the sound file appears. Had the same issue with Voxglitch Samplerx8.

**Comment by nysthi** [comment]
are you using windows ?
I can't repro on MAC

**Comment by jeanmartin13** [comment]
That would explain why .wav files are seen and not .WAV ?

**Comment by nysthi** [comment]
my filter for the WAV file is this
`WAV files:wav;WAV`
means
set as title "WAV files:"
and filter extensions "wav" and "WAV"

**Comment by nysthi** [comment]
Ah, ok, the inverse
considers the first entry

**Comment by jeanmartin13** [comment]
In fact it's more tricky, if I have WAV and wav files in the folder, it doesn't **display** the WAV files but it loads wav and WAV. That means that if I have only WAV files in the folder it displays a empty dialog. But if there is a wav in the folder, it is shown in the dialog so I can select it and it loads both WAV and wav even if WAV are not displayed.
