### ISSUE TITLE
Simpliciter does not save wav file path and filename in Rack2 Pro 2.1.0

### ISSUE THREAD

**Issue by fractalgee** [nysthi/nysthi#398]
As I sent via facebook here is the issue for that:

Simpliciter does not save wav file path and filename in Rack2 Pro 2.1.0 MacOS 11.6.4

The only thing it saves in the patch file is: 

``` "m_original_file_name": "" ```

 so it comes up again on loading patch next time as no WAV/AIFF loaded.

**Comment by nysthi** [comment]
I've updated the VCV source code to 2.1.0
and I'm unable to reproduce it

I can save a simpliciter or any other sampler where I've loaded file and reopen the file correctly ?

are you recording ? if yes, than you are destroying the union to the file

let me know!

**Comment by fractalgee** [comment]
very bizarre, just retested with the Simnpliciter Multi 2.0.15 on Rack 2.1.0 and now do see WAV fike in the patch file. So I must have played with recording (overdubbing) when I saw issue, though not sure anymore. Anyhow, Close this one, If I find a reliable way to make it happen then I will let you know

**Comment by nysthi** [comment]
:+1:
love simple bugs :D
