### ISSUE TITLE
Plugins Don't Appear in Menu

### ISSUE THREAD

**Issue by Cordoha** [nysthi/nysthi#4]
Plugins don't appear in menu with Rack 0.5.0 in Ubuntu.

**Comment by MarcBoule** [comment]
Same here.

**Comment by KottV** [comment]
Confirm on openSUSE TW g++ 7.2.1 glibc 2.26

[warning] Failed to load library ./plugins/nysthi/plugin.so: ./plugins/nysthi/plugin.so: undefined symbol: _ZN4rack11assetPluginEPNS_6PluginESs

**Comment by nysthi** [comment]
I have to compile for Fedora 23, give me a couple of hours...

**Comment by nysthi** [comment]
(I hate all those linux versions... )

**Comment by MarcBoule** [comment]
Not sure if the new NYSTHI v0.5.1 was meant to solve this issue, but I'm getting the same error as reported by KottV when Rack tries to load the plugin: 
`[warning] Failed to load library ./plugins/nysthi/plugin.so: ./plugins/nysthi/plugin.so: undefined symbol: _ZN4rack11assetPluginEPNS_6PluginESs`
(Ubuntu 17.10, Rack dev latest build)

**Comment by antoniotuzzi** [comment]
Sorry MArc
no I need to do a special version fro new Linux platform
I was trying to compile on my fedora but I had some problems
I 'll let yo know when ready !

**Comment by nysthi** [comment]
@MarcBoule @Cordoha @KottV 
please try the 
[fedora 26 release ...](https://github.com/nysthi/nysthi/releases/download/v0.5.1/fedora26_ubuntu_1604_v0_5_1.zip)

**Comment by MarcBoule** [comment]
YAY! It works now, thank you so much Antonio! Your mverb was highly recommended in my FB question/poll a few days ago regarding reverbs, and I'm going to start experimenting with it right now :-) Developers like yourself are making this superb platform really fun to explore  :+1:

**Comment by nysthi** [comment]
as I was developing on a Fedora emulator and the graphic was not ok.
I need just a confirma action from you:
if you put my modules on a rack, you see them correctly ? 
Because I'm seeing like this : 

![screen shot 2017-11-26 at 17 54 40](https://user-images.githubusercontent.com/33201978/33244310-4a0d5222-d2f5-11e7-92fc-0da21d65181f.png)

**Comment by MarcBoule** [comment]
I'm seeing the modules correctly. I created one of each in a Rack and they all look as intended (and definitely not like the ones in your picture). You really have a nice set of modules by the way, great job! Cheers!

**Comment by nysthi** [comment]
thank you sir, I consider it closed...
