### ISSUE TITLE
Master Recorder 2 - Disable VU lights?

### ISSUE THREAD

**Issue by GrayCatMusic** [nysthi/nysthi#400]
Greetings Antonio! I'm wondering if it's possible to implement a feature to disable the VU flashing lights on Master Recorder 2. The lights flash rather quickly and make it difficult for me to use with my sensory issues. I've mostly been using your other (now deprecated?) master recorder in my template patch for a while. Grazie mille! <3

**Comment by nysthi** [comment]
done
will be in 2.1.16 version

**Comment by GrayCatMusic** [comment]
you're the best, antonio! thank you!

**Comment by nysthi** [comment]
I reopen it
because I'll close when you'll receive it :D (I have to check!)

**Comment by GrayCatMusic** [comment]
My mistake! I'm still learning my way around github.

**Comment by nysthi** [comment]
is out
