### ISSUE TITLE
Increase maximum delay time in NYECHO

### ISSUE THREAD

**Issue by rchrd2** [nysthi/nysthi#401]
Hi. I am looking for extremely long delay times in a tape delay plugin. Eg I wish I could do 10 minutes or maybe even 20 minutes. The NYECHO plugin gets me very close with a delay that's almost 1 minute long. I wish I could drag the knob further. Is it possible for you to add the ability to change the speed from 0.10 cm/s to 0.01 cm/s? Thank you.

**Comment by nysthi** [comment]
20 minutes stereo at 88k2 Hz are 830Mb of memory

I could increase, but would be a crazy use of the memory :)

**Comment by rchrd2** [comment]
That's fine with me. My computer has 64 GB of memory. 

I don't want to make this request more complicated, but I should also note that I am only using 1 channel. Does the plugin have the option to run in mono mode? Would that save some memory as well?

Thanks you for your consideration.

**Comment by nysthi** [comment]
egoiste ! :D 

no, can't run in mono mode (currently)

**Comment by rchrd2** [comment]
Fair enough. Mono mode is not a requirement.

Stereo mode with extended time would work great for me. I am hoping to use it for performance where I play for some time, and then start dueting with my previous self once the loop starts.

**Comment by rchrd2** [comment]
@nysthi So what do you think? Would you be willing to add this feature? 🙏

**Comment by nysthi** [comment]
by tomorrow if you send me €1000
in 2 days €500
in 7 days €200

I guess you want to wait for the 100 days option... ;)

**Comment by nysthi** [comment]
is in (but I think I'll remove the distorsor/saturation part) or I'll put a switch

**Comment by nysthi** [comment]
added x10 switch
now max delay is 20 minutes stereo
