### ISSUE TITLE
POLYREC only consolidates in stereo pairs

### ISSUE THREAD

**Issue by MaZe6K** [nysthi/nysthi#402]
Hi!

When using POLYREC polyphonic recorder with "consolidate tracks after recording" I was expecting it to leave out every empty track. But it seems to only check for emptiness in stereo pairs, so when for example there is something on track 3 but track 4 is empty, track 4 is still saved as a file or track. Only when both channels of a pair (1-2, 3-4, etc.) are empty both get deleted.

Other than that I'm very happy with POLYREC and it's low impact on resources.

**Comment by nysthi** [comment]
are you sure you are not in "stereo pair mode" ?

**Comment by nysthi** [comment]
I re-tested it and is working regular

I have channel 1 3 and 8 with signals in a merge

normally records a 8 tracks wave
in consolidate a 3 track wave
if in stereo pair
saves 2 wave files with 2 channels

I'm on mac

**Comment by nysthi** [comment]
no
are you on ? what system ?  version 2 0 15 ?

I'm saving mono wave files correctly, with directory or not

my settings (8 chan arriving but 5 discarded)

<img width="394" alt="Screenshot 2022-04-05 at 19 44 49" src="https://user-images.githubusercontent.com/33201978/161817839-fa35dfd5-f47f-4d52-9eab-c86dd392b448.png">

**Comment by MaZe6K** [comment]
strange... I use the same settings. I have just checked again and it also does it when saving everything to one multitrack wav file, so it behaves the same in both SAFE FORMAT modes.

I'm on Windows 10 using 2.0.15 in VCV Rack Pro 2.0.6

I am using it inside the VST at the moment, but it did the same thing in standalone.

**Comment by MaZe6K** [comment]
these are my settings:
![polyrec settings](https://user-images.githubusercontent.com/50169405/161822181-6b6be3ca-d7bb-44de-9481-d37a3fde6489.jpg)

**Comment by nysthi** [comment]
my only explanation is that a signali is coming in the channels (minimal, maybe a spike)


try to unconnect some of the cable from merge

connect only 1, 3 and 8
and do same tests

**Comment by MaZe6K** [comment]
You're right, sorry for the false alarm!
When I disconnect the cables it works.

I had competely muted those channels in the signal path before, but it seems something got through somehow unless i disconnect the cables.

**Comment by nysthi** [comment]
> You're right, sorry for the false alarm! When I disconnect the cables it works.
> 
> I had competely muted those channels in the signal path before, but it seems something got through somehow unless i disconnect the cables - so probably some mono-stereo problems somewhere else in the chain.
> 
> Thanks for all your great work! In Rack VST this works really good for recording up to 16 channels while other VST recorders recording just one stereo channel produce crackles.

I'm very proud of the code I've written for the recorder(s)
it's a work of art
maybe some company want to buy it... :D
