### ISSUE TITLE
Request: Option of replacing previous sample on SIMPLICITER via D&D like in previous versions

### ISSUE THREAD

**Issue by sergisabater** [nysthi/nysthi#404]
Before 2.0.15 you could drag a sample into Simpliciter and replace the current sample. Now the samples join together.
I like to use Simpliciter in a complex system of my own for generating new sounds, and drag and drop is very useful for a quick workflow. 
Many thanks!

**Comment by nysthi** [comment]
done

will be a new Contextual menu command 
for both Simpliciter and Simpliciter Multi

## SIMPLICITER
## SIMPLICITER MULTI
```* add a menu command "DRAG & DROP files are appended".  
  If the flag is OFF incoming sample will substitute the current one. If on is appended  ```

**Comment by nysthi** [comment]
will be in version 2 1 16

**Comment by sergisabater** [comment]
I appreciate!
