### ISSUE TITLE
Squonk trigger outputs sending gates

### ISSUE THREAD

**Issue by nukeyz** [nysthi/nysthi#406]
If I connect a cable to one of Squonk's trigger outputs, it sends out a gate that lasts until Squonk reaches that stage a second time.

**Comment by nysthi** [comment]
I can't repro

are you using last version ?

do you have a minimal patch to share ? (only nysthi modules)

**Comment by nukeyz** [comment]
I’m running version 2.0.6


I am including an example patch with this email.

The top row demonstrates the issue I’m talking about.

The 2nd and 3rd rows are identical except I’m using a VCV stock LFO. I noticed this using an LFO from Bogaudio, that Squonk behaves differently than it does with the nysthi LFO. I’m wondering what is happening to make it behave differently.

**Comment by nysthi** [comment]
there is nothing attached
please use direclty github, not the email to attach files

**Comment by nukeyz** [comment]
[Squonk strangeness.vcv.zip](https://github.com/nysthi/nysthi/files/8547057/Squonk.strangeness.vcv.zip)

**Comment by nysthi** [comment]
yes
I've found it
will be solved in version 2.1.17
