### ISSUE TITLE
Simpliciter crashing/freezing vcv rack

### ISSUE THREAD

**Issue by Spaceperson16** [nysthi/nysthi#407]
Hey,

I have a weird bug with my simpliciter. It doesn't matter if it's the only module in the patch or others with them, it doesn't matter if a sam9le is loaded or not, but everytime when I click the slice delete button, next slice or previous slice button, my whole rack crashes and I need to restart. Same when I adress modulation or gates into the cv inputs of those controlles. Everything else works like a charm, even the select knob where I can adress the slices works fine.

Oh and I'm on windows 11 and use vcv rack mark2 pro version. I guess it has something to do with my setup, because otherwise someone else would have reported that. So I m new into github and bugfixing. Is there a way to get a crash protocoll in vcv rack I could send here that would help?

Or did you ever heard of that issue?
Kind regards Frank

P.S. the nysthi plugins are all up to date inside of the vcv rack library. Update every time something pops up

**Comment by nysthi** [comment]
1)
please use version  2 1 16

it's only available here:
https://github.com/nysthi/nysthi/releases/tag/v2.1.16

2)
I use a mac and generally I get a crash log when there is a crash
don't know to obtain it on window

3) first time I have a report like this

thank you for the report (I'll check)

**Comment by nysthi** [comment]
can't repro

**Comment by Spaceperson16** [comment]
Thanks!! I will try out the new version and write back if it worked! So I should always check nysthi github for new releases?

**Comment by nysthi** [comment]
> Thanks!! I will try out the new version and write back if it worked! So I should always check nysthi github for new releases?

I always announce it in the community (there is a nysthi thread)

**Comment by Spaceperson16** [comment]
So I tried 2.1.16 
Funnily the prev and next slices buttons work no without problem, but rec button and it's cv input freezing still the module. Also tried out different sample rates and more then one thread and it still happens.

this is the log file from startup till crashing and closing vcv rack. only module in the patch was nysthi. Maybe that helps. But for me it seems there is nothing unusual in the file. line 612 I insert simpliciter.

[crashlog log v1 (startup till crash and closing).txt](https://github.com/nysthi/nysthi/files/8546818/crashlog.log.v1.startup.till.crash.and.closing.txt)

**Comment by nysthi** [comment]
that log is useless

I can't repro on my windows 10

sorry

**Comment by jaynothin** [comment]
Ok I can easily reproduce a crash with Simpliciter.

Tested on:
Windows 10 Pro 21H2
VCV Rack Pro 2.1.1
Nysthi 2.1.18
(Also tested by 2 other users: 1 on WinPro, VCV free 2.0.6 and 1 on Linux Fedora 35, VCV free 2.0.6)

Procedure is as follow:
insert Simpliciter
push the red DELETE button, and voila,
now insert any other modules 
VCV will seem to be working but it should have crashed
works every time for me (and the 2 other users)


I hope this can help 😃

**Comment by nysthi** [comment]
I'll check

**Comment by nysthi** [comment]
found
ok
probably solved
In version 2.1.19

**Comment by jaynothin** [comment]
I need to add something, but I'm sure you might have already looked at it. But just in case, before you release a newer version.

I did not test it before, so that's why I didn't mention it in my post.  

- The Simpliciter Mutli has the same DEL freeze bug 🐛 .

😃

**Comment by nysthi** [comment]
> I need to add something, but I'm sure you might have already looked at it. But just in case, before you release a newer version.
> 
> I did not test it before, so that's why I didn't mention it in my post.
> 
> * The Simpliciter Mutli has the same DEL freeze bug 🐛 .
> 
> 😃

PLEASE open a new ISSUE/BUG for it !
