### ISSUE TITLE
Squonk RND ALL input too sensitive to gates

### ISSUE THREAD

**Issue by nukeyz** [nysthi/nysthi#408]
Thank you for your recent updates to Squonk! I don't think it was working this way before, but now when I send a gate to the RND ALL input, all the values continue randomizing for as long as the gate holds. This is quite sensitive so I find even when I send Squonk triggers, I sometimes hear individual steps playing back more than 1 value. 

Squonk is easily one of my favourite sequencers, thanks again Antonio!

**Comment by nysthi** [comment]
the input is a for a pulse not a gate

I'll check

**Comment by nukeyz** [comment]
[Squonk RND ALL input retriggering.vcv.zip](https://github.com/nysthi/nysthi/files/8585951/Squonk.RND.ALL.input.retriggering.vcv.zip)


Here I have an example where you can see on the scope that Squonk's own trigger outputs are sometimes triggering more than one randomization.

**Comment by nysthi** [comment]
corrected behaviour (adding timer to avoid repeats for pulses)
(remember the input is for a trig of 1 msec)

in 2.1.19

**Comment by nukeyz** [comment]
Awesome! Thank you so much. 👍🏼
