### ISSUE TITLE
Confusing Simpler Clicking

### ISSUE THREAD

**Issue by Chaircrusher** [nysthi/nysthi#411]
Illustrated in this simple patch with minimal modules.

[ConfusionClicker.zip](https://github.com/nysthi/nysthi/files/8680190/ConfusionClicker.zip)

The situation is that
- Grid is active
- The grid is set to > 1 -- the number doesn't matter.
- The slice is set by a pair of SQUONKs 
- The trigger from the SQUONKs starts the current slice.
The slices are generated automatically. I'm not smart enough to set them manually, and the arbitrary START and END point is my aesthetic in this case.

Wouldn't it be possible at the start of a slice playing there's a short fade in, and similarly at the end where it loops have a short fade out?

What is a bit mystifying to me is that even if I put an envelope/vca on the Confusing Simpler output, no setting of the envelope does what I'd hope it does, which is smooth over the DC offset at the slice start/end.

I got slightly better results when I used an envelope follower on the raw Confusing Simpler output to control the VCAs, probably because the envelope follower is slower than the envelope.

**Comment by Chaircrusher** [comment]
Looking forward to it! 

I'm a programmer but not a DSP programmer, but what occurred to me is  when slices are defined, nudge the beginning and end to a zero crossing. I don't know how that would interact with things like modulating the slice length when grid is active. 

If you want me to test it, let me know!

**Comment by sapiogenesis** [comment]
@nysthi  It still seems to be clicking, my version is 2.4.23… Should I file a new issue? Is there an option that should be enabled to enabled fade-out or zero-crossing snapping to avoid the clicking?
