### ISSUE TITLE
Feature Request: 02NAGOL short documentation of the required data-structure for a csv-file

### ISSUE THREAD

**Issue by scheichreisuli** [nysthi/nysthi#415]
Hello,

02NAGOL can load csv-files. I had a look at the log-files of LOGAN/LOGAN02. I have difficulties to understand the data-structure. I want to create csv-data outside of VCV Rack and load them using 02NAGOL.

Here is a short example of my log-file-data:

ticks,msecs,value 1,value 2,value 3,value 4
10,0.208333,0.415088,,,,,,,,,,,,,,,,,,,,
20,0.416667,0.415088,,,,,,,,,,,,,,,,,,,,
30,0.625,0.415088,,,,,,,,,,,,,,,,,,,,
40,0.833333,0.415088,,,,,,,,,,,,,,,,,,,,
50,1.04167,0.415088,,,,,,,,,,,,,,,,,,,,
60,1.25,0.415088,,,,,,,,,,,,,,,,,,,,
70,1.45833,0.415088,,,,,,,,,,,,,,,,,,,,
80,1.66667,0.415088,,,,,,,,,,,,,,,,,,,,
90,1.875,0.415088,,,,,,,,,,,,,,,,,,,,
100,2.08333,0.415088,,,,,,,,,,,,,,,,,,,,
110,2.29167,0.415088,,,,,,,,,,,,,,,,,,,,

(...)

49600,1033.33,8.02047,,,,,,,,,,,,,,,,,,,,
49610,1033.54,8.02047,,,,,,,,,,,,,,,,,,,,
49620,1033.75,8.02047,,,,,,,,,,,,,,,,,,,,
49630,1033.96,8.02047,,,,,,,,,,,,,,,,,,,,
49640,1034.17,8.02047,,,,,,,,,,,,,,,,,,,,
49650,1034.38,8.02047,,,,,,,,,,,,,,,,,,,,

(...)

3031080,63147.5,6.1687,,,,,,,,,,,,,,,,,,,,
3031090,63147.7,6.1687,,,,,,,,,,,,,,,,,,,,
3031100,63147.9,6.1687,,,,,,,,,,,,,,,,,,,,
3031110,63148.1,6.1687,,,,,,,,,,,,,,,,,,,,
3031120,63148.3,6.1687,,,,,,,,,,,,,,,,,,,,
3031130,63148.5,6.1687,,,,,,,,,,,,,,,,,,,,

I logged only channel 1, named it 'one' in the user-interace.

What I understand:

ticks increment in steps of 10
msecs is the length of a tick (can be used for gates f.e.)

Here are my questions:

Does the CSV-file expect a header-row with the names of the columns/channels? If this is the case, which character tells 02NAGOL the end of the header-row?
What is 'value' ?? CV ?? In my sample-log-file the values just increment, but the logged values were random CV-values, logged by trigger-input.
What is the maximum number of ticks in a file?
Is the step-width of 10 for ticks a must or must this value just increment by full numbers?
What is the range of msecs?
What is the range of values, how many digits are accepted after the period?
Is there a special algorithm to calculate the 'value' from source for storage?

User-Interface:
What does the input CV-ADDR do?
What does the output TRIG TO NEXT do?
What does the TIME-RATE do?

When I changed the channel-title it is not stored in the log-file. I understand, that this is not necessary to read the data. But storing custom channel-titles might be helpful if the log-files are exchanged with other people or loaded in new patches.

What I want to do with 02NAGOL;

I want to experiment with big-data and make it "sound". For this purpose I have to transpose the source-data into the 02NAGOL-structure. Fe, use some traffic-data (rows) of different cities (channels/columns) and let them play oscillators or modulate envelopes or ... 

I remember a project in 2020 that used the COVID19-spreading-rate of cities across the world and made them "sound". The result was interesting and created a special "view" of what was going on with COVID around the world.

Thank you for your attention.

Peace

**Comment by nysthi** [comment]
Ciao!

happy to help you

give me some time !
(it's long time I don't use 02NAGOL !)

ciao
Antonio

**Comment by nysthi** [comment]
the output of the LOGAN20 (and LOGAN)  is a standard CSV file

**Does the CSV-file expect a header-row with the names of the columns/channels? If this is the case, which character tells 02NAGOL the end of the header-row?**

a CSV file contains cells terminated with a COMMA and a next LINE terminated with and EOL + CR (End of line + Carriage Return) 

the output contains in the first line the TITLES. The first is "TICKS", the second is "MSEC", strting from THIRD are titles entered in the field of the UI of LOGAN

to be sure create always a line on TOP like this one:
```
ticks,msecs,value 1,value 2,value 3,value 4,value 5,value 6,value 7,value 8,value 9,value 10,value 11,value 12,value 13,value 14,value 15,value 16,value 17,value 18,value 19,value 20,
```


you can avoid the the first line and current title will be not substituted



**What is 'value' ?? CV ??** 

values are incoming voltages

**What is the maximum number of ticks in a file?**

no limits
depends on the memory of your computer

**Is the step-width of 10 for ticks a must or must this value just increment by full numbers?**

TICKS is the number of samples between the voltages snapshots

(you can change it before recording using the contextual menu)

of course it's sample rate dependent

if you use a trigger to take snapshorts of incoming voltages, the TICKS will be computed as differentials from the start of recording

**What is the range of msecs?**

MSEC it's only informative: if you don't change sample rate or time of execution, the msecs will the time of the execution of the single line/snapshots

**What is the range of values, how many digits are accepted after the period?**

standard floating point: you can use the number of digits you want

**Is there a special algorithm to calculate the 'value' from source for storage?**


is a control voltage: if you are controlling something probably will be between -5 and + 5, or 0v to 10v


**What does the input CV-ADDR do?**
it's a control VOltage to address directly values loaded in memory from a CSV file
maps 0v to 10v incoming to the address of all single snapshots


**What does the output TRIG TO NEXT do?**
if connected to a trigger, excludes the inner clock
and the advance to the next snapshot using a single PULSE


**What does the TIME-RATE do?**
it's a time multiplier with CV control
for example if the events are happening every 1000 msecs and you set time rate to 2.0
the events will happen every 500 msecs

**Comment by scheichreisuli** [comment]
Thanx  alot for the information.

Keep healthy.
