### ISSUE TITLE
Complex Simpler/Quad Simpler clicking at the end of sample

### ISSUE THREAD

**Issue by espenstoro** [nysthi/nysthi#416]
I'm experiencing some kind of DC on the output of those samplers, when sample playback has ended. It makes and audible click, making it difficult to use these for drum samples. Happens to any sample. Tested in another sampler, there's no such issue. My samples are trimmed and faded, there's absolute silence at the end, verified in Cubase and other software.
Rack 2.0.6 Windows, plugin version 2.0.15, running 44.1KhZ sample rate. Let me know if you need further details.
![kj6yh54](https://user-images.githubusercontent.com/41498804/172105360-00e9a027-bc65-40c9-b9e5-38ef742c063e.jpg)

**Comment by nysthi** [comment]
are you using version 2.1.18 ? (just to be aligned)
https://github.com/nysthi/nysthi/releases/tag/v2.1.18

**Comment by espenstoro** [comment]
Sorry, didn't get reply notifications, and I didn't know that one existed. The problem is gone in the new version. :)

**Comment by nysthi** [comment]
ME HAPPY!!! :D
