### ISSUE TITLE
Soy Model Sou: 0.5.1 patches displace cables when opened in 0.6

### ISSUE THREAD

**Issue by Endvelope** [nysthi/nysthi#42]
Hi, 
![nysthi sou bug copia](https://user-images.githubusercontent.com/39956252/40978679-6c8c48bc-68c3-11e8-9e4c-8d0abf6d5e21.jpg)

As shown in the pic, when opened with 0.6, a patch made with 0.5.1 does not hook cables properly in the asr section... (PS the patch in the picture stands as a pure example, this is why there's no in and no pulse)

**Comment by nysthi** [comment]
@Endvelope sorry for the problem

Probably I mismatched the sequence when I created the OVERFLOW mode! SORRY

I can't go back because there too many people using the 0.6.0 version !
