### ISSUE TITLE
VCV Rack 2 crashes when using the module browser

### ISSUE THREAD

**Issue by scheichreisuli** [nysthi/nysthi#422]
Hi.

I'm on Win10, using VCV RACK 2 in a custom path-environment on drive "D". VCV generally works fine in this environment.

Scrolling in the module browser crashes VCV Rack from time to time. I'm posting this issue here, because the NYSTHI-Modules are always involved when it cames to crashes. VCV Rack only crashes when I use the module browser.

If the reason for crashes is a more general VCV-aspect but a NYSTHI-aspect, I beg your pardon for posting here.

Most crashes occure, when NYSTHI is part of the search filter or if the only filter is NYSTHI (by brand).

The crash does not happen every time when I search in the modules, even when NYSTHI is part of the filter. If I remember it right, most of the crashes appear when scrolling to the end of the modules-list is part of the workflow, but I might be wrong.

Many crashes happened when the tag "delay" was involved, but this might be the case because I use this tag more often than other tags.

I remember two or three crashes triggered by hitting the backspace-key sereral times and fast in the module browser. Maybe the browser does not like hitting "backspace" when the search-filed is empty or no filter-tag is set. But this is NOT the main reason for the browser-crashes. 

I attache two log files, hoping they do tell more about the things that were going on on my machine.

Thank you for listening
Keep healthy

[20220527-1513_log.txt](https://github.com/nysthi/nysthi/files/9281611/20220527-1513_log.txt)
[20220808-log.txt](https://github.com/nysthi/nysthi/files/9281612/20220808-log.txt)

**Comment by nysthi** [comment]
hi

thanks for the report

the 1513 report contains info about the killing module:

the calling this sequence is

```
30: ZN7ScaleCV7processERKN4rack6engine6Module11ProcessArgsE 0x7ffc1a463940
29: ZN7ScaleCV7processERKN4rack6engine6Module11ProcessArgsE 0x7ffc1a463940
28: ZN7ScaleCV7processERKN4rack6engine6Module11ProcessArgsE 0x7ffc1a463940
27: Z7sprintfPcPKcz 0x7ffc1a46f960
26: Z24detect_chord_name_simple5chordPc 0x7ffc1a462880
25: ZN16DiatonicCVWidget18ChordDisplayWidget9drawLayerERKN4rack6widget6Widget8DrawArgsEi 0x7ffc1a4742d0
24: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffbed7d6e70
23: ZN4rack6widget6Widget9drawLayerERKNS1_8DrawArgsEi 0x7ffbed7d70c0
```

no one of this functions are mines

you should investigate in the community for these names

ScaleCV
detect_chord_name_simple chordPc
DiatonicCVWidget ChordDisplayWidget



the second log it's just the load log
and no info on CRASHES
Do you have a small amount of memory ?

**Comment by scheichreisuli** [comment]
Hi,

thank you for your quick answer. This was helpful. My skills are not sufficient to read the log-/crash-files written by VCV Rack. I'll contact the author of the modules you have mentioned, "Aaron Static".

My memory-size is 64GB, should be enough for VCV Rack. :) But maybe the memory-management of VCV Rack might be the reason for the crashes. The crashes always happened after VCV was running for a while.

There are issue-reports for the module-browser, dated from Dec 2021. Maybe there are still unsolved problems. I'll keep an eye on them.

Thank you again.

Have a nice day.

**Comment by nysthi** [comment]
grazie mille
