### ISSUE TITLE
4 ASR Global Release BUG

### ISSUE THREAD

**Issue by Outboarder** [nysthi/nysthi#442]
If you put global release to max and close vcv and reopen patch the global release resets to minimum but the knob is still in max position. 
Here is the patch :  
https://drive.google.com/file/d/1-4NLs8ids1Xx3IuVx6NJ4U3qe_MteLz9/view?usp=share_link
play with global release knob.

**Comment by nysthi** [comment]
please open your doc for my access !  grazie

**Comment by Outboarder** [comment]
Sorry. done
https://drive.google.com/file/d/1-4NLs8ids1Xx3IuVx6NJ4U3qe_MteLz9/view?usp=share_link
version 2.0.15

**Comment by nysthi** [comment]
can't repro on versione 2.1.19

**Comment by nysthi** [comment]
sorry can't repro but you are using a very obsolete versione, last is 2.1.19
