### ISSUE TITLE
ETCHASKETCHOSCOPE Vector length knob BUG 

### ISSUE THREAD

**Issue by Outboarder** [nysthi/nysthi#443]
Before the latest update Vector Length knob was reset to zero every time you open a saved patch (old bug). 
Now it prevents you to move the knob.

**Comment by nysthi** [comment]
bug !

**Comment by nysthi** [comment]
(anyway what's the most important is the "FADE TIME" knob )

**Comment by Outboarder** [comment]
I can type in values and it changes. but can't do that with mouse. I'm using official version 2.0.15 
![scope](https://user-images.githubusercontent.com/25549725/229730686-cbbe2adf-11b8-40ff-ab29-b3cb6698443a.gif)
* same behavior in version 2.1.19.

**Comment by nysthi** [comment]
mmmm, BUGGGGG!!!

**Comment by nysthi** [comment]
solved in next release
