### ISSUE TITLE
Programmer and VCV Pro 2/Windows- knobs not responding

### ISSUE THREAD

**Issue by technochitlin** [nysthi/nysthi#444]
Was trying to follow Pyers Suzanne Ciani videos, but discovered that when I add the Programmer the knobs cannot be adjusted by the mouse; also if I try to enter a voltage manually (via right-click) what ends up as the value seems to be about 10x what I entered. Am I missing something?

**Comment by nysthi** [comment]
you have to use the 2.1.19 version
form here
https://github.com/nysthi/nysthi/releases/tag/v2.1.19

**Comment by technochitlin** [comment]
That is the version I am having these problems with

**Comment by paulpiko** [comment]
Same problem here with nysthi 2.1.19 in Rack Pro 2.3.0. Using Windows. Can't adjust the knobs with the mouse, and entering a voltage manually ends up way off.

**Comment by nysthi** [comment]
I hate when VCV RACK destroys the work of plugin developers (changing inners)! Sorry guys I don't have time to give to an update (currently)

**Comment by paulpiko** [comment]
I’ll look forward to when you can get a chance to update it.

**Comment by paulpiko** [comment]
An update to show my workaround: Use Mindmeld Patchmaster to map the 64 knobs. The patchmaster knobs can then be used instead of the original Programmer ones. Use stoermelder Strip to save and re-use the set of modules. (I have repositioned the modules in the image)
![image](https://github.com/nysthi/nysthi/assets/56526215/3333062f-d171-445b-bd55-c83c0676b369)

**Comment by nysthi** [comment]
Hey @paulpiko  !!
Thank you for taking time to discover a workaround!

I hope to have time next august !
hugs !

**Comment by paulpiko** [comment]
Thanks, that's good news!

**Comment by nWacher** [comment]
I'm having the same problem using on both Linux and Mac intel (Nysthi 2.1.19).  Only setting the voltage range from 0v to 1v seems to work correctly. Thanks for the workaround @paulpiko!

**Comment by nysthi** [comment]
solved... in next release...
(if you have MAC arm I  have  new release)

**Comment by nysthi** [comment]
@paulpiko 👍

**Comment by nysthi** [comment]
(it was related to a change in the API from VCV code...)

**Comment by technochitlin** [comment]
Windows user
[sigh]
________________________________

**Comment by paulpiko** [comment]
Thanks Antonio! Don't have mac, so I'll try it out when there's a Win release. 😉  Very happy you've been able to get the time to update

**Comment by paulpiko** [comment]
Hi Antonio, the knobs aren't working in Win 2.4.21

**Comment by nysthi** [comment]
reopened... thanks for the report (I tested it, maybe during compilation something happened)

**Comment by nysthi** [comment]
PLEASE! try [this](https://github.com/nysthi/nysthi/releases/download/v2.4.21/NYSTHI-2.4.21-win-x64.vcvplugin)!

**Comment by nWacher** [comment]
Thank you Antonio, it works fine on my end (Linux)
