### ISSUE TITLE
Right click numerical input for Elsker module

### ISSUE THREAD

**Issue by CarlosBoix** [nysthi/nysthi#445]
Hello,

Whilst using Esker I wished it could accept numerical input of delay and gate length times to quickly punch in the values rather than having to click and drag. 

Could this function be implemented on a future update please ?

Many thanks in advance

**Comment by nysthi** [comment]
why not ! :D 
currently I'm not working on VCV, but I'll consider it if I'll do new releases

thank you !

**Comment by nysthi** [comment]
will be in next release
contextual menu to switch to editable text filed for durations and delays (but only for RAEL, that is a SUPERSET of ELSKER)
