### ISSUE TITLE
CPU overload on Mac Studio M2 Max

### ISSUE THREAD

**Issue by james4487** [nysthi/nysthi#446]
Hello! I'm experiencing an issue when using the Simpliciter in VCV Rack (VST running in Ableton) when I have a fairly big patch (nothing utterly crazy, five voices and various mod/ effects) open and one of the modules is Simpliciter. The CPU will be running between 25-35% in VCV rack/ Ableton but there will be occasional spikes where it suddenly heads into the 80-100% region for a split second which causes loud crackling and stutter. This is 100% due to Simpliciter and it's the only module I've used so far that causes this to happen on my Studio (which is obviously a pretty powerful machine).

A bit more context on the patch, I have a gate from Befaco Rampage that triggers the record every time the gate is falling, so it's regularly re-recording but only for a few seconds at a time.

Any idea what could be causing this? Apologies if it's something that's been addressed before, I've had a search and can't see anything.

Thanks! :)

**Comment by nysthi** [comment]
@james4487 sorry can't verify this
I don't have many items to repro the case

have you tried with the ARM version [here](https://github.com/nysthi/nysthi/releases/download/v2.4.0arm64/NYSTHI-2.4.0-mac-arm64.vcvplugin) ?

**Comment by ghost** [comment]
Why not put the ARM versions up on the VCV library?

**Comment by nysthi** [comment]
is in the LIB now
