### ISSUE TITLE
Improvement: Setting delimiter in LOGAN20 and NAGOL02

### ISSUE THREAD

**Issue by scheichreisuli** [nysthi/nysthi#447]
Hi,

currently LOGAN20 and NAGOL02 support the comma as the only CSV-delimiter. It would be nice to expand the set of supported delimiters or to implement a rightclick-menu-option to enter the delimiter for an entire CSV-file (im- and export).

When dealing with numeric values the comma is internationally used for different purposes.

In many European countries the comma is used as the decimal-dot, and the dot is used as the devider for thousands (different to the UK-world). In many applications It is not that simple to force the export of numeric decimal values in the UK-form. In many cases the numeric values have to be converted to strings for this purpose and then the comma has to be replaced by a dot. Such values remain strings, and when exporting strings to CSV, a lot of applications generally like to embed string-values in double-quotes.

All this is bad when preparing data for NAGOL02.

When exporting decimal values from Excel to CSV, the delimiter is semicolon as a fixed character, no way to change this inside of Excel anymore (WIN10+). To make such files available for NAGOL02, the semicolons have to be replaced with commas in an editor, which initiates more problems because the numeric values might have the comma, too, as their decimal-dot.

So it would be very nice to have a little bit more flexibility using LOGAN20 and NAGOL02. The support of ', ; | tab' as CSV-delimiters would be very handy.

Please let me mention another aspect:

Currently the CSV-files for NAGOL02 MUST match 22 columns, even if the maximum of used data-columns is lower. This is not a big thing, but maybe NAGOL02 might look for the number of used columns by itself, if this is no big deal to implement it.

Thank you for your time, LOGAN20 and NAGOL02

**Comment by nysthi** [comment]
checking

**Comment by nysthi** [comment]
added support for various separators 
<img width="299" alt="Screenshot 2023-09-12 at 09 59 08" src="https://github.com/nysthi/nysthi/assets/33201978/35d04c3b-d95b-48c7-8c87-402ab0c6683b">
(in export and import)
<img width="530" alt="Screenshot 2023-09-12 at 09 59 20" src="https://github.com/nysthi/nysthi/assets/33201978/2ba72082-baa8-442c-9d2e-a5b55bb9c4b5">

**Comment by nysthi** [comment]
will be in next 2.4.1 version

**Comment by nysthi** [comment]
added variable export: last connected input, will be last column exported

**Comment by nysthi** [comment]
will be released in 2.4.1

**Comment by scheichreisuli** [comment]
Thank you very, very much for these enhancements.
