### ISSUE TITLE
Simpler Tape Control Click does not Click

### ISSUE THREAD

**Issue by Petervos2018** [nysthi/nysthi#448]
https://community.vcvrack.com/t/simpler-tape-control-click/20461/1

When you're ready to take this on again 😉 

Greetings Peter

**Comment by nysthi** [comment]
Found...

**Comment by nysthi** [comment]
if you want a simple correction
go in the "nysthi/res folder"
remove the `simpler_tape_ctrl` folder
and unzip the one attached here
[simpler_tape_ctrl.zip](https://github.com/nysthi/nysthi/files/12540578/simpler_tape_ctrl.zip)

**Comment by nysthi** [comment]
will be solved in 2.4.1 release

**Comment by Petervos2018** [comment]
Thank you for looking into it. so it was the "case of the missing samples" ?

Greetings Peter.

**Comment by nysthi** [comment]
please don't close it (I need to do when I do the "official" release! )

(no problema !  :D )

**Comment by Petervos2018** [comment]
Cool sorry.

😃
