### ISSUE TITLE
DeepNoteGenerator

### ISSUE THREAD

**Issue by icet99** [nysthi/nysthi#45]
Hello,
in the VCV Rack Official User Group I found a video with a modul called DeepNoteGenerator. But I can't find such a module in VCV Rack under Nysthi. Where to find this module?
Rainer

**Comment by nysthi** [comment]
@icet99  did you find it ? It's called DeepNote

**Comment by icet99** [comment]
Yes, of course, I do now with 6.4.1. That's great, thanks a lot and go on with your marvelous work.

Rainer

 

Gesendet: Montag, 18. Juni 2018 um 20:01 Uhr
Von: nysthi <notifications@github.com>
An: nysthi/nysthi <nysthi@noreply.github.com>
Cc: icet99 <rainer.birlin@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [nysthi/nysthi] DeepNoteGenerator (#45)


@icet99 did you find it ? It's called DeepNote
