### ISSUE TITLE
ExpiredTime 2.0.15 #bug

### ISSUE THREAD

**Issue by bravegrumpy** [nysthi/nysthi#450]
# ExpiredTime 0.6.39 #bug
<details><summary>Details</summary>
<p>

The functionality of changing the Alarm Times does seem to function.
I want to use the alarm times to receive an output at the set time. 

</p>
</details>

**Comment by nysthi** [comment]
what is the 0.6.39  ?
Seems something of 4 years ago ! :)

**Comment by nysthi** [comment]
did you try to click and drag on the red fields of the alarms  ?

**Comment by bravegrumpy** [comment]
The 0.6.39 is the version that I found in the documentation. That is my mistake. I am actually using version 2.0.15.

I tried clicking and dragging, and I've tried right clicking, and I've tried it with and without connecting to another module that can accept a pulse imput (Bignumber). 

In none of these cases am I able to set the alarm times.

**Comment by nysthi** [comment]
you should use 2.1.19 version
from [here](https://github.com/nysthi/nysthi/releases/tag/v2.1.19)

**Comment by nysthi** [comment]
(2.1.19 is not library distributed)
