### ISSUE TITLE
Complex Simpler load wav issue

### ISSUE THREAD

**Issue by Petervos2018** [nysthi/nysthi#451]
Hi Antonio

After I have chosen a sample and I reload vcv I CAN NOT choose another sample by ->Open WAV or AIFF file. As long as I stay in the same folder it will not choose a different wav , but when I go to ->Current Files, I can choose any wav from the list and it will play.

So I can choose a Folder and click any wav in there and it will choose the first wav from the list, but I can change that by going into current files and choose one from the list.

And when I restart/reload vcv or the vcv file it will play the chosen file.

Win10 vcv 2.4.1 Nysthi 2.1.19.

I hope you understand what I'm trying to report here ;)

Greetings Peter.

**Comment by nysthi** [comment]
I think I'll need a new window machine! :D

**Comment by nysthi** [comment]
I tested in debugger mode and on my MAC m1
can't repro

I inserted a complex simpler
loaded with a sample
played with all the ten samples in same dir
duplicate the simplert (it's like to open it from file)
still working
opened on a new dir and imported another set of 4 samples

**Comment by Petervos2018** [comment]
Maybe when I have time I'll make a video to show you what I mean.

**Comment by Petervos2018** [comment]
If you rename the "open wav or aiff file" to "Open Folder"
And rename "current file" to "Choose file (from folder)"
It all works as expected .

**Comment by nysthi** [comment]
AH! I know whaat are you saying

it's happening on Windows, I think I have seen it in the past


in a dir with 10 wav, you choose the 5th
but the loaded sample is the 1st
and you can change it only with contextual menu

yes it's something for WIN

I need a WIN MACHINE !!! :D

**Comment by Petervos2018** [comment]
We were typing at the same time, but yes that's what's happening 🎉 

Now with pictures....ooooooooh

![afbeelding](https://github.com/nysthi/nysthi/assets/46076474/126754cb-cb6c-4a4b-8563-395d73e70d9b)

When I click open wav.... it opens the browser window, when I select Claptrap 10.wav an hit open(en) It will not load Claptrap 10 but it opens the first wav file in the folder in this case Claptrap 01.wav

![afbeelding](https://github.com/nysthi/nysthi/assets/46076474/e3d8e93f-8c5a-4985-8bc4-28b0cf97d6cf)

But now I can use the CURRENT FILE to choose Claptrap 10.wav

![afbeelding](https://github.com/nysthi/nysthi/assets/46076474/f5a112c2-c183-434a-9876-10708412cb9a)

TADA !

**Comment by nysthi** [comment]
you know that you can select it using CV and/or TRIG with expander ? (SL)

**Comment by nysthi** [comment]
(you need to put the expander on the right)
(I think)

**Comment by Petervos2018** [comment]
Yes that works great: 

![afbeelding](https://github.com/nysthi/nysthi/assets/46076474/c8ae8ae0-2200-46bd-a7d1-6334bb1321a0)

**Comment by nysthi** [comment]
found! Working on... 
(finally I 've created a setup in debug mode on win)
