### ISSUE TITLE
Thunator fails to get tuning on Behringer K-2.

### ISSUE THREAD

**Issue by jpnielsen** [nysthi/nysthi#452]
I Just tried the "Thunator" on the Behringer K-2 - the 4' range.

First time around, i did it in the 8' range on the K-2. Thunator couldn't find the upper frequencies. so I changed to the 4' range, and click "calibrate".
The calibrator tried again, but didn't stop when a lower than possible voltage was generated.

<img width="716" alt="image" src="https://github.com/nysthi/nysthi/assets/27916597/612d5497-37bb-4e64-b477-0ce67ea63f5c"> less than -40V volts - it doesn't stop.

I would like it to come out wirh an error if the range of my Expert Sleepers ES-3 is exceeded - it is plus/minus 10 Volt. Maybe an option to set low/high voltages.

The K-2 is presumably Hz/V - not V/Oct.

The way i have it cables, 0 - ca 8 V gives the full frequency range. the actual frequencies are reated to the range knob setting.

Thank you so much for making you modules, and making them available for "all".

**Comment by nysthi** [comment]
added a check on the range if the range is out of -20V -> 20v an errori is generated and the operation is stopped
(in the next release 2.4.21)

![Screenshot 2024-02-05 at 14 48 10](https://github.com/nysthi/nysthi/assets/33201978/90dfb407-265a-46ac-874f-3fd200a78e5b)


![Screenshot 2024-02-05 at 14 47 49](https://github.com/nysthi/nysthi/assets/33201978/72039dcb-a712-4279-84c8-5d488d98ecd2)
