### ISSUE TITLE
Latest version still crash in Rack 0.6.1

### ISSUE THREAD

**Issue by caecos** [nysthi/nysthi#46]

**Comment by caecos** [comment]
[5.609 warn src/plugin.cpp:84] Failed to load library ./plugins/NYSTHI/plugin.dll: code 126

**Comment by Ghalebor** [comment]
In Rack 0.6.1. Mostly parts of this plugin works fine. But Spectre always crash Rack.

**Comment by nysthi** [comment]
@Ghalebor @caecos can you try release 0.6.5 ?

**Comment by molluskderek** [comment]
I'm getting a crash on clicking "Open wav..." in QuadSimpler, Rack 0.6.1, NYSTHI .6.4.1 and .63. 

OSX 10.13.5

**Comment by nysthi** [comment]
@molluskderek you should use version 0.6.5 !
