### ISSUE TITLE
Feature Request/New Module: NYSTEREOEOEO - 

### ISSUE THREAD

**Issue by patman023** [nysthi/nysthi#48]
Like 2 Echorecs in one!
- Individual heads for each channel
- Modulated Stereo Pair Head Alignment?

**Comment by nysthi** [comment]
@patman023 
partially done
too complex to do separated heads

but I have now 2 ECHO running in pair with slight variations of the heads
and the output is Stereo

**Comment by nysthi** [comment]
in 0.6.6
