### ISSUE TITLE
Feature Request: NYECHOEcoecocococcococoooo

### ISSUE THREAD

**Issue by patman023** [nysthi/nysthi#49]
Increase Maximum Delay Time on the NYECHOECOECO

Suggestion:
- add a slow/extended mode switch, with speed ranging from 0.1cm/s to 9.9cm/s (factor of 10 difference from current) to not mess with existing patches, as well as to keep the same scaling on the knob

**Comment by nysthi** [comment]
this is a tricky change
if use the 0.1 as minimum, I have to preserve (at 44.1khz)
(44100 * 4 * 12 / 0.1) bytes  per chanel (because I can change delay to delay in smooth mode)
in stereo mode should be about 40MB preserved
