### ISSUE TITLE
complex simpler doesn't save start position, starts back at beginning on open

### ISSUE THREAD

**Issue by jeremywen** [nysthi/nysthi#5]
1. add complex simpler
2. load sample
3. turn start knob to the middle of the file
4. close Rack
5. open Rack

actual result:  start position now at the beginning.
expected result:  start position at middle of file where I left it.

**Comment by nysthi** [comment]
thanks for the report!

**Comment by nysthi** [comment]
0.5.1 coming...

**Comment by nysthi** [comment]
solved in 0.5.1
