### ISSUE TITLE
feature request for SQUONK

### ISSUE THREAD

**Issue by jeffreywithonef** [nysthi/nysthi#52]
Hi 
I really love the nysthi modules especially SQUONK, I was wondering if it is possible to add cv to the ROT feature so I can modulate it. 

Have a nice day and great work on these modules

**Comment by nysthi** [comment]
find me a place !!! (it's crowded !)

**Comment by jeffreywithonef** [comment]
Haha, I get your point, I have two suggestions tho. 
![nysthirot](https://user-images.githubusercontent.com/41511187/43576601-02aaa844-964a-11e8-963f-7e6edb1843b7.png)

**Comment by nysthi** [comment]
in v1
