### ISSUE TITLE
Dynamo Display probllem

### ISSUE THREAD

**Issue by ShofB** [nysthi/nysthi#55]
I am getting this display error on one of my machines.  It is a W10 using AMD and the on board video.  Anything I can do to help let me know.  BTW thank you so much for your innovative and useful mods!

![dynamo error](https://user-images.githubusercontent.com/4075532/43484434-2f57814c-94c3-11e8-8876-2b0ddd63ef87.jpg)

**Comment by nysthi** [comment]
thank you for the report!
very strange problem because I have a clipping too on that view !

**Comment by patman023** [comment]
AMD A10-9600P 4C+6G APU, no issues

**Comment by patman023** [comment]
@ShofB still an issue?

**Comment by patman023** [comment]
Recommend closing.
