### ISSUE TITLE
Depends on a dylib not present on Rack 0.6?

### ISSUE THREAD

**Issue by cwmoriarty** [nysthi/nysthi#56]
Running OSX Mojave. 

NYSTHI works in Rack 0.6.2b, but not 0.6.0.

Rack's log.txt:
`[0.646 warn] Failed to load library /Users/cmoriarty/Documents/Rack/plugins/NYSTHI/plugin.dylib: dlopen(/Users/cmoriarty/Documents/Rack/plugins/NYSTHI/plugin.dylib, 2): Symbol not found: _osdialog_filters_free`

**Comment by nysthi** [comment]
yes, it's not compatible with 6.0 : there was a slight change in the RACK api in 0.6.1 and nysthi used a non declared API

**Comment by cwmoriarty** [comment]
thanks! Just making sure someone was aware.
