### ISSUE TITLE
Mverb segmentation fault

### ISSUE THREAD

**Issue by WouterSpekkink** [nysthi/nysthi#57]
This is not something that happens consistently, but it still happens quite often: When I add an Mverb module, either via the context menu or by duplicating, sometimes VCV rack will crash and report a segmentation fault in the console. In other words, something in the code for the Mverb module is trying to access memory at an illegal memory address.

I am running VCV rack on Debian 9.

**Comment by nysthi** [comment]
I noticed, something happening on mverb
(it's like the module is called before init)
