### ISSUE TITLE
Bug? in text value displays

### ISSUE THREAD

**Issue by ShofB** [nysthi/nysthi#58]
On some of your new modules you have a numeric display that you can click on and by moving the mouse up/down change the value.  However when they are used in a stereo mode you can not adjust them independently.  Turning up one cause both of them to increment.

![image](https://user-images.githubusercontent.com/4075532/44324580-eeedf300-a40a-11e8-8709-96ee424eaae6.png)

Also I can find no other way to change the values on these displays.  Am I missing something.  And as usual thanks a million for you great work.  From on coder to another I don't see how you are able to maintain this level of quality output.  I

**Comment by nysthi** [comment]
the red display are always editable
the more you move the mouse to the left, the more increase or decrease the value

the green display are always result of the red display after modulation. They are just to show the current real value used (after a CV modulation for example)
Most of the time they have the same value as the red ones.

there are no separated control for LEFT and RIGHT channel on this one !

sorry if I'm so hermetic! But for speedy reason I've standardized some of my controls and uses

**Comment by ShofB** [comment]
No, great and thanks.  I expected it was me not knowing what was happening.

ShofB

My Web Site
http://www.l-and-l.net

Check out my Soundcloud stream @
https://soundcloud.com/shofb

And my YouTube MyKits demos @
http://www.youtube.com/channel/UCjKNiE1s2YlJYPsAKbe8vhg

________________________________
