### ISSUE TITLE
Duplicating Complex Simpler causes confusion on reload

### ISSUE THREAD

**Issue by cschol** [nysthi/nysthi#60]
When **duplicating** a `Complex Simpler` (via context menu), both of the instances seems to be connected to the same setting in the patch file. On reload this causes **both** of the instances to reload the sample that was selected **last** in either of the instances.

This does not happen when creating a new `Complex Simpler` instance "from scratch" (i.e. via the normal module selection menu).

Looking at the patch file, this is probably because the `nysthi_id` gets duplicated instead of generating a new one when creating a new instance by duplication via context menu.

**Comment by nysthi** [comment]
something changed in the 0.6.1 API
was solved in 0.5.0

**Comment by nysthi** [comment]
the clone mode is impossible to distinguish from the  normal creation, so I can't create a separate ID for a duplicated SIMPLER

I've removed the DUPLICATE commands from simplers
