### ISSUE TITLE
jooper reset

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#62]
Hi, here's the original Joop :)
Could you make the reset switch on the Jooper reset everything, but not the mode? Now, if you have set two scenes in dual exclusive mode, when you reset (which is needed to set the jooper to the start position when starting a song) the mode is reset too, which breaks the structure of the composition. To me, it would be more logically to stay in the mode that's selected.

Thanks again, Joop

**Comment by nysthi** [comment]
ok!

**Comment by nysthi** [comment]
done
in release 0.6.23 the reset will apply to the mode only if you press "WINDOWS/OPTION" key down when you press it

**Comment by joopvdl** [comment]
Wonderful! I assume the trig in for reset will also not apply to the mode?

**Comment by antoniotuzzi** [comment]
correct

**Comment by nysthi** [comment]
solved

**Comment by joopvdl** [comment]
Hey Antonio, I was wondering, why doesn't set the reset function switch the
scenes back to scene 1?
Jooper is awesome, I might be the only one using it but it is so great for
creating structure. I have a patch with 4 instances in it at the moment :)

Joop

Op zo 16 sep. 2018 om 19:35 schreef nysthi <notifications@github.com>:

**Comment by nysthi** [comment]
do you want a reset on scene 1 too (when reset is hit) ?

**Comment by joopvdl** [comment]
This is what I had in mind:
the scenes stay as they were programmed. Reset will set the Jooper to scene
1. So you can then advance through the scenes you programmed.
There's no need to have reset erase the scenes, on the contrary, we want
those to stay!

btw a trig in for "add scene" would come in handy when working with
multiple Joopers.

Op di 16 okt. 2018 om 23:09 schreef nysthi <notifications@github.com>:

**Comment by nysthi** [comment]
it's a dual requests ... :)

I agree about the add by trig is very important for automated creations

**Comment by joopvdl** [comment]
oh man, dual is nothing yet :)


Op di 16 okt. 2018 om 23:16 schreef nysthi <notifications@github.com>:

**Comment by nysthi** [comment]
solved
in the 0.6.28

1) on reset, the screen is cleaned, and scene is set to 1 (one) but not loaded
2) added LOAD by TRIG and by TAP 
3) added SAVE by TRIG and by TAP

**Comment by joopvdl** [comment]
wonderful.
just a question, what is the difference between set and load? I think I
have missed that until now..

Op wo 17 okt. 2018 om 00:21 schreef nysthi <notifications@github.com>:

**Comment by nysthi** [comment]
you can change the current SCENE using the RED display (mouse and drag)
and to load it in the screen, you need to LOAD 

the PREV and NEXT are doing  1) a move to the scene and a 2) LOAD automatically

**Comment by nysthi** [comment]
I changed my mind
the jooper is 2 main areas:
the JOOPER SCENE CREATOR
and the JOOPER SCENE SEQUENCER

so the RESET for the JOOPER SCENE CREATOR is just a clean up of the screen to initial conditions
but I have added new commands an trigs for the sequencer:

GO FIRST (TAP and TRIG) will jump a load the FIRST SCENE (kind of RESET of the SCENE SEQUENCER)
+ I've added TRIG to DELETE and DELETE all, so you can use other tool to do programming (or use events from RACK)

![screen shot 2018-10-17 at 09 03 06](https://user-images.githubusercontent.com/33201978/47068045-81ccc300-d1eb-11e8-8b11-255b677f2c6c.png)

**Comment by joopvdl** [comment]
the wonderful thing is, you seen to find functionalities that go much
further than I originally suggested, and they are super useful. This thing
has turned into so much more than I imagined! Antonio, please come to
Holland and I will serve you a wonderful lasagne, tiramisu and loads of
beer.

Op wo 17 okt. 2018 om 09:03 schreef nysthi <notifications@github.com>:

**Comment by joopvdl** [comment]
now I'm dreaming about a clock input, and a counter (per scene) that will automatically (after the counter value) proceed to the next. So you can automate structure, and finetune arrangements by changing the counter values. Scene 1, 8 bars, scene2, two bars, etc...

**Comment by joopvdl** [comment]
can't you make a separate module that will sync to the current scene
setting of Jooper? It will need to be called Janneker (that's my wife) :)

Op wo 17 okt. 2018 om 11:11 schreef nysthi <notifications@github.com>:

**Comment by nysthi** [comment]
good idea
a scene sequencer of pulses

the best would be to associate directly in the JOOPER
every SCENE can live  for XXX pulse (the pulse in counter), and the information is store with SCENE

a pulse (with reset feature) come in and advance the pulse count, showing it
and if the OVERFLOW is hit, output a pulse (to sync other devices) and advance to the next

this means I need to change the file format: are you ready for this ?

**Comment by nysthi** [comment]
I could do a separated JANNEKER module, but you need to build a sequence in parallel to the scene manager

but seems more flexible, you can use it for many other things

**Comment by nysthi** [comment]
I think I'll go with JANNEKER mode

**Comment by joopvdl** [comment]
If you can connect the next/previous scene buttons through cv, that would
do the trick. Or even just the next scene. So you can zap forward through
the scenes, and the two modules will stay in sync.
But you could also use an external trigger for this.
Reset will reset both to scene 1.
If you include a record function, you can play your structures live and it
will be remembered. When record is enabled, every time you advance to the
next scene, the count number is stored.
Man, that would be AWESOME :)

Op wo 17 okt. 2018 om 12:04 schreef nysthi <notifications@github.com>:

**Comment by joopvdl** [comment]
Currently, there's no way to update a scene, right? In Jooper .
When you have made a sequence of scenes that you like, but in the 8th scene you would like to take out something (or add..)..
Now, if you change something, that isn't remembered. Would be nice if it just remembers the last used setting. Or there could be an "update" function. 
Same in Janneke, if you have made the sequence of steps (lengths), will you be able to make changes in a scene?

**Comment by nysthi** [comment]
next version will have UPDATE (from current screen)
and INSERT too

**Comment by nysthi** [comment]
(Janneker is already updatable, but not INSERT (no space))

**Comment by joopvdl** [comment]
Now I think we should convince Omri or one of our other friends to create a
video explaining the workflow of the Jooper/Janneker combination.
I would love to do this, but my system is not ready for video capture.
But I would gladly assist.
And boy, am I proud.

Op ma 22 okt. 2018 om 19:08 schreef nysthi <notifications@github.com>:
