### ISSUE TITLE
confusing simpler crashes when opening project on a different computer, recording

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#65]
I assume this has to do with either the directory structure, or the location of the samples. anyway the project opens fine but when simpler goes into record it crashes.
I seem to remember this happened with the other simplers too, and I don't know if there's anything to do about it, but just wanted to report this. If you need any help trying out stuff, just let me know.

**Comment by nysthi** [comment]
I simulate all cases only using a mac, and can't repro
if something is missing, is always recreated
also if it's missing the directory

extending the tests

**Comment by nysthi** [comment]
tested on WIN10, cant't repro
I simulated both, missing file and missing directory

**Comment by joopvdl** [comment]
What should happen if the sample is not found? I am still getting these crashes.

**Comment by nysthi** [comment]
should present a confusing simpler with an empty sample area (all white)

**Comment by nysthi** [comment]
can you see a "cache" directory under "nysthi" ?
can you see files there ?

**Comment by joopvdl** [comment]
There's a cache directory, and there are files in it.
I think the problem is this: one system is in Dutch language, the other
English.
So the names of the directory structure (file path) are different.
If I port a patch from one computer to the other, it will look for the
cache in the wrong directory, and it will try to write the cache file to a
non-existing directory (because it expects it to be there, as written in
the vcv file (is that xml?)
If I delete the sampler, and repace it, problem gone. Because then it will
have the proper file path in the vcv file.

Could that be it? I am not a programmer, so I could be wrong, of course.

Op di 23 okt. 2018 om 08:53 schreef nysthi <notifications@github.com>:

**Comment by nysthi** [comment]
could be a valid reason
can you send me the full path to the "cache" directory of your dutch system ?

(I want to check if there is something strange in the names and reproduce it locally)

thank you !

**Comment by nysthi** [comment]
ok, could be a problem of the inner RACK routine giving back the "Documents" directory where RACK is located ?

but if you say, you can add a new SIMPLER to the DUTCH sys and add a SAMPLE and after you see that sample in the CACHE... 

there is more involved

**Comment by joopvdl** [comment]
here's a patch that will demonstrate the path differences.
If I press record in the newly created simpler (the second), no problem.
If I record the other, crash (a while after ending record, strangely enough)

hope you can read the attachment, I don't know if github accepts that

Op wo 24 okt. 2018 om 09:22 schreef Joop van der Linden <
joopvanderlinden@gmail.com>:

**Comment by nysthi** [comment]
in 0 6 30
