### ISSUE TITLE
Confusing Simpler: Anti-click applied when scanning through slices?

### ISSUE THREAD

**Issue by cschol** [nysthi/nysthi#67]
When scanning through slices the anti-click parameter does not seem to have any effect. I still hear an audible click when switching between slices.

Is the anti-click a crossfade-type functionality?

**Comment by nysthi** [comment]
nope, is an always fadein type
I have to recheck

**Comment by nysthi** [comment]
solved in 0.6.26

**Comment by nysthi** [comment]
solved in 0.6.26 :)
