### ISSUE TITLE
µOperator loses sound when patched and release is turned down on mod env

### ISSUE THREAD

**Issue by fractalgee** [nysthi/nysthi#69]
The attached patch is a simple mod of the one Antonio posted. I added one µEnv and fed it's out into  FM in on µOP2 (top row). It's EOC out is going to release of µEN1 (top row).

Sound starts fine when opened, but now turn down release on µEN2 until no more sound and even after setting it back where it was, all that remains in the output is some dirty noise. and no way I can work out to get it back safe reverting to saved version.
[slims_silentWay.vcv.zip](https://github.com/nysthi/nysthi/files/2418505/slims_silentWay.vcv.zip)

**Comment by nysthi** [comment]
you abused the TIME input of the µOP using an irregular timing coming from the EOC

**Comment by nysthi** [comment]
to recover the patch, remove the patching from µEN3::EOC -> µOP2::TIME-IN and move the OCTAVE or the TUNE knob
