### ISSUE TITLE
Confusing Simpler: Crash when m_nysthi_file_id points to invalid path

### ISSUE THREAD

**Issue by cschol** [nysthi/nysthi#70]
I create a patch on a Mac using `Confusing Simpler`. Its `m_nysthi_file_id` points to a file stored in the cache at `/Users/cschol/Documents`. I move the patch file to a Linux machine where this path does not exist. I open the patch on Linux and hit record. As soon as I stop the recording, the `Confusing Simpler` crashes.

The same happens when I am trying to just **load** a sample into the `Confusing Simpler` instance and the `m_nysthi_file_id` is invalid. Same crash.

Backtrace:
```
(gdb) bt
#0  0x000000b10000007e in  ()
#1  0x00007f8b659a4602 in SoundFileWrite::writeSampleDouble(double) () at /home/cschol/.Rack/plugins/NYSTHI/plugin.so
#2  0x00007f8b65945d6a in confusedSimpler::save_to_file_buffers(char const*, double*, double*, long) () at /home/cschol/.Rack/plugins/NYSTHI/plugin.so
#3  0x00007f8b659408f4 in confusedSimpler::set_samples(double*, double*, long, double) () at /home/cschol/.Rack/plugins/NYSTHI/plugin.so
#4  0x00007f8b65940e7b in confusedSimpler::do_end_recording_operations() () at /home/cschol/.Rack/plugins/NYSTHI/plugin.so
#5  0x00007f8b6594297c in confusedSimpler::step() () at /home/cschol/.Rack/plugins/NYSTHI/plugin.so
#6  0x000000000051f07f in  ()
#7  0x00007f8b7dc72ae4 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f8b7f4f46db in start_thread (arg=0x7f8b2affd700) at pthread_create.c:463
#9  0x00007f8b7d32e88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by nysthi** [comment]
pretty bad ! Thanks for the report !

**Comment by nysthi** [comment]
@cschol I tested it simulating on MAC (removing files and so on...)
do you remember if the "cache" directory was already present on the LINUX sys ? (plugins/NYSTHI/cache)

**Comment by nysthi** [comment]
I simulate also removing the cache directory
both confusing player opened with zero samples
and when I tried to record or load, they registered a cached copy in a new created  cache directory

**Comment by nysthi** [comment]
tested on WIN10, cant't repro
I simulated both, missing file and missing directory

**Comment by nysthi** [comment]
to be tested on linux

**Comment by nysthi** [comment]
this should be solved in 0 6 30
