### ISSUE TITLE
ConfusingSimpler crash when slices seq tries to play past the sample length

### ISSUE THREAD

**Issue by smerkley** [nysthi/nysthi#72]
Load a wav file of a certain length, set up some slice sequence at the end of the file, load a wav file that's shorter and play the slice sequence, crash.

**Comment by nysthi** [comment]
found... 
new rule
if the sample change
all the slice after the end will be removed
all in the middle will have the end cut

in version 0.6.26

**Comment by nysthi** [comment]
soved in 0 6 26
