### ISSUE TITLE
Convolution Request

### ISSUE THREAD

**Issue by ShofB** [nysthi/nysthi#73]
First thanks so much for this (and all of your other) modules.  It would be nice if you could have folders inside the impulse directory.  With even a modest impulse collection it can get pretty crowded.

**Comment by nysthi** [comment]
I'll try it ASAP ;)

**Comment by nysthi** [comment]
coming in 0 6 28
you can add subdirectories (one level) to the RTimpulse directory

**Comment by ShofB** [comment]
Thant will do it.. thanks!
________________________________
