### ISSUE TITLE
Dynamo look ahead bug?

### ISSUE THREAD

**Issue by InductiveOne** [nysthi/nysthi#80]
The look ahead knob seems to be adding much more delay than I expected it to at very low settings. Even at 34ms is feels more like 500ms delay. I also seem to get distortion in limiter mode as soon as the peaks hit the threshold, possibly more distortion at 48k sample rate.

**Comment by InductiveOne** [comment]
![dynamolimdist](https://user-images.githubusercontent.com/43386726/47163469-0559e300-d2c4-11e8-9258-ea89ec34f68f.jpg)

**Comment by patman023** [comment]
seems okay here. [dynamo lookahead.txt](https://github.com/nysthi/nysthi/files/2785054/dynamo.lookahead.txt)

**Comment by nysthi** [comment]
for me is ok, let's close for the v1 coming
