### ISSUE TITLE
janneker: one suggestion and one observation

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#81]
I am very happy with the way Janneker and Jooper are working together.
One observation, though: I find it difficult to set the number of pulses. Very hard to hit the right number.

Then a suggestion. It would be great if there were a "record" mode, where Janneker will be in passive mode. It will count the number of pulses that pass, until you hit "next". Then it starts counting again.
This way you will be able to create (improvise) a song structure on the fly.
This could be a separate record button, but it could also be standard behaviour when Janneker is in passive mode (that is, not active).

**Comment by nysthi** [comment]
ok, I have to think about it

**Comment by nysthi** [comment]
done, in 0.6.30

**Comment by joopvdl** [comment]
In record mode (which is almost exactly what I meant) it would be very
useful if Adding a sequence would also have Janneker Advance to the Next
sequence. So in record mode, triggering add should also trigger next.
This is a great tool. Very powerful.


Op vr 26 okt. 2018 om 15:01 schreef nysthi <notifications@github.com>:

**Comment by nysthi** [comment]
should be already like that, the ADD always ADD at the END (is not visualized on the screen)

**Comment by joopvdl** [comment]
ok, but when you are in scene 1, and you press add, it stays in scene 1
(and scene 2 is added). Or I am mistaken.

Op vr 26 okt. 2018 om 15:14 schreef nysthi <notifications@github.com>:

**Comment by nysthi** [comment]
yes, stays in scene one, but the added is always at the end

**Comment by joopvdl** [comment]
exactly. but my original idea was to create a sequence fron scratch. so you
stsrt the recording, build scene one, add scene two and proceed to that
scene, build scene two, etc.

**Comment by nysthi** [comment]
is just a visual thing, 
I'll add it

**Comment by joopvdl** [comment]
ah, I see

**Comment by joopvdl** [comment]
it's exactly as I imagined. I tried it now.
You are wonderful

**Comment by nysthi** [comment]
check the TIMED too...
I think has some implication with real directing

could be nice to add a "SCALE" time

**Comment by joopvdl** [comment]
you mean scaling time, as in multiply or divide the time values by a
certain amount?

**Comment by nysthi** [comment]
yes, (like I'm already scaling in DOPPLAB or PHASOR)
le't say I've set an event after 80 seconds
and the second after  other 40 secs
and I notice that I want everything slower by 1.5
the scale mode will move 80 --> 120
and 40 --> 60

**Comment by nysthi** [comment]
and I think I have to increase the MAXTIME (otherwise if you need more than 100 secs , you need to use 2 scenes)

**Comment by joopvdl** [comment]
that's great.
you could also scale the pulse counts :)

But I have found a problem.
When I use Janneker (the regular version), for instance when you are making
a groove (currently I am making a reggae groove, because that came up in
the facebook groop), I time everything on the bar. So next scene, exactly
on the bar.
For that I use the trigger buffer from Martin Lueders.
But if I do this, the add-trigger and the pulse come at the same time, so I
get an extra pulse (in this case, there's one pulse per bar)
So if I time everything after 4 bars, I will get 5 bars in every scene.
I hope I explain this well.


Op vr 26 okt. 2018 om 16:30 schreef nysthi <notifications@github.com>:

**Comment by joopvdl** [comment]
Hey Antonio, I don't want to be pushy or so but I'm afraid this post is going to be missed in the daily avalanche of requests and new ideas, so I would like to give it some new attention. I think the quantizing to pulse-issue would be essential for Janneker to function properly.

**Comment by nysthi** [comment]
please describe your request:
in PLAYING MODE if doing ADD or NEXT should jump to the new one to the next pulse ?

**Comment by joopvdl** [comment]
it should wait to jump until the next pulse.

Op zo 4 nov. 2018 om 10:42 schreef nysthi <notifications@github.com>:

**Comment by joopvdl** [comment]
in recording mode

**Comment by nysthi** [comment]
in 0 6 31
if in recording mode
if you press ADD, the reset will happen on the next pulse coming in

you see 
1 -- 2 -- 3 -- 4 
PRESS ADD
a scene with 4 pulses is created and a new one is started in sync

**Comment by joopvdl** [comment]
just one reply for all the information coming in. (Janneker, Jooper, Bivio):
great work, Antonio! Thanks so much. Looking forward to trying all this out.

Op di 13 nov. 2018 om 22:17 schreef nysthi <notifications@github.com>:

**Comment by nysthi** [comment]
released 0 6 31
