### ISSUE TITLE
Magister Fuzz

### ISSUE THREAD

**Issue by WiggyWire** [nysthi/nysthi#83]
There appears to be some sort of click/noise/pop at non-periodic times when this module is used. Even with any setting on the sound. Seems to be some internal thing with the module affecting the signal path.

**Comment by nysthi** [comment]
I'll recheck it, thank you

**Comment by nysthi** [comment]
correction coming

**Comment by nysthi** [comment]
please recheck it with new release

**Comment by WiggyWire** [comment]
Ok, will check now.. you still get the same noises with the new release. Does it need a lot of cpu power?

**Comment by nysthi** [comment]
yes,lot of cpu, I think I have to give block size changeable for the users

**Comment by patman023** [comment]
@WiggyWire was this corrected with the release of 0.6.37?

**Comment by nysthi** [comment]
please open a new issue in v 1.0.0 if reproducible
