### ISSUE TITLE
TIMEX

### ISSUE THREAD

**Issue by WiggyWire** [nysthi/nysthi#84]
Hi, one thing that would be useful in this module is to be able to trigger the on switch for both counters at the same time. At the moment you can trigger counter 1 or counter 2 independently. But sometimes you want to be able to start both counters at the same time. (In my case I set counter 1 to 60 and counter 2 to 120 to be able to switch the recorder on and off for 60 seconds then wait 60 seconds for me to adjust patch settings before the next recording.)

I think there is space above the counter section for such a button. Another thing that would be very useful is the ability to enter counter values, time values using the numpad like in SQ2.

**Comment by nysthi** [comment]
in 0 6 30

**Comment by WiggyWire** [comment]
Thank you.
