### ISSUE TITLE
Seven seas clip audio

### ISSUE THREAD

**Issue by fradsprds** [nysthi/nysthi#85]
I notice that with some type of wavetable (try glitchboy.waw) sevenen seas clip the audio 
the strange thing is that in the begining it was fine even with that wavetable so it could be relate to memory???

**Comment by nysthi** [comment]
where is this "glitchboy.wav" ? is it a wavetable edited in waveedit ?
Or it's a standard wave file ?
can't be a memory problem

**Comment by fradsprds** [comment]
it is from this pack wav files https://waveeditonline.com/wav-files.zip

**Comment by nysthi** [comment]
testing it, can't repro

are you using a MAC ?

can you test connecting it directly to the audio port ? and check again ?

**Comment by fradsprds** [comment]
yes i'm using mac i did it both using a mixer and directly to the audio port in both cases it clip
i also found that it happen with euclidea.waw as well but with most of the wavetable is ok

**Comment by nysthi** [comment]
can you a video recording ?

this is mine using the wave table GLITCHBO.WAV
https://youtu.be/fUrwFi_fam4

no clip 
no audio chain destroyed

**Comment by nysthi** [comment]
so I think you are getting some "CLICKS" not CLIP

1) what is your MAC ? (I think i5 have problems with multithreads)

2) are you using version 0.6.29 ? (if you click on the module with right mouse button what version says ?

**Comment by fradsprds** [comment]
my mac is i7
i'm using version 0.6.29 but it was doing it in the 0.6.28 aswell just with glitchboy.waw and euclidea.waw with other wavetable is working fine

**Comment by fradsprds** [comment]
is strange that if you compare your view with my one you will notice that in the bottom part my view is different and it is exactly where it click # @
![tavola disegno 1 2x-100](https://user-images.githubusercontent.com/44433404/47448003-3011d300-d7bf-11e8-9024-e2eabf405914.jpg)

**Comment by nysthi** [comment]
interessante investigazione!

**Comment by nysthi** [comment]
still can't repro, but I'm adding a check for overflow values !

**Comment by nysthi** [comment]
in 0 6 30 coming

**Comment by fradsprds** [comment]
thank you, its a banging module i'm using it in every patch

**Comment by nysthi** [comment]
there are new feature and improvements coming

**Comment by diimdeep** [comment]
I have clips on Mac, amount depends on audio device block size (256 occasional, 512 lots, 1024 impossible) here is video https://yadi.sk/i/yt4jFG8ScSMbRQ in video fork with multithreading and fps limit, but latest vanilla is same.

**Comment by diimdeep** [comment]
from menu unchecking MULTITHREADED solves clips

**Comment by nysthi** [comment]
so, I guess you have a 2 core computer, correct ?

**Comment by diimdeep** [comment]
2 cores, yes

**Comment by nysthi** [comment]
means that when 7seas is running on extra thread, is always on one of the 2 cores available and already used by RACK (engine and graphic)

**Comment by diimdeep** [comment]
Anyway. IDK, maybe this expected, but when MULTITHREADED is checked and PROCESSING BLOCK SIZES <= Audio device block size, there is clipping.  Here is official Rack video https://yadi.sk/i/IFhFtH0jrx6u3w
