### ISSUE TITLE
NYECHO crashing VCV on win 7

### ISSUE THREAD

**Issue by mizi0** [nysthi/nysthi#87]
Whenever i make a patch with this module involved, then i close VCV, when i re-open the software it stops responding.

win7 x64- i5 3570-16gb Ram-gtx970 4gb
[nyecho.zip](https://github.com/nysthi/nysthi/files/2519550/nyecho.zip)
[details.txt](https://github.com/nysthi/nysthi/files/2519558/details.txt)

**Comment by mizi0** [comment]
If i can help in any way, please let me know

**Comment by Funk-Burasuta** [comment]
An easy and consistent way to reproduce this bug can be done this way:

- Load NYECHOecoeco
- Turn the ERASE HEAD off
- Send something into NYECHO's input
- Turn on a bunch of heads (any amount works)
- Close VCV
- Open VCV
- Voilà!

**Comment by nysthi** [comment]
to be verified

**Comment by patman023** [comment]
confirmed with above method for all except head 1.

VCV Log does not display errors.

Windows error log with consistent 
Faulting application name: Rack.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: plugin.dll, version: 0.0.0.0, time stamp: 0x00000000
***Exception code: 0xc0000005***
Fault offset: 0x00000000000353ae 
    ***(Also 0x0000000000035346, 35207, 35271, 352db)***
Faulting process id: 0xf0
Faulting application start time: 0x01d49beb3414c8b6
***Faulting application path: C:\Program Files\VCV0.6.1\VCV\Rack\Rack.exe
Faulting module path: C:\Users\Pat\Documents\Rack\plugins\NYSTHI\plugin.dll***
Report Id: d9a159aa-d85d-46c0-b2a2-88b9b9c5c5f2
Faulting package full name: 
Faulting package-relative application ID:

**Comment by nysthi** [comment]
thanks guys
I've found what could be the problem

**Comment by nysthi** [comment]
maybe we have winner.... version 0 6 37 !

**Comment by nysthi** [comment]
probably gone !
