### ISSUE TITLE
Janneker Loop Toggle Bug?

### ISSUE THREAD

**Issue by InductiveOne** [nysthi/nysthi#88]
I have managed to get Janneker to loop with the 'Loop' toggle off (and vise versa). Looping mode seems to work fine (10 seconds, loop toggle on, loops successfully) with no keyframe (scene) but as soon as I hit the 'Add' button the function of the loop toggle button reverses. Maybe the button is flipping the value saved in the keyframe? 

Happens the same in Janneker and Janneker Timed.

![jannekerlooptoggle](https://user-images.githubusercontent.com/43386726/47606158-0c78a380-d9de-11e8-82c0-6140eae402d6.jpg)

**Comment by nysthi** [comment]
I cna't repro, or I can understand it


if LOOP is ON yellow is on
and if there are more thatn 1 scene and ACTIVE is ON

the sequencer is looping for all the scenes

BTW I've found another bug: usign the mouse you can increase only by seconds, and not by fractions

**Comment by nysthi** [comment]
PS:
the value of the LOOP is not save in the KF

**Comment by InductiveOne** [comment]
This might just be user error. Let me try to explain.

You load a Janneker Timed and it defaults to loop toggle ON, 1 second scene time, and it is outputting a pulse every 1 second. The current window is counting from 0 to 1 and resetting. 

Click the Add button to add a scene, which should still be a 1 second loop, but instead of looping it counts from 0 to infinity and has a solid 10v signal coming out of the end of scene jack. If you toggle the loop mode OFF it goes back to normal behavior of counting from 0 to 1 and sending out a trig every second. 

This might be the way you meant it to work and I am thinking backwards.

**Comment by nysthi** [comment]
BUG!

**Comment by nysthi** [comment]
corrected
in 0.6.31

**Comment by nysthi** [comment]
released 0 6 31
