### ISSUE TITLE
TIMEX on/off counter buttons second counter not switching off.

### ISSUE THREAD

**Issue by WiggyWire** [nysthi/nysthi#89]
I have found an intermittent issue with TIMEX that you sometimes cannot switch off counter 2. Its always showing its in an on state. This happens even if you re-initialise the module, or connect/disconnect the group start/stop port.

Here is a video showing what I mean:

https://youtu.be/FvkQ5oxxnrM

**Comment by nysthi** [comment]
sorry, I can't repro, I rechecked all the code  and can't see anything wrong

ora I need a patch with REPRODUCIBILITY

are you using a new instance from ZERO ?
(from the menu)

o are you using one coming from an old file ?

**Comment by WiggyWire** [comment]
Hi, I am using 0.6.30. It was a new patch. Its very strange because that error only happens sometimes. For instance tonight I cannot replicate the bug either. Very strange.
