### ISSUE TITLE
Loading wav files into complexSimpler crashes Rack on Mac

### ISSUE THREAD

**Issue by metaphorz** [nysthi/nysthi#9]
This is an intermittent problem but I have noticed it enough to raise an issue. I have gotten some otherwise very nice patches from Patchstorage. These patches include the Simpler module. When I right click to open a new sound sample in this module, Rack crashes. The most recent patch I tried was an uploaded patch called ayn-random-6.vcv. It has some problems in 0.5.0 because of modules whose names have been updated, so I fixed those.

My solution to the crash upon opening a new wav file is solved by me deleting the simpler module from the patch, and creating a brand new one and re-patching. Then, everything works.

I also wonder why when a patch is saved, the WAV files are not saved with it.

This issue seems to be with someone elses patch. If I were to create the patch myself with my own simpler modules, there may not be an issue.

OS: Mac High Sierra

**Comment by metaphorz** [comment]
I might suggest that you send me a VCV file for me to test. If I create it on my machine, Rack will not exhibit a crash. I can include the resulting dump in my reply.

**Comment by nysthi** [comment]
samples are saved in a nysthi/cache directory; are not saved in the VCV files.
So you need to transfer files form cache to cache
would be impossible to save megabytes of data in  the VCV file because the file is autosaved every 15 secs

**Comment by metaphorz** [comment]
I think I am following you, but even if it is impossible to save megabytes of data that compose a WAV file, wouldn't it be possible to save a reference link to the WAV file? For example, if my sample is called MYSAMPLE.WAV, then you can store this reference "MYSAMPLE.WAV" which would have to be located in some agreed-upon, or standard, place in the Rack file hierarchy? In that fashion, one musician can share a patch and the WAV files and give them to another musician. The other musician would then save these WAV files (same names), and everything would work.

If everything in cache, how can a patch with these samplers be shared?

**Comment by nysthi** [comment]
there is no relation to the original file
every load is transformed in memory and a cache WAV file is saved in the nysthi/cache

just move them and you solve the problem...

**Comment by metaphorz** [comment]
I see. I am unsure how cache is structured. Does the cache save only the latest patch info or an accumulation of prior Rack activity?

**Comment by antoniotuzzi** [comment]
every NYsTHI object has a unique ID, that is maintened across savings
so you can pass you patch to other people, but they need that files in your cache

though there is problem with CLONING (duplicate) and it's a RACK problem that I asked to solve (will corrected in 0.6.0 I hope)

**Comment by Virzile** [comment]
Hey there,
Same problem here but on W10 I tried on a blank project it keeps crashing, I even tried with differents types of wav files it crashes all the time.
What should I do?

**Comment by nysthi** [comment]
don't know, 
are you using latest lib  0 5 2 ?

**Comment by metaphorz** [comment]
Virzile: I found that I could create a new patch, create a new instance of Simpler and then load a WAV file (I think this is all that is supported?). My crash issue had to do with opening patches that were created by someone else -- and trying to load a Simpler with a WAV file crashed Rack.

**Comment by Virzile** [comment]
nysthi: Yep i'm using the lastest lib
metaphorz: well I can open a patch from someone else but i can't create a blank patch and load a sample into the simpler, it keeps crashing all the godamn taime :(

**Comment by Virzile** [comment]
Updated to the new sweet as version, problem solved !
Thanks for everything this is awesome !!!

**Comment by nysthi** [comment]
published
v0.5.7
