### ISSUE TITLE
Slicer Quantizer not working?

### ISSUE THREAD

**Issue by ROGAVKA** [nysthi/nysthi#90]
Seems like it just bypasses values now, see screenshot
![quantizerissue](https://user-images.githubusercontent.com/44550443/47618197-54342380-dae1-11e8-928a-0a1192c686b3.jpg)

**Comment by nysthi** [comment]
tested perfectly working

**Comment by nysthi** [comment]
check here
https://youtu.be/Y0uieTOwmOk

it's CV QUANTIZER in EQUAL STEPS
cuts 0 volts to 10v in N STEPS

**Comment by ROGAVKA** [comment]
Yeah, it stopped reproducing after a couple of reboots, guess some problem with rack on my side.

**Comment by nysthi** [comment]
ok, if you have reproducible case, please  let me know!
