### ISSUE TITLE
Janneker & Janneker Timmed record button locking while record port is connected.

### ISSUE THREAD

**Issue by WiggyWire** [nysthi/nysthi#91]
Hi, in both Janneker & Janneker Timmed the record button locks into the on state when the record port is connected. It is not possible to stop recording the event unless you first disconnect the patch cable from the record port. I have made a recording to show what I mean. 

https://youtu.be/CZ3Yst8oYxY

**Comment by nysthi** [comment]
in version 0.6.31

probably you used some very high value

the input is in OR with button, if a value in input was stil over 1.0 (for example using an LFO out)

I changed now, the input value is considered always 0. if < 1.0 and 1 if >= 1.0

BETTER to use  PULSE for that input !

**Comment by nysthi** [comment]
released 0 6 31
