### ISSUE TITLE
4Hands Enable Ins Toggle Bug

### ISSUE THREAD

**Issue by InductiveOne** [nysthi/nysthi#93]
Sometimes this button seems to get stuck on. If I close and re-open rack it is unstuck. Not sure what causes it to happen.

**Comment by nysthi** [comment]
is it connected with a pulse IN ? (the pulse IN always win over TAP)

**Comment by InductiveOne** [comment]
No, happens with no connections. Button is solid yellow and it is using the input jacks. I will see if I can figure out how to make it happen consistently

**Comment by InductiveOne** [comment]
Still not sure why it happens:
https://youtu.be/DAP9cUq2dY8

**Comment by nysthi** [comment]
WOW very strange !

**Comment by nysthi** [comment]
rechecking it

**Comment by nysthi** [comment]
please retest in 0 6 31 when ready

**Comment by patman023** [comment]
@InductiveOne can you verify please?

**Comment by nysthi** [comment]
can't repro
please open a new issue in v 1.0.0 if still present and reproducible
