### ISSUE TITLE
4Hands Feature Request(s)

### ISSUE THREAD

**Issue by InductiveOne** [nysthi/nysthi#94]
One issue I have been thinking about is keeping track of keyframes when you are using Janneker and 4Hands. I think a textbox in the keyframe area that would save like 12-16 char with each keyframe would pretty much solve the organizational issue. Named patterns would be a huge help (to me a least). 

Also, if possible could you add a CV in for the global porta amount? Sorry, I have innate need to modulate everything.

Last one. I thought I remembered one of your modules having a random step button in the keyframe section. I either made that up or I can't find it. It would be cool to have a random step button, or a random mode so the 'next' button went to a random keyframe or something along those lines.

![4handswithradgreenarrows](https://user-images.githubusercontent.com/43386726/47974424-8ca2a700-e077-11e8-9009-d187354aaa8a.jpg)

**Comment by nysthi** [comment]
yes the SQUONK as the RND btn... ;)

**Comment by nysthi** [comment]
cv + vca to global added

**Comment by nysthi** [comment]
text filed added

**Comment by nysthi** [comment]
in 0 6 31

**Comment by nysthi** [comment]
released 0 6 31
