### ISSUE TITLE
bivio, maybe bridges, reset button

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#95]
I think bivio could, at least in my use of it, be more useful with a reset button. This could be a global reset for all three rows of bivio. I like to use it to switch between sections of a composition (patch), and this way you can have the song start in the "start" settings. 
Same for Bridges

And then an idea: Could you make a "one-shot" mode? For Bivio? (Maybe bridges) So the module will respond to incoming pulses, and randomly switch (set by probability button) but then stays in that position until reset. 
This way you can make unpredictable changes into new sections.

**Comment by nysthi** [comment]
for sure !
I'm currently  fighting some REAL deadlines.. :D so just wait a little bit for all
not only this! My PArallales expired and I have to shell out $99 to renew license...  :(

**Comment by nysthi** [comment]
monster change!
like it a lot 

in 0 6 31

**Comment by nysthi** [comment]
released 0 6 31
