### ISSUE TITLE
jooper reset still not functioning properly

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#96]
When jooper is functioning in dual exclusive mode, after reset it will still show this mode but will actually have reset to something else. You can see that the leds on the third rows (left and right) have disappeared. When you press global trig, it gets back to dual exclusive mode.
You can also press the mode button three times to get it back to the right mode. If you are using more than one jooper, you will see that the mode changes (the leds change) but the mode text "dual exclusive, etc" will stay the same when you press the mode button. The button itself will change color.

**Comment by joopvdl** [comment]
haven't figured it out exactly yet, but somehow this has to do with Jooper saving the mode with the scene. Maybe that is correct behaviour, but it's not what I would expect. Will try it out a bit more.

**Comment by nysthi** [comment]
it's a bug...  because before I was assuming the RESET always to EXCLUSIVE

**Comment by nysthi** [comment]
released 0 6 31
