### ISSUE TITLE
janneker data entry

### ISSUE THREAD

**Issue by joopvdl** [nysthi/nysthi#99]
I may have asked this before, but could the same data entry you use in the small sequencers also be available in Janneker? It's a bit hard to set the number of pulses, and that would help a lot.

**Comment by nysthi** [comment]
in vers 0 6 31
---- ADDING a CHEAT SHEET to use it with the KEYBOARD
---- TO use the keyboard your mouse must be placed on top of the JANNEKER
------ "PAGE DOWN" go to the next scene
------ "PAGE UP" go to previous scene
------ "ESCAPE" reload current scene removing current alterations
------ "OPTION/WINDOWKEY `P`" will reset current scene, all scenes will be deleted
------ "OPTION/WINDOWKEY `A`" will add current scene to the scenes list
------ "ENTER (keypad)" add a stage with current values at the end of the sequence
------ "RETURN" (or "OPTION/WINDOWKEY `ENTER (keypad)`") update current stage with current onscreen values
------ "I" insert a stage with current values before the current stage of the sequence
------ "DECIMAL POINT (keypad)" reset current pulse count entering value to 1
------ "+" adds 1 to the current pulses value
------ "-" subtract 1 to the current pulses value
------ "OPTION/WINDOWKEY `-`" will delete current scene, and remove it from list
------ "OPTION/WINDOWKEY `+`" add a stage with current values at the end of the scenes (same as "ENTER (keypad)")
------ 0 1 2 3 4 5 6 7 8 9 are used to entering data
-------- values for modes are:
-------- PULSECOUNTmode from 1 to 9999

**Comment by Scumbag01** [comment]
Some folks don't use a keyboard with page up and down keys. could OPTION/WINDOWKEY up or down arrows be used in place of the pg up and pg down keys?

**Comment by nysthi** [comment]
ok, I'll leave open
for the next release

**Comment by nysthi** [comment]
@Scumbag01 I've added in 6 37 the "COMMAND + arrows" but they works, but clash with main scroller that moves everything

**Comment by nysthi** [comment]
is in
